import type { MilitaryBase } from "./types";

export const basesE: MilitaryBase[] = [
  {
    slug: "ru-kola-gadzhievo",
    name: "Gadzhievo Submarine Base",
    hostCountryCode: "RU",
    region: "Arctic",
    location: "Kola Peninsula, Murmansk Oblast",
    type: "nuclear",
    primaryServiceBranch: "Russian Navy",
    tenantCountryCodes: ["RU"],
    hostedUnits: ["31st Submarine Division"],
    hostedSystems: ["Borei / Borei-A SSBN"],
    role: "Primary SSBN base on the Kola; Bastion concept anchor.",
  },
  {
    slug: "ru-engels",
    name: "Engels-2 Air Base",
    hostCountryCode: "RU",
    region: "Eurasia",
    location: "Saratov Oblast",
    type: "air",
    primaryServiceBranch: "Russian Long-Range Aviation",
    tenantCountryCodes: ["RU"],
    hostedUnits: ["121st Heavy Bomber Aviation Regiment"],
    hostedSystems: ["Tu-160 Blackjack", "Tu-95MS Bear-H"],
    role: "Russia's principal strategic bomber base; struck repeatedly by Ukrainian deep-strike UAVs since 2022.",
  },
  {
    slug: "ru-plesetsk",
    name: "Plesetsk Cosmodrome",
    hostCountryCode: "RU",
    region: "Eurasia",
    location: "Arkhangelsk Oblast",
    type: "space",
    primaryServiceBranch: "Russian Aerospace Forces",
    tenantCountryCodes: ["RU"],
    hostedUnits: ["1st State Test Cosmodrome"],
    hostedSystems: ["RS-28 Sarmat ICBM test", "Yars / Topol-M ICBMs"],
    role: "Russia's primary military cosmodrome and ICBM test range.",
  },
  {
    slug: "ru-sevastopol-contested",
    name: "Sevastopol Naval Base",
    hostCountryCode: "UA",
    region: "Europe",
    location: "Crimea (occupied by Russia since 2014)",
    type: "naval",
    primaryServiceBranch: "Russian Navy (de facto)",
    tenantCountryCodes: ["RU"],
    hostedUnits: ["Black Sea Fleet HQ (de facto)"],
    hostedSystems: ["Slava CG (Moskva sunk 2022)", "Krivak / Admiral Grigorovich frigates", "Kilo-class SSK"],
    role: "Black Sea Fleet HQ since occupation; subject to Ukrainian missile and drone strikes 2022-present.",
    notes: "Crimea is internationally recognized as Ukrainian territory; Russian basing is contested.",
  },
  {
    slug: "by-baranavichy",
    name: "Baranavichy Air Base",
    hostCountryCode: "BY",
    region: "Europe",
    location: "Brest Region",
    type: "air",
    primaryServiceBranch: "Belarusian Air Force",
    tenantCountryCodes: ["BY", "RU"],
    hostedUnits: ["61st Fighter Air Base"],
    hostedSystems: ["Su-30SM", "MiG-29", "Iskander-M (Russian forward deployment)"],
    role: "Belarusian fighter base hosting Russian Iskander-M and tactical-nuclear-shared aircraft.",
  },
  {
    slug: "in-jodhpur",
    name: "Jodhpur Air Force Station",
    hostCountryCode: "IN",
    region: "South Asia",
    location: "Jodhpur, Rajasthan",
    type: "air",
    primaryServiceBranch: "Indian Air Force",
    tenantCountryCodes: ["IN"],
    hostedUnits: ["No. 17 Squadron 'Golden Arrows'"],
    hostedSystems: ["Rafale F3R"],
    role: "Western India Rafale base; covers Pakistan border.",
  },
  {
    slug: "in-thanjavur",
    name: "Thanjavur Air Force Station",
    hostCountryCode: "IN",
    region: "South Asia",
    location: "Tamil Nadu",
    type: "air",
    primaryServiceBranch: "Indian Air Force",
    tenantCountryCodes: ["IN"],
    hostedUnits: ["No. 222 Squadron 'Tigersharks'"],
    hostedSystems: ["Su-30MKI with BrahMos-A"],
    role: "Southern India BrahMos-armed Su-30MKI base covering Indian Ocean approaches.",
  },
  {
    slug: "pk-sargodha",
    name: "PAF Base Mushaf (Sargodha)",
    hostCountryCode: "PK",
    region: "South Asia",
    location: "Sargodha, Punjab",
    type: "air",
    primaryServiceBranch: "Pakistan Air Force",
    tenantCountryCodes: ["PK"],
    hostedUnits: ["Central Air Command"],
    hostedSystems: ["F-16C/D Block 52", "JF-17 Block II"],
    role: "Premier Pakistani fighter base; allegedly hosts portions of Pakistani nuclear-capable air assets.",
  },
  {
    slug: "pk-karachi",
    name: "Karachi Naval Base (PNS Qasim)",
    hostCountryCode: "PK",
    region: "South Asia",
    location: "Karachi",
    type: "naval",
    primaryServiceBranch: "Pakistan Navy",
    tenantCountryCodes: ["PK"],
    hostedUnits: ["Commander Karachi"],
    hostedSystems: ["Tughril-class FFG", "Agosta-90B Khalid SSK"],
    role: "Principal Pakistan Navy base; protects Indian Ocean approaches.",
  },
  {
    slug: "pk-gwadar",
    name: "Gwadar Port",
    hostCountryCode: "PK",
    region: "South Asia",
    location: "Balochistan",
    type: "naval",
    primaryServiceBranch: "Pakistan Navy",
    tenantCountryCodes: ["PK", "CN"],
    hostedUnits: [],
    hostedSystems: [],
    role: "Chinese-financed deep-water port; potential PLA Navy logistics access node under CPEC.",
  },
  {
    slug: "kp-pyongyang-sunan",
    name: "Pyongyang Sunan International Airport (military)",
    hostCountryCode: "KP",
    region: "Indo-Pacific",
    location: "Pyongyang",
    type: "air",
    primaryServiceBranch: "Korean People's Army Air Force",
    tenantCountryCodes: ["KP"],
    hostedUnits: ["KPAAF transport elements"],
    hostedSystems: ["Hwasong-17 ICBM (parade)", "Hwasong-18 solid-fuel ICBM"],
    role: "Site of repeated DPRK ICBM launches and military parades.",
  },
  {
    slug: "kp-sinpo",
    name: "Sinpo South Shipyard",
    hostCountryCode: "KP",
    region: "Indo-Pacific",
    location: "Sinpo, South Hamgyong",
    type: "nuclear",
    primaryServiceBranch: "Korean People's Navy",
    tenantCountryCodes: ["KP"],
    hostedUnits: ["KPN submarine development"],
    hostedSystems: ["Pukguksong-3/-4/-5 SLBM test platforms", "8.24 Yongung SSB"],
    role: "Centerpiece of DPRK SLBM and ballistic-missile submarine development.",
  },
  {
    slug: "kp-punggye-ri",
    name: "Punggye-ri Nuclear Test Site",
    hostCountryCode: "KP",
    region: "Indo-Pacific",
    location: "Kilju County",
    type: "nuclear",
    primaryServiceBranch: "DPRK government",
    tenantCountryCodes: ["KP"],
    hostedUnits: [],
    hostedSystems: [],
    role: "DPRK underground nuclear test site (six tests 2006-2017); portals partly demolished 2018, status uncertain.",
  },
  {
    slug: "id-natuna",
    name: "Natuna Besar Outpost",
    hostCountryCode: "ID",
    region: "Indo-Pacific",
    location: "Natuna Islands",
    type: "joint",
    primaryServiceBranch: "Indonesian Armed Forces",
    tenantCountryCodes: ["ID"],
    hostedUnits: ["Kogasratgab Natuna"],
    hostedSystems: ["Su-30MKM", "C-705 anti-ship missile"],
    role: "Indonesian outpost contesting PRC nine-dash-line claims north of Natuna; expanded since 2020.",
  },
  {
    slug: "fr-cayenne",
    name: "FAG Centre Spatial Guyanais",
    hostCountryCode: "FR",
    region: "South America",
    location: "Kourou, French Guiana",
    type: "space",
    primaryServiceBranch: "Centre national d'études spatiales",
    tenantCountryCodes: ["FR"],
    hostedUnits: ["Forces armées en Guyane"],
    hostedSystems: ["Ariane 6", "Vega-C"],
    role: "European spaceport on the equator; protected by French airborne / 3e REI.",
  },
  {
    slug: "fr-noumea",
    name: "FANC New Caledonia",
    hostCountryCode: "NC",
    region: "Oceania",
    location: "Nouméa",
    type: "joint",
    primaryServiceBranch: "Forces armées en Nouvelle-Calédonie",
    tenantCountryCodes: ["FR"],
    hostedUnits: ["French Pacific Maritime Forces"],
    hostedSystems: ["Falcon 200 Gardian", "P-400 OPV"],
    role: "Principal French Indo-Pacific base; underpins France's Indo-Pacific strategy.",
  },
  {
    slug: "fr-reunion",
    name: "FAZSOI Réunion",
    hostCountryCode: "RE",
    region: "Indo-Pacific",
    location: "La Réunion",
    type: "joint",
    primaryServiceBranch: "Forces armées dans la zone sud de l'océan Indien",
    tenantCountryCodes: ["FR"],
    hostedUnits: ["2e Régiment de parachutistes"],
    hostedSystems: ["Floréal-class light surveillance frigate"],
    role: "French sovereign Indian Ocean basing for Mozambique Channel and southwestern Indian Ocean security.",
  },
  {
    slug: "gb-ascension",
    name: "RAF Ascension Island",
    hostCountryCode: "SH",
    region: "South Atlantic",
    location: "Ascension Island",
    type: "air",
    primaryServiceBranch: "Royal Air Force / US Space Force",
    tenantCountryCodes: ["GB", "US"],
    hostedUnits: ["RAF Ascension Garrison"],
    hostedSystems: ["GPS monitoring station"],
    role: "Atlantic transit hub; supports Falklands airbridge and overhead navigation infrastructure.",
  },
  {
    slug: "es-rota-spanish",
    name: "Naval Station Rota (Spanish Navy)",
    hostCountryCode: "ES",
    region: "Europe",
    location: "Cádiz, Andalusia",
    type: "naval",
    primaryServiceBranch: "Spanish Navy",
    tenantCountryCodes: ["ES", "US"],
    hostedUnits: ["Spanish Naval Air Service"],
    hostedSystems: ["Juan Carlos I (L-61) STOVL/LHD"],
    role: "Joint Spanish-US base; flagship of the Spanish Navy.",
  },
  {
    slug: "lt-rukla",
    name: "Camp Rukla",
    hostCountryCode: "LT",
    region: "Europe",
    location: "Jonava district",
    type: "army",
    primaryServiceBranch: "Lithuanian Armed Forces",
    tenantCountryCodes: ["LT", "DE"],
    hostedUnits: ["NATO eFP Battle Group Lithuania (German-led)", "German Brigade Lithuania (forming)"],
    hostedSystems: ["Leopard 2A6", "PzH 2000", "Boxer"],
    role: "Future host of permanent German brigade for NATO frontline deterrence on the Suwałki Gap approaches.",
  },
  {
    slug: "ee-amari",
    name: "Ämari Air Base",
    hostCountryCode: "EE",
    region: "Europe",
    location: "Harju County",
    type: "air",
    primaryServiceBranch: "Estonian Air Force",
    tenantCountryCodes: ["EE"],
    hostedUnits: ["NATO Baltic Air Policing rotational"],
    hostedSystems: ["Eurofighter / F-35A (rotational)"],
    role: "Eastern Baltic NATO BAP rotational fighter base.",
  },
  {
    slug: "lv-lielvarde",
    name: "Lielvārde Air Base",
    hostCountryCode: "LV",
    region: "Europe",
    location: "Ogre Municipality",
    type: "air",
    primaryServiceBranch: "Latvian National Armed Forces",
    tenantCountryCodes: ["LV"],
    hostedUnits: ["Latvian Air Force HQ"],
    hostedSystems: ["UH-60M Black Hawk"],
    role: "Principal Latvian air operations base.",
  },
  {
    slug: "no-banak",
    name: "Banak Air Station",
    hostCountryCode: "NO",
    region: "Arctic",
    location: "Lakselv, Finnmark",
    type: "air",
    primaryServiceBranch: "Royal Norwegian Air Force",
    tenantCountryCodes: ["NO"],
    hostedUnits: ["330 Squadron SAR detachment"],
    hostedSystems: ["AW101 SAR"],
    role: "Northernmost Norwegian air base; Arctic SAR and surveillance.",
  },
  {
    slug: "is-keflavik",
    name: "Keflavík Air Base",
    hostCountryCode: "IS",
    region: "Arctic",
    location: "Reykjanesbær",
    type: "air",
    primaryServiceBranch: "Icelandic Coast Guard",
    tenantCountryCodes: ["IS", "US"],
    hostedUnits: ["NATO Iceland Air Policing rotational", "US Navy P-8A rotational"],
    hostedSystems: ["P-8A Poseidon (rotational)"],
    role: "GIUK Gap maritime patrol and air policing hub.",
  },
  {
    slug: "us-fort-greely",
    name: "Fort Greely",
    hostCountryCode: "US",
    region: "Arctic",
    location: "Delta Junction, Alaska",
    type: "missile_defense",
    primaryServiceBranch: "US Army",
    tenantCountryCodes: ["US"],
    hostedUnits: ["49th Missile Defense Battalion"],
    hostedSystems: ["Ground-Based Interceptor (GBI)"],
    role: "Primary continental missile defense site for the homeland (against North Korea).",
  },
  {
    slug: "us-vandenberg",
    name: "Vandenberg Space Force Base",
    hostCountryCode: "US",
    region: "North America",
    location: "Lompoc, California",
    type: "space",
    primaryServiceBranch: "US Space Force",
    tenantCountryCodes: ["US"],
    hostedUnits: ["30th Space Wing", "Combined Force Space Component Command"],
    hostedSystems: ["Minuteman III ICBM test", "Falcon 9 / Atlas V launches"],
    role: "Western Range; ICBM test launches and polar satellite launches.",
  },
  {
    slug: "us-malmstrom",
    name: "Malmstrom Air Force Base",
    hostCountryCode: "US",
    region: "North America",
    location: "Great Falls, Montana",
    type: "nuclear",
    primaryServiceBranch: "US Air Force",
    tenantCountryCodes: ["US"],
    hostedUnits: ["341st Missile Wing"],
    hostedSystems: ["Minuteman III ICBM (LGM-30G)"],
    role: "One of three remaining ICBM bases hosting Minuteman III silos; Sentinel modernization pending.",
  },
  {
    slug: "us-minot",
    name: "Minot Air Force Base",
    hostCountryCode: "US",
    region: "North America",
    location: "Minot, North Dakota",
    type: "nuclear",
    primaryServiceBranch: "US Air Force",
    tenantCountryCodes: ["US"],
    hostedUnits: ["91st Missile Wing", "5th Bomb Wing"],
    hostedSystems: ["Minuteman III ICBM", "B-52H Stratofortress"],
    role: "Only US base hosting both ICBMs and bombers; two legs of nuclear triad co-located.",
  },
  {
    slug: "us-warren",
    name: "F.E. Warren Air Force Base",
    hostCountryCode: "US",
    region: "North America",
    location: "Cheyenne, Wyoming",
    type: "nuclear",
    primaryServiceBranch: "US Air Force",
    tenantCountryCodes: ["US"],
    hostedUnits: ["90th Missile Wing"],
    hostedSystems: ["Minuteman III ICBM"],
    role: "Third Minuteman III ICBM wing; future Sentinel host.",
  },
  {
    slug: "us-whiteman",
    name: "Whiteman Air Force Base",
    hostCountryCode: "US",
    region: "North America",
    location: "Knob Noster, Missouri",
    type: "air",
    primaryServiceBranch: "US Air Force",
    tenantCountryCodes: ["US"],
    hostedUnits: ["509th Bomb Wing"],
    hostedSystems: ["B-2 Spirit", "B-21 Raider (incoming)"],
    role: "Sole B-2 Spirit base; will host the B-21 Raider stealth bomber as it enters service.",
  },
];
