import type { MilitaryBase } from "./types";

export const basesA: MilitaryBase[] = [
  {
    slug: "us-naval-station-norfolk",
    name: "Naval Station Norfolk",
    hostCountryCode: "US",
    region: "North America",
    location: "Norfolk, Virginia",
    latitude: 36.95,
    longitude: -76.32,
    type: "naval",
    primaryServiceBranch: "US Navy",
    tenantCountryCodes: ["US"],
    hostedUnits: ["US Fleet Forces Command", "US 2nd Fleet", "Carrier Strike Group 8"],
    hostedSystems: ["Nimitz / Ford-class carriers", "Arleigh Burke-class DDGs", "Virginia-class SSNs"],
    role: "World's largest naval base; principal homeport of the Atlantic Fleet and command hub for Atlantic carrier strike group operations.",
    notes: "Hosts Naval Air Station Oceana for F/A-18E/F and F-35C training-coast deployments.",
  },
  {
    slug: "us-naval-base-san-diego",
    name: "Naval Base San Diego",
    hostCountryCode: "US",
    region: "North America",
    location: "San Diego, California",
    latitude: 32.68,
    longitude: -117.13,
    type: "naval",
    primaryServiceBranch: "US Navy",
    tenantCountryCodes: ["US"],
    hostedUnits: ["US 3rd Fleet (San Diego HQ)", "Naval Surface Forces Pacific"],
    hostedSystems: ["Arleigh Burke DDGs", "Ticonderoga CGs", "Independence-class LCS", "Wasp/America-class LHDs"],
    role: "Principal Pacific homeport for surface combatants and amphibious ready groups.",
  },
  {
    slug: "us-naval-base-kitsap",
    name: "Naval Base Kitsap (Bangor)",
    hostCountryCode: "US",
    region: "North America",
    location: "Bremerton/Bangor, Washington",
    latitude: 47.74,
    longitude: -122.73,
    type: "nuclear",
    primaryServiceBranch: "US Navy",
    tenantCountryCodes: ["US"],
    hostedUnits: ["Submarine Group 9", "Strategic Weapons Facility Pacific"],
    hostedSystems: ["Ohio-class SSBN", "Trident II D5 SLBMs"],
    role: "Pacific SSBN homeport; one of two strategic weapons facilities for the US sea-based deterrent.",
  },
  {
    slug: "us-naval-station-kings-bay",
    name: "Naval Submarine Base Kings Bay",
    hostCountryCode: "US",
    region: "North America",
    location: "Kings Bay, Georgia",
    latitude: 30.79,
    longitude: -81.52,
    type: "nuclear",
    primaryServiceBranch: "US Navy",
    tenantCountryCodes: ["US"],
    hostedUnits: ["Submarine Group 10", "Strategic Weapons Facility Atlantic"],
    hostedSystems: ["Ohio-class SSBN", "Trident II D5 SLBMs"],
    role: "Atlantic SSBN homeport; companion strategic weapons facility for sea-based nuclear deterrent.",
  },
  {
    slug: "us-pearl-harbor",
    name: "Joint Base Pearl Harbor-Hickam",
    hostCountryCode: "US",
    region: "Indo-Pacific",
    location: "Honolulu, Hawaii",
    latitude: 21.36,
    longitude: -157.96,
    type: "joint",
    primaryServiceBranch: "US Navy / US Air Force",
    tenantCountryCodes: ["US"],
    hostedUnits: [
      "US Pacific Fleet HQ",
      "Submarine Force US Pacific Fleet",
      "Pacific Air Forces (PACAF)",
      "15th Wing",
    ],
    hostedSystems: ["Virginia / Los Angeles SSNs", "F-22A Raptor (Hawaii Air Guard)", "C-17A Globemaster III"],
    role: "Forward HQ for Indo-Pacific naval and air operations; home of Pacific Fleet command and Indo-Pacific Command-aligned forces.",
  },
  {
    slug: "us-andersen-afb",
    name: "Andersen Air Force Base",
    hostCountryCode: "US",
    region: "Indo-Pacific",
    location: "Yigo, Guam",
    latitude: 13.58,
    longitude: 144.92,
    type: "air",
    primaryServiceBranch: "US Air Force",
    tenantCountryCodes: ["US"],
    hostedUnits: ["36th Wing", "Pacific Air Forces"],
    hostedSystems: ["B-52H Stratofortress (rotational BTF)", "B-1B Lancer (rotational)", "B-2 Spirit (rotational)", "RQ-4 Global Hawk"],
    role: "Continuous Bomber Presence and rotational bomber task force hub for the Western Pacific.",
  },
  {
    slug: "us-camp-blaz",
    name: "Marine Corps Base Camp Blaz",
    hostCountryCode: "US",
    region: "Indo-Pacific",
    location: "Dededo, Guam",
    type: "joint",
    primaryServiceBranch: "US Marine Corps",
    tenantCountryCodes: ["US"],
    hostedUnits: ["III Marine Expeditionary Force (rotational)"],
    hostedSystems: [],
    role: "First new Marine Corps base in 70 years; receives Marines relocated from Okinawa under US-Japan realignment.",
  },
  {
    slug: "us-yokosuka",
    name: "Commander Fleet Activities Yokosuka",
    hostCountryCode: "JP",
    region: "Indo-Pacific",
    location: "Yokosuka, Kanagawa",
    latitude: 35.29,
    longitude: 139.66,
    type: "naval",
    primaryServiceBranch: "US Navy",
    tenantCountryCodes: ["US"],
    hostedUnits: ["US 7th Fleet HQ", "Carrier Strike Group 5"],
    hostedSystems: ["USS Ronald Reagan (CVN-76) / USS George Washington (CVN-73)", "Aegis DDGs / CGs"],
    role: "Only forward-deployed US carrier strike group homeport; nerve center of Pacific Fleet forward operations.",
  },
  {
    slug: "us-kadena-ab",
    name: "Kadena Air Base",
    hostCountryCode: "JP",
    region: "Indo-Pacific",
    location: "Okinawa",
    latitude: 26.36,
    longitude: 127.77,
    type: "air",
    primaryServiceBranch: "US Air Force",
    tenantCountryCodes: ["US"],
    hostedUnits: ["18th Wing", "Pacific Air Forces"],
    hostedSystems: ["F-15C Eagle (retiring; rotational F-22 / F-35 / F-15EX)", "KC-135R Stratotanker", "RC-135V/W Rivet Joint"],
    role: "Largest US Air Force base in the Pacific; primary fighter and ISR hub closest to Taiwan and the Korean peninsula.",
  },
  {
    slug: "us-misawa-ab",
    name: "Misawa Air Base",
    hostCountryCode: "JP",
    region: "Indo-Pacific",
    location: "Misawa, Aomori",
    latitude: 40.7,
    longitude: 141.37,
    type: "air",
    primaryServiceBranch: "US Air Force / Japan ASDF",
    tenantCountryCodes: ["US", "JP"],
    hostedUnits: ["35th Fighter Wing", "JASDF Northern Air Defense Force"],
    hostedSystems: ["F-16CJ/CM Fighting Falcon (Wild Weasel)", "F-35A (JASDF)"],
    role: "Joint US-Japan northern Honshu fighter base; F-16 SEAD/DEAD coverage of Sea of Japan.",
  },
  {
    slug: "us-yokota-ab",
    name: "Yokota Air Base",
    hostCountryCode: "JP",
    region: "Indo-Pacific",
    location: "Fussa, Tokyo",
    latitude: 35.75,
    longitude: 139.34,
    type: "air",
    primaryServiceBranch: "US Air Force",
    tenantCountryCodes: ["US"],
    hostedUnits: ["US Forces Japan HQ", "5th Air Force HQ", "374th Airlift Wing"],
    hostedSystems: ["C-130J Super Hercules", "CV-22B Osprey", "C-12J"],
    role: "USFJ headquarters; airlift hub for Japan and the western Pacific.",
  },
  {
    slug: "us-iwakuni",
    name: "Marine Corps Air Station Iwakuni",
    hostCountryCode: "JP",
    region: "Indo-Pacific",
    location: "Iwakuni, Yamaguchi",
    latitude: 34.14,
    longitude: 132.24,
    type: "air",
    primaryServiceBranch: "US Marine Corps",
    tenantCountryCodes: ["US", "JP"],
    hostedUnits: ["1st Marine Aircraft Wing forward elements", "Carrier Air Wing 5 (when ashore)"],
    hostedSystems: ["F-35B Lightning II", "F/A-18 Hornet", "EA-18G Growler"],
    role: "Forward Marine and Navy fixed-wing hub supporting carrier air wing operations from Japan.",
  },
  {
    slug: "us-camp-humphreys",
    name: "United States Army Garrison Humphreys",
    hostCountryCode: "KR",
    region: "Indo-Pacific",
    location: "Pyeongtaek",
    latitude: 36.97,
    longitude: 127.03,
    type: "joint",
    primaryServiceBranch: "US Army",
    tenantCountryCodes: ["US"],
    hostedUnits: ["Eighth Army HQ", "United States Forces Korea HQ", "ROK-US Combined Forces Command"],
    hostedSystems: ["AH-64E Apache", "MQ-1C Gray Eagle"],
    role: "Largest overseas US Army installation; consolidated USFK headquarters since 2018.",
  },
  {
    slug: "us-osan-ab",
    name: "Osan Air Base",
    hostCountryCode: "KR",
    region: "Indo-Pacific",
    location: "Pyeongtaek",
    latitude: 37.09,
    longitude: 127.03,
    type: "air",
    primaryServiceBranch: "US Air Force",
    tenantCountryCodes: ["US"],
    hostedUnits: ["7th Air Force HQ", "51st Fighter Wing"],
    hostedSystems: ["A-10C Thunderbolt II", "F-16C/D Block 40"],
    role: "Forward fighter and CAS hub for the Korean peninsula; co-located with ROK Air Force Operations Command.",
  },
  {
    slug: "us-kunsan-ab",
    name: "Kunsan Air Base",
    hostCountryCode: "KR",
    region: "Indo-Pacific",
    location: "Gunsan",
    type: "air",
    primaryServiceBranch: "US Air Force / ROK Air Force",
    tenantCountryCodes: ["US", "KR"],
    hostedUnits: ["8th Fighter Wing", "ROKAF 38th Fighter Group"],
    hostedSystems: ["F-16C/D Block 40", "KF-16 Fighting Falcon"],
    role: "Western coast Korean peninsula fighter base; survivable second F-16 wing.",
  },
  {
    slug: "us-ramstein-ab",
    name: "Ramstein Air Base",
    hostCountryCode: "DE",
    region: "Europe",
    location: "Ramstein-Miesenbach",
    latitude: 49.44,
    longitude: 7.6,
    type: "air",
    primaryServiceBranch: "US Air Force",
    tenantCountryCodes: ["US"],
    hostedUnits: ["US Air Forces in Europe-Air Forces Africa HQ", "Allied Air Command", "86th Airlift Wing"],
    hostedSystems: ["C-130J Super Hercules", "C-21A Learjet"],
    role: "USAFE-AFAFRICA headquarters; principal Atlantic-Europe airlift hub and AOR command node.",
  },
  {
    slug: "us-spangdahlem-ab",
    name: "Spangdahlem Air Base",
    hostCountryCode: "DE",
    region: "Europe",
    location: "Spangdahlem, Rhineland-Palatinate",
    type: "air",
    primaryServiceBranch: "US Air Force",
    tenantCountryCodes: ["US"],
    hostedUnits: ["52nd Fighter Wing"],
    hostedSystems: ["F-16CM Fighting Falcon (SEAD)", "F-35A (replacing F-16 from 2025)"],
    role: "Forward USAFE fighter base; SEAD/DEAD wing for European theater.",
  },
  {
    slug: "us-buchel-ab",
    name: "Büchel Air Base",
    hostCountryCode: "DE",
    region: "Europe",
    location: "Büchel, Rhineland-Palatinate",
    type: "nuclear",
    primaryServiceBranch: "Luftwaffe",
    tenantCountryCodes: ["US", "DE"],
    hostedUnits: ["Tactical Air Wing 33", "USAF Munitions Support Squadron"],
    hostedSystems: ["Tornado IDS (DCA, retiring)", "F-35A (incoming)", "B61-12 (US weapons under nuclear sharing)"],
    role: "German DCA host for US B61 weapons under NATO nuclear sharing arrangement.",
  },
  {
    slug: "us-rota",
    name: "Naval Station Rota",
    hostCountryCode: "ES",
    region: "Europe",
    location: "Cádiz, Andalusia",
    latitude: 36.64,
    longitude: -6.35,
    type: "naval",
    primaryServiceBranch: "Spanish Navy / US Navy",
    tenantCountryCodes: ["US", "ES"],
    hostedUnits: ["Forward-Deployed Naval Forces Europe", "Destroyer Squadron 60"],
    hostedSystems: ["Arleigh Burke DDGs (Aegis BMD)"],
    role: "Forward Aegis BMD destroyer homeport supporting NATO European Phased Adaptive Approach.",
  },
  {
    slug: "us-aviano-ab",
    name: "Aviano Air Base",
    hostCountryCode: "IT",
    region: "Europe",
    location: "Aviano, Friuli",
    type: "air",
    primaryServiceBranch: "US Air Force / Italian Air Force",
    tenantCountryCodes: ["US", "IT"],
    hostedUnits: ["31st Fighter Wing"],
    hostedSystems: ["F-16CM Fighting Falcon"],
    role: "Sole USAFE fighter wing in southern Europe; rapid Mediterranean and Balkan response.",
  },
  {
    slug: "us-incirlik-ab",
    name: "Incirlik Air Base",
    hostCountryCode: "TR",
    region: "Middle East",
    location: "Adana",
    latitude: 37.0,
    longitude: 35.42,
    type: "nuclear",
    primaryServiceBranch: "Turkish Air Force",
    tenantCountryCodes: ["US", "TR"],
    hostedUnits: ["39th Air Base Wing"],
    hostedSystems: ["B61-12 (US weapons stored)", "rotational tankers and ISR"],
    role: "US tactical nuclear weapons storage under NATO nuclear sharing; status periodically debated amid Turkey-US tensions.",
  },
  {
    slug: "us-al-udeid-ab",
    name: "Al Udeid Air Base",
    hostCountryCode: "QA",
    region: "Middle East",
    location: "Al Udeid",
    latitude: 25.12,
    longitude: 51.32,
    type: "air",
    primaryServiceBranch: "Qatar Emiri Air Force / US Air Force",
    tenantCountryCodes: ["US", "QA", "GB"],
    hostedUnits: ["US Air Forces Central forward HQ", "Combined Air Operations Center"],
    hostedSystems: ["KC-135 / KC-46 tankers", "RC-135 ISR", "rotational fighters and bombers"],
    role: "AFCENT forward HQ and CAOC controlling air operations across the Middle East and Central Asia.",
  },
  {
    slug: "us-al-dhafra-ab",
    name: "Al Dhafra Air Base",
    hostCountryCode: "AE",
    region: "Middle East",
    location: "Abu Dhabi",
    type: "air",
    primaryServiceBranch: "UAE Air Force / US Air Force",
    tenantCountryCodes: ["US", "AE", "FR"],
    hostedUnits: ["380th Air Expeditionary Wing", "French Air and Space Force detachment"],
    hostedSystems: ["F-22A Raptor (rotational)", "F-35A (rotational)", "KC-10 / KC-46 tankers", "RQ-4 Global Hawk"],
    role: "Major Gulf air hub for US/coalition air policing and ISR; hosts French Rafale detachment.",
  },
  {
    slug: "us-camp-arifjan",
    name: "Camp Arifjan",
    hostCountryCode: "KW",
    region: "Middle East",
    location: "Al Ahmadi Governorate",
    type: "army",
    primaryServiceBranch: "US Army",
    tenantCountryCodes: ["US"],
    hostedUnits: ["US Army Central forward elements"],
    hostedSystems: [],
    role: "Forward Army logistics hub for the Gulf and Iraq-Syria operations.",
  },
  {
    slug: "us-camp-lemonnier",
    name: "Camp Lemonnier",
    hostCountryCode: "DJ",
    region: "Africa",
    location: "Djibouti City",
    latitude: 11.55,
    longitude: 43.16,
    type: "joint",
    primaryServiceBranch: "US Navy",
    tenantCountryCodes: ["US"],
    hostedUnits: ["Combined Joint Task Force-Horn of Africa"],
    hostedSystems: ["MQ-9 Reaper", "P-8A Poseidon (rotational)"],
    role: "Only enduring US base on the African continent; Horn of Africa counter-terror and Bab-el-Mandeb security node.",
  },
  {
    slug: "us-diego-garcia",
    name: "Naval Support Facility Diego Garcia",
    hostCountryCode: "GB",
    region: "Indo-Pacific",
    location: "Diego Garcia, BIOT",
    latitude: -7.31,
    longitude: 72.41,
    type: "joint",
    primaryServiceBranch: "US Navy / Royal Navy",
    tenantCountryCodes: ["US", "GB"],
    hostedUnits: ["Maritime Prepositioning Ships Squadron 2"],
    hostedSystems: ["B-2 Spirit (rotational)", "B-1B Lancer (rotational)", "P-8A Poseidon"],
    role: "Strategic Indian Ocean basing for prepositioning, bomber rotations, and maritime ISR.",
  },
  {
    slug: "us-thule-pituffik",
    name: "Pituffik Space Base (Thule)",
    hostCountryCode: "DK",
    region: "Arctic",
    location: "Greenland",
    latitude: 76.53,
    longitude: -68.7,
    type: "space",
    primaryServiceBranch: "US Space Force",
    tenantCountryCodes: ["US", "DK"],
    hostedUnits: ["821st Space Base Group"],
    hostedSystems: ["Upgraded Early Warning Radar (UEWR)", "Space surveillance sensors"],
    role: "Northernmost US installation; missile warning, space surveillance, and Arctic surveillance node.",
  },
  {
    slug: "us-fairford-raf",
    name: "RAF Fairford",
    hostCountryCode: "GB",
    region: "Europe",
    location: "Gloucestershire",
    type: "air",
    primaryServiceBranch: "Royal Air Force",
    tenantCountryCodes: ["GB", "US"],
    hostedUnits: ["501st Combat Support Wing detachment"],
    hostedSystems: ["B-52H Stratofortress (rotational BTF)", "B-1B (rotational)", "B-2 Spirit (rotational)"],
    role: "Standing forward operating site for US strategic bombers in Europe.",
  },
  {
    slug: "us-mildenhall-raf",
    name: "RAF Mildenhall",
    hostCountryCode: "GB",
    region: "Europe",
    location: "Suffolk",
    type: "air",
    primaryServiceBranch: "Royal Air Force / US Air Force",
    tenantCountryCodes: ["US", "GB"],
    hostedUnits: ["100th Air Refueling Wing", "352nd Special Operations Wing"],
    hostedSystems: ["KC-135 Stratotanker", "CV-22B Osprey", "MC-130J Commando II"],
    role: "European air-refueling and SOF aviation hub.",
  },
  {
    slug: "us-lakenheath-raf",
    name: "RAF Lakenheath",
    hostCountryCode: "GB",
    region: "Europe",
    location: "Suffolk",
    type: "air",
    primaryServiceBranch: "Royal Air Force / US Air Force",
    tenantCountryCodes: ["US", "GB"],
    hostedUnits: ["48th Fighter Wing"],
    hostedSystems: ["F-15E Strike Eagle", "F-35A Lightning II", "F-15EX Eagle II (replacing F-15C)"],
    role: "Europe's only USAF F-35A wing; principal NATO fast-jet base in the UK.",
  },
];
