import type { MilitaryBase } from "./types";

export const basesB: MilitaryBase[] = [
  {
    slug: "uk-clyde-faslane",
    name: "HMNB Clyde (Faslane)",
    hostCountryCode: "GB",
    region: "Europe",
    location: "Argyll and Bute, Scotland",
    latitude: 56.06,
    longitude: -4.82,
    type: "nuclear",
    primaryServiceBranch: "Royal Navy",
    tenantCountryCodes: ["GB"],
    hostedUnits: ["UK Submarine Service"],
    hostedSystems: [
      "Vanguard-class SSBN",
      "Astute-class SSN",
      "Trident II D5 SLBM",
    ],
    role: "Sole UK SSBN base; foundation of the UK continuous-at-sea deterrent (CASD).",
  },
  {
    slug: "uk-coningsby",
    name: "RAF Coningsby",
    hostCountryCode: "GB",
    region: "Europe",
    location: "Lincolnshire",
    type: "air",
    primaryServiceBranch: "Royal Air Force",
    tenantCountryCodes: ["GB"],
    hostedUnits: ["No. 3 Squadron", "No. 11 Squadron", "No. 29 Squadron"],
    hostedSystems: ["Eurofighter Typhoon FGR4"],
    role: "Southern UK QRA Typhoon base for air policing.",
  },
  {
    slug: "uk-lossiemouth",
    name: "RAF Lossiemouth",
    hostCountryCode: "GB",
    region: "Europe",
    location: "Moray, Scotland",
    type: "air",
    primaryServiceBranch: "Royal Air Force",
    tenantCountryCodes: ["GB"],
    hostedUnits: [
      "No. 1 Squadron",
      "No. 2 Squadron",
      "No. 6 Squadron",
      "120 Sqn (P-8A)",
    ],
    hostedSystems: ["Eurofighter Typhoon FGR4", "P-8A Poseidon MRA1"],
    role: "Northern UK QRA base; UK maritime patrol hub covering GIUK approaches.",
  },
  {
    slug: "uk-akrotiri",
    name: "RAF Akrotiri",
    hostCountryCode: "CY",
    region: "Middle East",
    location: "Cyprus (UK Sovereign Base Area)",
    type: "air",
    primaryServiceBranch: "Royal Air Force",
    tenantCountryCodes: ["GB"],
    hostedUnits: ["No. 84 Squadron"],
    hostedSystems: [
      "Typhoon FGR4 (rotational)",
      "Voyager KC2/KC3",
      "Sentinel R1 (retired) / RC-135W rotational",
    ],
    role: "UK Sovereign Base Area; Eastern Mediterranean strike, ISR, and basing hub.",
  },
  {
    slug: "uk-mount-pleasant",
    name: "RAF Mount Pleasant",
    hostCountryCode: "FK",
    region: "South Atlantic",
    location: "Falkland Islands",
    type: "joint",
    primaryServiceBranch: "Royal Air Force",
    tenantCountryCodes: ["GB"],
    hostedUnits: ["No. 1435 Flight"],
    hostedSystems: [
      "Typhoon FGR4 (4 aircraft)",
      "Sky Sabre (CAMM) air defence",
    ],
    role: "Falklands sovereignty deterrent; sole UK strategic basing in South Atlantic.",
  },
  {
    slug: "uk-gibraltar",
    name: "British Forces Gibraltar",
    hostCountryCode: "GI",
    region: "Europe",
    location: "Gibraltar",
    type: "joint",
    primaryServiceBranch: "Royal Navy",
    tenantCountryCodes: ["GB"],
    hostedUnits: ["Royal Gibraltar Regiment", "Royal Navy Gibraltar Squadron"],
    hostedSystems: [],
    role: "Strategic basing controlling western approach to the Mediterranean.",
  },
  {
    slug: "fr-saint-dizier",
    name: "Base aérienne 113 Saint-Dizier",
    hostCountryCode: "FR",
    region: "Europe",
    location: "Saint-Dizier, Haute-Marne",
    type: "nuclear",
    primaryServiceBranch: "Armée de l'air et de l'espace",
    tenantCountryCodes: ["FR"],
    hostedUnits: ["EC 1/4 Gascogne", "EC 2/4 La Fayette"],
    hostedSystems: ["Rafale B/C with ASMP-A nuclear cruise missile"],
    role: "Primary French air-component nuclear deterrent (FAS) base.",
  },
  {
    slug: "fr-istres",
    name: "Base aérienne 125 Istres-Le Tubé",
    hostCountryCode: "FR",
    region: "Europe",
    location: "Istres, Bouches-du-Rhône",
    type: "air",
    primaryServiceBranch: "Armée de l'air et de l'espace",
    tenantCountryCodes: ["FR"],
    hostedUnits: ["GRV 2/91 Bretagne (tankers)", "FAS support"],
    hostedSystems: ["A330 MRTT Phénix", "Rafale (ASMP-A backup)"],
    role: "Strategic refueling backbone for French air-component deterrent and expeditionary operations.",
  },
  {
    slug: "fr-ile-longue",
    name: "Île Longue",
    hostCountryCode: "FR",
    region: "Europe",
    location: "Brest, Brittany",
    type: "nuclear",
    primaryServiceBranch: "Marine nationale",
    tenantCountryCodes: ["FR"],
    hostedUnits: ["Force océanique stratégique (FOST)"],
    hostedSystems: ["Triomphant-class SSBN", "M51.3 SLBM"],
    role: "Sole French SSBN base; foundation of the sea-component nuclear deterrent.",
  },
  {
    slug: "fr-toulon",
    name: "Toulon Naval Base",
    hostCountryCode: "FR",
    region: "Europe",
    location: "Toulon, Var",
    type: "naval",
    primaryServiceBranch: "Marine nationale",
    tenantCountryCodes: ["FR"],
    hostedUnits: ["French Mediterranean Fleet"],
    hostedSystems: [
      "Charles de Gaulle (R91)",
      "Suffren-class SSN",
      "FREMM frigates",
    ],
    role: "Largest French naval base; principal Mediterranean fleet homeport.",
  },
  {
    slug: "fr-djibouti-fdj",
    name: "Forces françaises stationnées à Djibouti (FFDj)",
    hostCountryCode: "DJ",
    region: "Africa",
    location: "Djibouti City",
    type: "joint",
    primaryServiceBranch: "French Armed Forces",
    tenantCountryCodes: ["FR"],
    hostedUnits: ["5e Régiment interarmes d'outre-mer"],
    hostedSystems: ["Mirage 2000-5 (rotational)"],
    role: "Largest French overseas base; Horn of Africa and Indian Ocean projection node.",
  },
  {
    slug: "de-buchel",
    name: "Büchel Air Base (Bundeswehr)",
    hostCountryCode: "DE",
    region: "Europe",
    location: "Büchel, Rhineland-Palatinate",
    type: "nuclear",
    primaryServiceBranch: "Luftwaffe",
    tenantCountryCodes: ["DE", "US"],
    hostedUnits: ["Tactical Air Wing 33"],
    hostedSystems: ["Tornado IDS (DCA)", "F-35A (incoming)", "B61-12 (US)"],
    role: "German DCA host for B61 weapons under NATO nuclear sharing.",
  },
  {
    slug: "nl-volkel",
    name: "Volkel Air Base",
    hostCountryCode: "NL",
    region: "Europe",
    location: "Uden, North Brabant",
    type: "nuclear",
    primaryServiceBranch: "Royal Netherlands Air Force",
    tenantCountryCodes: ["NL", "US"],
    hostedUnits: ["312 Squadron", "313 Squadron"],
    hostedSystems: ["F-35A Lightning II (DCA)", "B61-12 (US)"],
    role: "Dutch DCA F-35A host for NATO nuclear sharing.",
  },
  {
    slug: "be-kleine-brogel",
    name: "Kleine Brogel Air Base",
    hostCountryCode: "BE",
    region: "Europe",
    location: "Peer, Limburg",
    type: "nuclear",
    primaryServiceBranch: "Belgian Air Component",
    tenantCountryCodes: ["BE", "US"],
    hostedUnits: ["10th Tactical Wing"],
    hostedSystems: [
      "F-16AM (retiring)",
      "F-35A Lightning II (incoming)",
      "B61-12 (US)",
    ],
    role: "Belgian DCA host for NATO nuclear sharing; transitioning to F-35A platform.",
  },
  {
    slug: "it-aviano",
    name: "Aviano Air Base (Italian Air Force)",
    hostCountryCode: "IT",
    region: "Europe",
    location: "Aviano, Friuli-Venezia Giulia",
    type: "air",
    primaryServiceBranch: "Italian Air Force",
    tenantCountryCodes: ["IT", "US"],
    hostedUnits: [
      "Italian Air Force 51° Stormo (offsite)",
      "USAF 31st Fighter Wing",
    ],
    hostedSystems: ["F-16CM (US)"],
    role: "Joint Italian-US base; sole USAFE fighter wing in southern Europe.",
  },
  {
    slug: "it-ghedi",
    name: "Ghedi Air Base",
    hostCountryCode: "IT",
    region: "Europe",
    location: "Ghedi, Lombardy",
    type: "nuclear",
    primaryServiceBranch: "Italian Air Force",
    tenantCountryCodes: ["IT", "US"],
    hostedUnits: ["6º Stormo"],
    hostedSystems: [
      "Tornado IDS (DCA, retiring)",
      "F-35A (transitioning)",
      "B61-12 (US)",
    ],
    role: "Italian DCA host for NATO nuclear sharing; F-35A conversion underway.",
  },
  {
    slug: "it-sigonella",
    name: "Naval Air Station Sigonella",
    hostCountryCode: "IT",
    region: "Europe",
    location: "Catania, Sicily",
    type: "joint",
    primaryServiceBranch: "Italian Air Force / US Navy",
    tenantCountryCodes: ["IT", "US"],
    hostedUnits: ["US Navy P-8A detachment", "Italian 41° Stormo"],
    hostedSystems: ["P-8A Poseidon", "MQ-4C Triton", "ATR 72 MPA"],
    role: "Mediterranean MPA hub for US and Italian maritime patrol.",
  },
  {
    slug: "es-moron",
    name: "Morón Air Base",
    hostCountryCode: "ES",
    region: "Europe",
    location: "Morón de la Frontera, Andalusia",
    type: "joint",
    primaryServiceBranch: "Spanish Air Force / US Marine Corps",
    tenantCountryCodes: ["ES", "US"],
    hostedUnits: [
      "Special Purpose Marine Air-Ground Task Force Crisis Response - Africa",
    ],
    hostedSystems: ["MV-22 Osprey", "KC-130J"],
    role: "US AFRICOM rapid-response hub on the Iberian Peninsula.",
  },
  {
    slug: "pl-redzikowo",
    name: "Aegis Ashore Redzikowo",
    hostCountryCode: "PL",
    region: "Europe",
    location: "Redzikowo, Pomerania",
    type: "missile_defense",
    primaryServiceBranch: "US Navy",
    tenantCountryCodes: ["PL", "US"],
    hostedUnits: ["Aegis Ashore Missile Defense System Poland"],
    hostedSystems: ["SM-3 Block IIA", "SPY-1D radar"],
    role: "Northern node of NATO European Phased Adaptive Approach BMD; declared operational late 2024.",
  },
  {
    slug: "ro-deveselu",
    name: "Aegis Ashore Deveselu",
    hostCountryCode: "RO",
    region: "Europe",
    location: "Deveselu, Olt",
    type: "missile_defense",
    primaryServiceBranch: "US Navy",
    tenantCountryCodes: ["RO", "US"],
    hostedUnits: ["Aegis Ashore Missile Defense System Romania"],
    hostedSystems: ["SM-3 Block IB", "SPY-1D radar"],
    role: "Southern Aegis Ashore node defending NATO southern flank.",
  },
  {
    slug: "ro-mihail-kogalniceanu",
    name: "Mihail Kogălniceanu Air Base",
    hostCountryCode: "RO",
    region: "Europe",
    location: "Constanța",
    type: "air",
    primaryServiceBranch: "Romanian Air Force",
    tenantCountryCodes: ["RO", "US"],
    hostedUnits: ["57th Air Base", "US Army V Corps Forward (rotational)"],
    hostedSystems: ["F-16AM/BM", "F-35A Lightning II (incoming)"],
    role: "Major Black Sea NATO posture hub; expanding to largest NATO base in Europe.",
  },
  {
    slug: "no-evenes",
    name: "Evenes Air Station",
    hostCountryCode: "NO",
    region: "Europe",
    location: "Evenes, Nordland",
    type: "air",
    primaryServiceBranch: "Royal Norwegian Air Force",
    tenantCountryCodes: ["NO"],
    hostedUnits: ["133 Air Wing"],
    hostedSystems: ["P-8A Poseidon", "F-35A (QRA forward)"],
    role: "Northern Norway QRA + maritime patrol hub watching Russian Northern Fleet.",
  },
  {
    slug: "no-orland",
    name: "Ørland Air Station",
    hostCountryCode: "NO",
    region: "Europe",
    location: "Ørlandet, Trøndelag",
    type: "air",
    primaryServiceBranch: "Royal Norwegian Air Force",
    tenantCountryCodes: ["NO"],
    hostedUnits: ["132 Air Wing"],
    hostedSystems: ["F-35A Lightning II"],
    role: "Norwegian F-35A main operating base.",
  },
  {
    slug: "no-haakonsvern",
    name: "Haakonsvern Naval Base",
    hostCountryCode: "NO",
    region: "Europe",
    location: "Bergen",
    type: "naval",
    primaryServiceBranch: "Royal Norwegian Navy",
    tenantCountryCodes: ["NO"],
    hostedUnits: ["Norwegian Submarine Service", "Frigate Force"],
    hostedSystems: ["Fridtjof Nansen-class FFG", "Ula-class SSK"],
    role: "Largest naval base in Northern Europe; submarine homeport adjacent to GIUK approaches.",
  },
  {
    slug: "fi-rovaniemi",
    name: "Rovaniemi Air Base",
    hostCountryCode: "FI",
    region: "Europe",
    location: "Rovaniemi, Lapland",
    type: "air",
    primaryServiceBranch: "Finnish Air Force",
    tenantCountryCodes: ["FI"],
    hostedUnits: ["Lapland Air Command"],
    hostedSystems: ["F/A-18C Hornet (replacement F-35A)"],
    role: "Northern Finland QRA base on Arctic flank; closest fighter base to Russian Kola.",
  },
  {
    slug: "se-satenas",
    name: "F 7 Såtenäs",
    hostCountryCode: "SE",
    region: "Europe",
    location: "Lidköping",
    type: "air",
    primaryServiceBranch: "Swedish Air Force",
    tenantCountryCodes: ["SE"],
    hostedUnits: ["Skaraborg Wing"],
    hostedSystems: [
      "JAS 39E Gripen E (training)",
      "C-130H Hercules",
      "C-17 (Heavy Airlift Wing detachment)",
    ],
    role: "Swedish Gripen fleet training and conversion hub.",
  },
  {
    slug: "se-muskö",
    name: "Muskö Naval Base",
    hostCountryCode: "SE",
    region: "Europe",
    location: "Stockholm archipelago",
    type: "naval",
    primaryServiceBranch: "Swedish Navy",
    tenantCountryCodes: ["SE"],
    hostedUnits: ["Swedish Submarine Flotilla"],
    hostedSystems: ["Gotland-class SSK", "Visby-class corvette"],
    role: "Hardened underground naval base; submarine and corvette homeport.",
  },
  {
    slug: "tr-incirlik-tr",
    name: "Incirlik Air Base (Türk Hava Kuvvetleri)",
    hostCountryCode: "TR",
    region: "Middle East",
    location: "Adana",
    type: "joint",
    primaryServiceBranch: "Turkish Air Force",
    tenantCountryCodes: ["TR", "US"],
    hostedUnits: ["10. Tanker Üs Komutanlığı"],
    hostedSystems: ["KC-135R (Turkish)", "B61-12 (US, NATO sharing)"],
    role: "Strategic Turkish-US base hosting NATO weapons; periodically tense political status.",
  },
  {
    slug: "tr-konya",
    name: "Konya Air Base",
    hostCountryCode: "TR",
    region: "Middle East",
    location: "Konya",
    type: "air",
    primaryServiceBranch: "Turkish Air Force",
    tenantCountryCodes: ["TR"],
    hostedUnits: ["3rd Main Jet Base", "AEW Group"],
    hostedSystems: ["E-7T Peace Eagle AEW&C", "F-16C/D"],
    role: "Turkish AEW&C and central-Anatolia fighter hub.",
  },
];
