import type { MilitaryBase } from "./types";

export const basesF: MilitaryBase[] = [
  // Additional Russian bases
  {
    slug: "ru-olenya",
    name: "Olenya Air Base",
    hostCountryCode: "RU",
    region: "Arctic",
    location: "Murmansk Oblast",
    type: "air",
    primaryServiceBranch: "Russian Long-Range Aviation",
    tenantCountryCodes: ["RU"],
    hostedUnits: ["40th Composite Aviation Regiment"],
    hostedSystems: ["Tu-22M3 Backfire", "Tu-95MS Bear-H"],
    role: "Strategic bomber base on the Kola; key node for North Atlantic operations.",
  },
  {
    slug: "ru-ukrainka",
    name: "Ukrainka Air Base",
    hostCountryCode: "RU",
    region: "Indo-Pacific",
    location: "Amur Oblast",
    type: "air",
    primaryServiceBranch: "Russian Long-Range Aviation",
    tenantCountryCodes: ["RU"],
    hostedUnits: ["79th Heavy Bomber Aviation Regiment"],
    hostedSystems: ["Tu-95MS Bear-H"],
    role: "Far Eastern strategic bomber base for Pacific operations.",
  },
  {
    slug: "ru-belaya",
    name: "Belaya Air Base",
    hostCountryCode: "RU",
    region: "Eurasia",
    location: "Irkutsk Oblast",
    type: "air",
    primaryServiceBranch: "Russian Aerospace Forces",
    tenantCountryCodes: ["RU"],
    hostedUnits: ["200th Heavy Bomber Aviation Regiment"],
    hostedSystems: ["Tu-22M3 Backfire"],
    role: "Forward bomber base; struck repeatedly by Ukrainian deep-strike UAVs.",
  },
  {
    slug: "ru-vidyayevo",
    name: "Vidyayevo Submarine Base",
    hostCountryCode: "RU",
    region: "Arctic",
    location: "Kola Peninsula",
    type: "naval",
    primaryServiceBranch: "Russian Navy",
    tenantCountryCodes: ["RU"],
    hostedUnits: ["7th Submarine Division"],
    hostedSystems: ["Yasen / Yasen-M SSGN/SSN"],
    role: "Northern Fleet SSGN homeport; Yasen-class operations against Atlantic.",
  },
  {
    slug: "ru-tartus",
    name: "Tartus Naval Facility",
    hostCountryCode: "SY",
    region: "Middle East",
    location: "Tartus",
    type: "naval",
    primaryServiceBranch: "Russian Navy",
    tenantCountryCodes: ["RU"],
    hostedUnits: ["Russian 720th Logistics Support Point"],
    hostedSystems: ["Project 22350 Admiral Gorshkov frigates (visiting)"],
    role: "Russia's only Mediterranean naval base; supports Mediterranean Squadron operations.",
  },

  // PLA / China
  {
    slug: "cn-east-sea-ningbo",
    name: "Ningbo Naval Base",
    hostCountryCode: "CN",
    region: "Indo-Pacific",
    location: "Ningbo, Zhejiang",
    type: "naval",
    primaryServiceBranch: "PLA Navy",
    tenantCountryCodes: ["CN"],
    hostedUnits: ["East Sea Fleet HQ"],
    hostedSystems: ["Type 052D / Type 055 destroyers", "CV-17 Shandong"],
    role: "Fleet HQ for the East Sea Fleet; covers Taiwan Strait and East China Sea.",
  },
  {
    slug: "cn-zhanjiang",
    name: "Zhanjiang Naval Base",
    hostCountryCode: "CN",
    region: "Indo-Pacific",
    location: "Zhanjiang, Guangdong",
    type: "naval",
    primaryServiceBranch: "PLA Navy",
    tenantCountryCodes: ["CN"],
    hostedUnits: ["South Sea Fleet HQ"],
    hostedSystems: ["Type 052D destroyers", "Type 075 LHD"],
    role: "South Sea Fleet HQ; principal nexus for South China Sea operations.",
  },
  {
    slug: "cn-rocket-force-bases",
    name: "Yu'nan Brigade (PLARF)",
    hostCountryCode: "CN",
    region: "Indo-Pacific",
    location: "Eastern China (specific site classified)",
    type: "missile_defense",
    primaryServiceBranch: "PLA Rocket Force",
    tenantCountryCodes: ["CN"],
    hostedUnits: ["PLARF Eastern Theatre Command brigades"],
    hostedSystems: ["DF-17", "DF-21D", "DF-26"],
    role: "Forward PLARF deployment area for anti-ship and conventional/nuclear strike against Taiwan/Japan.",
  },

  // PLA in disputed territories
  {
    slug: "cn-mischief-reef",
    name: "Meiji Reef (Mischief Reef)",
    hostCountryCode: "CN",
    region: "Indo-Pacific",
    location: "Spratly Islands",
    type: "joint",
    primaryServiceBranch: "PLA Navy / PLA Air Force",
    tenantCountryCodes: ["CN"],
    hostedUnits: ["Reef garrison"],
    hostedSystems: [
      "Anti-ship cruise missiles",
      "Surface-to-air missiles",
      "Reconnaissance aircraft",
    ],
    role: "Militarized PRC outpost in the Spratlys; located within Philippine EEZ per 2016 ruling.",
    notes:
      "Mischief Reef lies within Philippine EEZ; PCA ruling found Chinese activities inconsistent with UNCLOS.",
  },
  {
    slug: "cn-subi-reef",
    name: "Zhubi Reef (Subi Reef)",
    hostCountryCode: "CN",
    region: "Indo-Pacific",
    location: "Spratly Islands",
    type: "joint",
    primaryServiceBranch: "PLA Navy / PLA Air Force",
    tenantCountryCodes: ["CN"],
    hostedUnits: ["Reef garrison"],
    hostedSystems: ["Anti-ship cruise missiles", "SAMs", "3 km airstrip"],
    role: "Militarized PRC outpost in the Spratlys; near Pag-asa (PH-occupied Thitu Island).",
  },

  // UK additions
  {
    slug: "uk-portsmouth",
    name: "HMNB Portsmouth",
    hostCountryCode: "GB",
    region: "Europe",
    location: "Portsmouth",
    type: "naval",
    primaryServiceBranch: "Royal Navy",
    tenantCountryCodes: ["GB"],
    hostedUnits: ["Portsmouth Flotilla"],
    hostedSystems: [
      "HMS Queen Elizabeth (R08)",
      "HMS Prince of Wales (R09)",
      "Type 45 destroyers",
    ],
    role: "Home of the surface fleet including the Royal Navy carriers and Type 45s.",
  },
  {
    slug: "uk-devonport",
    name: "HMNB Devonport",
    hostCountryCode: "GB",
    region: "Europe",
    location: "Plymouth",
    type: "naval",
    primaryServiceBranch: "Royal Navy",
    tenantCountryCodes: ["GB"],
    hostedUnits: ["Devonport Flotilla", "Submarine Refit Complex"],
    hostedSystems: ["Type 23 frigates", "Astute-class SSN"],
    role: "Largest naval base in Western Europe; SSN refit and ASW frigate hub.",
  },
  {
    slug: "uk-marham",
    name: "RAF Marham",
    hostCountryCode: "GB",
    region: "Europe",
    location: "Norfolk",
    type: "air",
    primaryServiceBranch: "Royal Air Force",
    tenantCountryCodes: ["GB"],
    hostedUnits: ["No. 617 Squadron 'Dambusters'", "No. 207 Squadron"],
    hostedSystems: ["F-35B Lightning II"],
    role: "UK F-35B operational base; Lightning Force HQ.",
  },

  // France additions
  {
    slug: "fr-mont-de-marsan",
    name: "Base aérienne 118 Mont-de-Marsan",
    hostCountryCode: "FR",
    region: "Europe",
    location: "Mont-de-Marsan, Landes",
    type: "air",
    primaryServiceBranch: "Armée de l'air et de l'espace",
    tenantCountryCodes: ["FR"],
    hostedUnits: ["EC 1/30 Côte d'Argent", "EC 2/30 Normandie-Niemen"],
    hostedSystems: ["Rafale B/C"],
    role: "Major French Rafale base; tactical evaluation and operational test.",
  },
  {
    slug: "fr-cazaux",
    name: "Base aérienne 120 Cazaux",
    hostCountryCode: "FR",
    region: "Europe",
    location: "Cazaux, Gironde",
    type: "air",
    primaryServiceBranch: "Armée de l'air et de l'espace",
    tenantCountryCodes: ["FR", "SG (training detachment)"],
    hostedUnits: [
      "EAC 00.314 'Christian Martell'",
      "Singaporean Alpha Jet detachment",
    ],
    hostedSystems: ["Alpha Jet trainer", "Mirage 2000 (legacy)"],
    role: "French air training base; hosts Singaporean Air Force training detachment.",
  },
  {
    slug: "fr-saint-christol",
    name: "Plateau d'Albion (closed nuclear missile site)",
    hostCountryCode: "FR",
    region: "Europe",
    location: "Saint-Christol, Vaucluse",
    type: "nuclear",
    primaryServiceBranch: "Armée de l'air (former)",
    tenantCountryCodes: ["FR"],
    hostedUnits: [
      "Foreign Legion 2nd Foreign Engineer Regiment (current tenant)",
    ],
    hostedSystems: ["Former S3D IRBM silos (deactivated 1996)"],
    role: "Former French ground-based ICBM site; now Foreign Legion engineer base.",
  },
  {
    slug: "fr-orleans",
    name: "Base aérienne 123 Orléans-Bricy",
    hostCountryCode: "FR",
    region: "Europe",
    location: "Orléans, Loiret",
    type: "air",
    primaryServiceBranch: "Armée de l'air et de l'espace",
    tenantCountryCodes: ["FR"],
    hostedUnits: ["ET 1/61 'Touraine'", "ET 3/61 'Poitou' (SOF airlift)"],
    hostedSystems: ["A400M Atlas", "C-130J Super Hercules"],
    role: "French strategic and tactical airlift hub.",
  },

  // Germany / Netherlands
  {
    slug: "de-laage",
    name: "Laage Air Base",
    hostCountryCode: "DE",
    region: "Europe",
    location: "Laage, Mecklenburg",
    type: "air",
    primaryServiceBranch: "Luftwaffe",
    tenantCountryCodes: ["DE"],
    hostedUnits: ["Tactical Air Wing 73 'Steinhoff'"],
    hostedSystems: ["Eurofighter Typhoon"],
    role: "German Eurofighter operational conversion unit.",
  },
  {
    slug: "de-wittmund",
    name: "Wittmund Air Base",
    hostCountryCode: "DE",
    region: "Europe",
    location: "Wittmund, Lower Saxony",
    type: "air",
    primaryServiceBranch: "Luftwaffe",
    tenantCountryCodes: ["DE"],
    hostedUnits: ["Tactical Air Wing 71 'Richthofen'"],
    hostedSystems: ["Eurofighter Typhoon"],
    role: "Northern Germany QRA Eurofighter base.",
  },
  {
    slug: "nl-leeuwarden",
    name: "Leeuwarden Air Base",
    hostCountryCode: "NL",
    region: "Europe",
    location: "Leeuwarden, Friesland",
    type: "air",
    primaryServiceBranch: "Royal Netherlands Air Force",
    tenantCountryCodes: ["NL"],
    hostedUnits: ["322 Squadron", "323 Squadron"],
    hostedSystems: ["F-35A Lightning II"],
    role: "Dutch F-35A QRA and conversion base.",
  },

  // Eastern Europe expansion
  {
    slug: "pl-krzesiny",
    name: "Krzesiny Air Base",
    hostCountryCode: "PL",
    region: "Europe",
    location: "Poznań",
    type: "air",
    primaryServiceBranch: "Polish Air Force",
    tenantCountryCodes: ["PL"],
    hostedUnits: ["31. Baza Lotnictwa Taktycznego"],
    hostedSystems: ["F-16C/D Block 52+", "F-35A (incoming)"],
    role: "Major Polish F-16 and future F-35A operations base.",
  },
  {
    slug: "pl-malbork",
    name: "Malbork Air Base",
    hostCountryCode: "PL",
    region: "Europe",
    location: "Malbork, Pomerania",
    type: "air",
    primaryServiceBranch: "Polish Air Force",
    tenantCountryCodes: ["PL"],
    hostedUnits: ["41. Baza Lotnictwa Szkolnego"],
    hostedSystems: ["MiG-29 (retiring)"],
    role: "Polish base near the Russian Kaliningrad exclave.",
  },
  {
    slug: "pl-gdynia",
    name: "Gdynia Naval Base",
    hostCountryCode: "PL",
    region: "Europe",
    location: "Gdynia, Pomerania",
    type: "naval",
    primaryServiceBranch: "Polish Navy",
    tenantCountryCodes: ["PL"],
    hostedUnits: ["Polish Navy 3rd Ship Flotilla"],
    hostedSystems: ["Orkan-class missile boat", "Kobben-class SSK (retiring)"],
    role: "Principal Polish naval base on the Baltic.",
  },
  {
    slug: "ee-tapa",
    name: "Tapa Army Base",
    hostCountryCode: "EE",
    region: "Europe",
    location: "Tapa, Lääne-Viru",
    type: "army",
    primaryServiceBranch: "Estonian Defence Forces",
    tenantCountryCodes: ["EE", "GB"],
    hostedUnits: [
      "1st Infantry Brigade",
      "NATO eFP Battle Group Estonia (UK-led)",
    ],
    hostedSystems: ["Challenger 2 (UK rotational)", "K9 Kõu SP howitzer"],
    role: "Estonian frontline brigade base hosting NATO eFP UK-led battlegroup.",
  },
  {
    slug: "lv-adazi",
    name: "Camp Ādaži",
    hostCountryCode: "LV",
    region: "Europe",
    location: "Ādaži, near Riga",
    type: "army",
    primaryServiceBranch: "Latvian Land Forces",
    tenantCountryCodes: ["LV", "CA"],
    hostedUnits: [
      "Latvian Mechanized Infantry Brigade",
      "NATO eFP Battle Group Latvia (Canadian-led)",
    ],
    hostedSystems: ["Patria 6x6", "M109A5OE SP howitzer"],
    role: "Largest Latvian military base; NATO eFP Canadian-led battlegroup expanding to brigade.",
  },
  {
    slug: "lt-pabrade",
    name: "General Silvestras Žukauskas Training Area (Pabradė)",
    hostCountryCode: "LT",
    region: "Europe",
    location: "Pabradė",
    type: "army",
    primaryServiceBranch: "Lithuanian Land Forces",
    tenantCountryCodes: ["LT", "US", "DE"],
    hostedUnits: [
      "Lithuanian Iron Wolf Mechanized Brigade",
      "US rotational forces",
    ],
    hostedSystems: ["Boxer", "PzH 2000"],
    role: "Largest Lithuanian training area; rotational US and German presence.",
  },

  // Indo-Pacific additions
  {
    slug: "kr-suwon",
    name: "Suwon Air Base",
    hostCountryCode: "KR",
    region: "Indo-Pacific",
    location: "Suwon",
    type: "air",
    primaryServiceBranch: "ROK Air Force",
    tenantCountryCodes: ["KR"],
    hostedUnits: ["10th Fighter Wing"],
    hostedSystems: ["KF-16C/D"],
    role: "Northern Seoul air defence base; closest fighter base to DMZ.",
  },
  {
    slug: "jp-hyakuri",
    name: "Hyakuri Air Base",
    hostCountryCode: "JP",
    region: "Indo-Pacific",
    location: "Ibaraki",
    type: "air",
    primaryServiceBranch: "JASDF",
    tenantCountryCodes: ["JP"],
    hostedUnits: ["7th Air Wing"],
    hostedSystems: ["F-2A/B Viper Zero"],
    role: "JASDF F-2 main operating base in central Japan.",
  },
  {
    slug: "jp-tsuiki",
    name: "Tsuiki Air Base",
    hostCountryCode: "JP",
    region: "Indo-Pacific",
    location: "Fukuoka",
    type: "air",
    primaryServiceBranch: "JASDF",
    tenantCountryCodes: ["JP"],
    hostedUnits: ["8th Air Wing"],
    hostedSystems: ["F-2A/B"],
    role: "Western Japan JASDF base covering Korea Strait approaches.",
  },
  {
    slug: "tw-taoyuan",
    name: "Taoyuan Air Base",
    hostCountryCode: "TW",
    region: "Indo-Pacific",
    location: "Taoyuan",
    type: "air",
    primaryServiceBranch: "ROC Air Force",
    tenantCountryCodes: ["TW"],
    hostedUnits: ["3rd Tactical Fighter Wing"],
    hostedSystems: ["Mirage 2000-5", "F-16V (rotation)"],
    role: "Northern Taiwan air defence base.",
  },
  {
    slug: "tw-tainan",
    name: "Tainan Air Base",
    hostCountryCode: "TW",
    region: "Indo-Pacific",
    location: "Tainan",
    type: "air",
    primaryServiceBranch: "ROC Air Force",
    tenantCountryCodes: ["TW"],
    hostedUnits: ["443rd Tactical Fighter Wing"],
    hostedSystems: ["F-CK-1 IDF"],
    role: "Southern Taiwan IDF main operating base.",
  },
  {
    slug: "th-utapao",
    name: "U-Tapao International Airport / Naval Air Station",
    hostCountryCode: "TH",
    region: "Indo-Pacific",
    location: "Rayong",
    type: "joint",
    primaryServiceBranch: "Royal Thai Navy",
    tenantCountryCodes: ["TH", "US"],
    hostedUnits: ["Royal Thai Navy 1st Air Wing"],
    hostedSystems: ["S-70B-2 Seahawk", "Cobra Gold rotational US forces"],
    role: "Joint Thai-US air base hosting annual Cobra Gold exercise.",
  },
  {
    slug: "ph-edca-fort-magsaysay",
    name: "Fort Magsaysay (EDCA)",
    hostCountryCode: "PH",
    region: "Indo-Pacific",
    location: "Nueva Ecija, Luzon",
    type: "joint",
    primaryServiceBranch: "Philippine Army",
    tenantCountryCodes: ["PH", "US"],
    hostedUnits: [
      "7th Infantry Division",
      "US rotational training detachments",
    ],
    hostedSystems: [],
    role: "Largest Philippine Army installation; major EDCA site for joint training.",
  },
  {
    slug: "ph-edca-camilo-osias",
    name: "Camilo Osias Naval Base (EDCA)",
    hostCountryCode: "PH",
    region: "Indo-Pacific",
    location: "Cagayan, northern Luzon",
    type: "naval",
    primaryServiceBranch: "Philippine Navy",
    tenantCountryCodes: ["PH", "US"],
    hostedUnits: [],
    hostedSystems: [],
    role: "EDCA site closest to Bashi Channel and Taiwan; significant 2023 EDCA expansion site.",
  },

  // Middle East additions
  {
    slug: "il-ramat-david",
    name: "Ramat David Airbase",
    hostCountryCode: "IL",
    region: "Middle East",
    location: "Northern Israel",
    type: "air",
    primaryServiceBranch: "Israeli Air Force",
    tenantCountryCodes: ["IL"],
    hostedUnits: ["109 Squadron 'Valley'", "117 'First Jet'"],
    hostedSystems: ["F-16I Sufa"],
    role: "Northern Israel F-16I base near Lebanese and Syrian borders.",
  },
  {
    slug: "il-ovda",
    name: "Ovda Airbase",
    hostCountryCode: "IL",
    region: "Middle East",
    location: "Negev",
    type: "air",
    primaryServiceBranch: "Israeli Air Force",
    tenantCountryCodes: ["IL"],
    hostedUnits: ["IAF Flight Academy advanced phase"],
    hostedSystems: ["TA-4J Skyhawk (training)", "Aggressor squadron F-16"],
    role: "Southern Israel air training and aggressor base.",
  },
  {
    slug: "sa-king-faisal-naval",
    name: "King Faisal Naval Base, Jeddah",
    hostCountryCode: "SA",
    region: "Middle East",
    location: "Jeddah",
    type: "naval",
    primaryServiceBranch: "Royal Saudi Navy",
    tenantCountryCodes: ["SA"],
    hostedUnits: ["RSN Western Fleet"],
    hostedSystems: ["Al Riyadh-class FFG", "Sawari II frigates"],
    role: "Principal Red Sea naval base of the Royal Saudi Navy.",
  },
  {
    slug: "sa-king-abdulaziz-jubail",
    name: "King Abdulaziz Naval Base, Jubail",
    hostCountryCode: "SA",
    region: "Middle East",
    location: "Jubail",
    type: "naval",
    primaryServiceBranch: "Royal Saudi Navy",
    tenantCountryCodes: ["SA"],
    hostedUnits: ["RSN Eastern Fleet"],
    hostedSystems: ["Al Jubail-class corvette", "Badr-class corvette"],
    role: "Principal Persian Gulf naval base of the Royal Saudi Navy.",
  },

  // Africa additions
  {
    slug: "fr-cnes-kourou-protection",
    name: "Centre spatial guyanais (military protection)",
    hostCountryCode: "FR",
    region: "South America",
    location: "Kourou, French Guiana",
    type: "space",
    primaryServiceBranch: "French Armed Forces",
    tenantCountryCodes: ["FR"],
    hostedUnits: ["3e REI", "9e RIMa"],
    hostedSystems: ["Crotale NG (legacy)", "Mistral 3 SHORAD"],
    role: "Military protection of European spaceport during launches.",
  },
  {
    slug: "tr-aksaray",
    name: "Aksaz Naval Base (Aegean)",
    hostCountryCode: "TR",
    region: "Europe",
    location: "Marmaris",
    type: "naval",
    primaryServiceBranch: "Turkish Navy",
    tenantCountryCodes: ["TR"],
    hostedUnits: ["Turkish Aegean Sea Command"],
    hostedSystems: ["Reis-class (Type 214TN) SSK", "İstanbul-class FFG"],
    role: "Turkish Aegean Fleet base.",
  },
  {
    slug: "tr-mersin",
    name: "Mersin Naval Base",
    hostCountryCode: "TR",
    region: "Middle East",
    location: "Mersin",
    type: "naval",
    primaryServiceBranch: "Turkish Navy",
    tenantCountryCodes: ["TR"],
    hostedUnits: ["Turkish Mediterranean Sea Command"],
    hostedSystems: ["Ada-class corvette", "MILGEM"],
    role: "Eastern Mediterranean Turkish Navy base; covers Cyprus approaches.",
  },

  // Latin America additions
  {
    slug: "br-itaguai-prosub",
    name: "Naval Complex of Itaguaí (PROSUB)",
    hostCountryCode: "BR",
    region: "South America",
    location: "Itaguaí, Rio de Janeiro",
    type: "nuclear",
    primaryServiceBranch: "Brazilian Navy",
    tenantCountryCodes: ["BR"],
    hostedUnits: ["Submarine Force Command"],
    hostedSystems: ["Riachuelo-class (Scorpène) SSK"],
    role: "Brazilian SSN program (PROSUB) shipyard with French Naval Group cooperation.",
  },
  {
    slug: "co-tolemaida",
    name: "Tolemaida Air Base",
    hostCountryCode: "CO",
    region: "South America",
    location: "Tolemaida, Tolima",
    type: "joint",
    primaryServiceBranch: "Colombian Armed Forces",
    tenantCountryCodes: ["CO", "US"],
    hostedUnits: ["Colombian Special Forces", "US rotational training"],
    hostedSystems: ["UH-60M Black Hawk", "AT-29B Super Tucano"],
    role: "Largest Colombian military base; major US training partnership site.",
  },
  {
    slug: "cl-punta-arenas",
    name: "Punta Arenas Naval Base",
    hostCountryCode: "CL",
    region: "South America",
    location: "Punta Arenas",
    type: "naval",
    primaryServiceBranch: "Chilean Navy",
    tenantCountryCodes: ["CL"],
    hostedUnits: ["Chilean Antarctic Squadron"],
    hostedSystems: ["Almirante Williams-class FFG", "Antarctic patrol vessels"],
    role: "Southern Cone naval base; gateway to Chilean Antarctic operations.",
  },

  // North America additions
  {
    slug: "us-norad-cheyenne",
    name: "Cheyenne Mountain Space Force Station",
    hostCountryCode: "US",
    region: "North America",
    location: "Colorado Springs, Colorado",
    type: "space",
    primaryServiceBranch: "US Space Force / NORAD",
    tenantCountryCodes: ["US", "CA"],
    hostedUnits: ["NORAD alternate command center"],
    hostedSystems: ["Space surveillance and missile-warning operations"],
    role: "Hardened underground bunker; alternate NORAD command and missile-warning center.",
  },
  {
    slug: "us-peterson",
    name: "Peterson Space Force Base",
    hostCountryCode: "US",
    region: "North America",
    location: "Colorado Springs, Colorado",
    type: "space",
    primaryServiceBranch: "US Space Force",
    tenantCountryCodes: ["US"],
    hostedUnits: ["Space Operations Command HQ", "NORAD HQ", "USSPACECOM HQ"],
    hostedSystems: ["Space surveillance C2"],
    role: "USSPACECOM and NORAD headquarters; primary US space operations command node.",
  },
  {
    slug: "us-schriever",
    name: "Schriever Space Force Base",
    hostCountryCode: "US",
    region: "North America",
    location: "Colorado Springs, Colorado",
    type: "space",
    primaryServiceBranch: "US Space Force",
    tenantCountryCodes: ["US"],
    hostedUnits: ["50th Space Wing", "Space Delta 6"],
    hostedSystems: ["GPS Master Control Station"],
    role: "GPS satellite constellation control; military satellite command and control hub.",
  },
];
