import type { MilitaryBase } from "./types";

export const basesC: MilitaryBase[] = [
  {
    slug: "jp-yokosuka-jmsdf",
    name: "JMSDF Yokosuka District",
    hostCountryCode: "JP",
    region: "Indo-Pacific",
    location: "Yokosuka, Kanagawa",
    type: "naval",
    primaryServiceBranch: "JMSDF",
    tenantCountryCodes: ["JP", "US"],
    hostedUnits: ["Self-Defense Fleet HQ", "Escort Flotilla 1"],
    hostedSystems: ["JS Izumo (DDH-183)", "Maya-class DDG", "Kongō-class DDG"],
    role: "Largest JMSDF base; co-located with US 7th Fleet HQ.",
  },
  {
    slug: "jp-sasebo",
    name: "JMSDF Sasebo District / US Fleet Activities Sasebo",
    hostCountryCode: "JP",
    region: "Indo-Pacific",
    location: "Sasebo, Nagasaki",
    type: "naval",
    primaryServiceBranch: "JMSDF / US Navy",
    tenantCountryCodes: ["JP", "US"],
    hostedUnits: ["Escort Flotilla 2", "Amphibious Squadron 11 (US)"],
    hostedSystems: ["JS Kaga (DDH-184) — F-35B carrier conversion", "Wasp-class LHD (US)", "MCM ships"],
    role: "Forward amphibious and DDH base; F-35B sea-control hub closest to Korean and Taiwan straits.",
  },
  {
    slug: "jp-iwakuni-jmsdf",
    name: "MCAS Iwakuni / JMSDF Iwakuni Air Base",
    hostCountryCode: "JP",
    region: "Indo-Pacific",
    location: "Iwakuni, Yamaguchi",
    type: "air",
    primaryServiceBranch: "JMSDF / US Marine Corps",
    tenantCountryCodes: ["JP", "US"],
    hostedUnits: ["Air Group 31 (JMSDF)", "Marine Aircraft Group 12"],
    hostedSystems: ["P-1 (JMSDF)", "F-35B (US)", "F/A-18 (US)"],
    role: "Joint Japanese-US air base hosting carrier air wing fixed-wing assets ashore.",
  },
  {
    slug: "jp-naha",
    name: "Naha Air Base",
    hostCountryCode: "JP",
    region: "Indo-Pacific",
    location: "Okinawa",
    type: "air",
    primaryServiceBranch: "JASDF",
    tenantCountryCodes: ["JP"],
    hostedUnits: ["Southwestern Air Defense Force", "9th Air Wing"],
    hostedSystems: ["F-15J / F-15JSI"],
    role: "Closest Japanese fighter base to Senkaku and Taiwan; expanded F-15 wing for Southwestern defense.",
  },
  {
    slug: "kr-jeju",
    name: "Jeju Naval Base",
    hostCountryCode: "KR",
    region: "Indo-Pacific",
    location: "Jeju Island",
    type: "naval",
    primaryServiceBranch: "Republic of Korea Navy",
    tenantCountryCodes: ["KR"],
    hostedUnits: ["7th Mobile Flotilla"],
    hostedSystems: ["Sejong the Great-class DDG", "Dosan Ahn Changho-class SSK"],
    role: "Southern naval base supporting submarine and Aegis destroyer operations across the East China Sea approaches.",
  },
  {
    slug: "kr-busan",
    name: "Busan Naval Base",
    hostCountryCode: "KR",
    region: "Indo-Pacific",
    location: "Busan",
    type: "naval",
    primaryServiceBranch: "Republic of Korea Navy",
    tenantCountryCodes: ["KR", "US"],
    hostedUnits: ["ROK Fleet Command"],
    hostedSystems: ["Sejong the Great-class DDG", "Chang Bogo-class SSK", "Dokdo-class LPH"],
    role: "Principal ROK Navy headquarters port; hosts US Navy logistics for the peninsula.",
  },
  {
    slug: "tw-zuoying",
    name: "Zuoying Naval Base",
    hostCountryCode: "TW",
    region: "Indo-Pacific",
    location: "Kaohsiung",
    type: "naval",
    primaryServiceBranch: "Republic of China Navy",
    tenantCountryCodes: ["TW"],
    hostedUnits: ["ROCN Fleet Command"],
    hostedSystems: ["Kee Lung DDG", "Cheng Kung FFG", "Hai Lung SSK", "Hai Kun (sea trials)"],
    role: "Largest ROCN base; principal southern Taiwan fleet anchor.",
  },
  {
    slug: "tw-hsinchu",
    name: "Hsinchu Air Base",
    hostCountryCode: "TW",
    region: "Indo-Pacific",
    location: "Hsinchu",
    type: "air",
    primaryServiceBranch: "ROC Air Force",
    tenantCountryCodes: ["TW"],
    hostedUnits: ["499th Tactical Fighter Wing"],
    hostedSystems: ["Mirage 2000-5"],
    role: "Northern Taiwan air defence base intercepting PLA aircraft over the Strait.",
  },
  {
    slug: "tw-chiashan",
    name: "Chiashan Air Base",
    hostCountryCode: "TW",
    region: "Indo-Pacific",
    location: "Hualien",
    type: "air",
    primaryServiceBranch: "ROC Air Force",
    tenantCountryCodes: ["TW"],
    hostedUnits: ["401st Tactical Fighter Wing"],
    hostedSystems: ["F-16V Block 70", "Sky Bow III SAM"],
    role: "Hardened mountain shelter air base on Taiwan's east coast; survivability hub against PLA first strikes.",
  },
  {
    slug: "ph-edca-antonio-bautista",
    name: "Antonio Bautista Air Base (EDCA)",
    hostCountryCode: "PH",
    region: "Indo-Pacific",
    location: "Puerto Princesa, Palawan",
    type: "air",
    primaryServiceBranch: "Philippine Air Force",
    tenantCountryCodes: ["PH", "US"],
    hostedUnits: ["570th Composite Tactical Wing"],
    hostedSystems: [],
    role: "EDCA site closest to the South China Sea; rotational US presence supporting West Philippine Sea operations.",
  },
  {
    slug: "ph-edca-basa",
    name: "Basa Air Base (EDCA)",
    hostCountryCode: "PH",
    region: "Indo-Pacific",
    location: "Floridablanca, Pampanga",
    type: "air",
    primaryServiceBranch: "Philippine Air Force",
    tenantCountryCodes: ["PH", "US"],
    hostedUnits: ["5th Fighter Wing"],
    hostedSystems: ["FA-50PH"],
    role: "Major EDCA fighter base supporting US rotational presence in northern Luzon.",
  },
  {
    slug: "au-tindal",
    name: "RAAF Base Tindal",
    hostCountryCode: "AU",
    region: "Oceania",
    location: "Katherine, Northern Territory",
    type: "air",
    primaryServiceBranch: "Royal Australian Air Force",
    tenantCountryCodes: ["AU", "US"],
    hostedUnits: ["No. 75 Squadron"],
    hostedSystems: ["F-35A Lightning II", "B-52H (rotational)"],
    role: "Northern Australian fighter and rotational bomber base; principal AUKUS deep-strike posture node.",
  },
  {
    slug: "au-darwin",
    name: "RAAF Base Darwin",
    hostCountryCode: "AU",
    region: "Oceania",
    location: "Darwin, Northern Territory",
    type: "joint",
    primaryServiceBranch: "Royal Australian Air Force",
    tenantCountryCodes: ["AU", "US"],
    hostedUnits: ["Marine Rotational Force - Darwin"],
    hostedSystems: [],
    role: "Hosts annual rotational US Marine Air-Ground Task Force; jumping-off base for SE Asia.",
  },
  {
    slug: "au-stirling",
    name: "HMAS Stirling",
    hostCountryCode: "AU",
    region: "Oceania",
    location: "Garden Island, Western Australia",
    type: "naval",
    primaryServiceBranch: "Royal Australian Navy",
    tenantCountryCodes: ["AU", "US", "GB"],
    hostedUnits: ["Fleet Base West"],
    hostedSystems: ["Collins-class SSK", "AUKUS rotational SSN forward presence"],
    role: "Future host of rotational US Virginia-class SSNs under AUKUS Pillar I.",
  },
  {
    slug: "au-pine-gap",
    name: "Joint Defence Facility Pine Gap",
    hostCountryCode: "AU",
    region: "Oceania",
    location: "Alice Springs, Northern Territory",
    type: "intel",
    primaryServiceBranch: "Australian Signals Directorate / NSA",
    tenantCountryCodes: ["AU", "US"],
    hostedUnits: ["Joint US-Australia SIGINT facility"],
    hostedSystems: [],
    role: "Critical Five Eyes SIGINT and overhead reconnaissance ground station.",
  },
  {
    slug: "sg-changi",
    name: "Changi Naval Base",
    hostCountryCode: "SG",
    region: "Indo-Pacific",
    location: "Changi, Singapore",
    type: "naval",
    primaryServiceBranch: "Republic of Singapore Navy",
    tenantCountryCodes: ["SG", "US"],
    hostedUnits: ["RSN 185 Squadron", "Logistics Group Western Pacific (US)"],
    hostedSystems: ["Independence-class LCS (US, rotational)", "Formidable-class FFG"],
    role: "Hosts forward-deployed US Navy LCS rotation through Singapore.",
  },
  {
    slug: "my-butterworth",
    name: "RMAF Butterworth",
    hostCountryCode: "MY",
    region: "Indo-Pacific",
    location: "Butterworth, Penang",
    type: "joint",
    primaryServiceBranch: "Royal Malaysian Air Force",
    tenantCountryCodes: ["MY", "AU"],
    hostedUnits: ["Integrated Area Defence System HQ", "RAAF 92 Wing detachment"],
    hostedSystems: ["RAAF AP-3C Orion (rotational)", "RMAF F/A-18D Hornet"],
    role: "FPDA Integrated Air Defence System headquarters; Australian rotational MPA presence.",
  },
  {
    slug: "vn-camranh",
    name: "Cam Ranh Bay Naval Base",
    hostCountryCode: "VN",
    region: "Indo-Pacific",
    location: "Cam Ranh, Khánh Hòa",
    type: "naval",
    primaryServiceBranch: "Vietnam People's Navy",
    tenantCountryCodes: ["VN"],
    hostedUnits: ["VPN Submarine Brigade 189"],
    hostedSystems: ["Kilo-class (Project 636) SSK", "Gepard 3.9 FFG"],
    role: "Premier Vietnamese naval base; rare deep-water harbor with international visit access for foreign navies.",
  },
  {
    slug: "in-karwar",
    name: "INS Kadamba (Karwar)",
    hostCountryCode: "IN",
    region: "Indo-Pacific",
    location: "Karwar, Karnataka",
    type: "naval",
    primaryServiceBranch: "Indian Navy",
    tenantCountryCodes: ["IN"],
    hostedUnits: ["Western Naval Command forward elements"],
    hostedSystems: ["INS Vikramaditya (R33)", "Kolkata-class DDG"],
    role: "Largest east-coast Indian Navy base; Project Seabird expansion will house carriers and SSNs.",
  },
  {
    slug: "in-andaman",
    name: "Andaman & Nicobar Tri-Service Command",
    hostCountryCode: "IN",
    region: "Indo-Pacific",
    location: "Port Blair",
    type: "joint",
    primaryServiceBranch: "Indian Armed Forces",
    tenantCountryCodes: ["IN"],
    hostedUnits: ["Andaman & Nicobar Command"],
    hostedSystems: ["Su-30MKI", "P-8I", "INS Karmuk corvette"],
    role: "Sole Indian tri-service operational command; commands the Malacca/Six Degree Channel approaches.",
  },
  {
    slug: "cn-yulin",
    name: "Yulin Naval Base",
    hostCountryCode: "CN",
    region: "Indo-Pacific",
    location: "Sanya, Hainan",
    type: "nuclear",
    primaryServiceBranch: "PLA Navy",
    tenantCountryCodes: ["CN"],
    hostedUnits: ["South Sea Fleet submarine bastion"],
    hostedSystems: ["Type 094 Jin-class SSBN", "Type 093 Shang-class SSN", "Type 075 LHD"],
    role: "PLA Navy SSBN bastion in the South China Sea; underground submarine pens.",
  },
  {
    slug: "cn-qingdao",
    name: "Qingdao Naval Base",
    hostCountryCode: "CN",
    region: "Indo-Pacific",
    location: "Qingdao, Shandong",
    type: "naval",
    primaryServiceBranch: "PLA Navy",
    tenantCountryCodes: ["CN"],
    hostedUnits: ["North Sea Fleet"],
    hostedSystems: ["CV-16 Liaoning", "Type 055 Renhai DDG"],
    role: "Northern PLA Navy fleet headquarters; carrier homeport.",
  },
  {
    slug: "cn-djibouti-support",
    name: "PLA Support Base in Djibouti",
    hostCountryCode: "DJ",
    region: "Africa",
    location: "Doraleh",
    type: "logistics",
    primaryServiceBranch: "PLA",
    tenantCountryCodes: ["CN"],
    hostedUnits: ["PLA Support Base detachment"],
    hostedSystems: [],
    role: "PLA's first overseas base; enables sustained Indian Ocean and Horn of Africa operations.",
  },
  {
    slug: "cn-woody-island",
    name: "Yongxing Dao (Woody Island)",
    hostCountryCode: "CN",
    region: "Indo-Pacific",
    location: "Paracel Islands",
    type: "joint",
    primaryServiceBranch: "PLA Navy / PLA Air Force",
    tenantCountryCodes: ["CN"],
    hostedUnits: ["PLA garrison detachment"],
    hostedSystems: ["YJ-62 anti-ship cruise missile", "HQ-9 SAM", "J-11B / Su-30 (rotational)"],
    role: "Largest militarized PRC outpost in the Paracels; airstrip and missile-defence node.",
  },
  {
    slug: "cn-fiery-cross",
    name: "Yongshu Reef (Fiery Cross Reef)",
    hostCountryCode: "CN",
    region: "Indo-Pacific",
    location: "Spratly Islands",
    type: "joint",
    primaryServiceBranch: "PLA Navy / PLA Air Force",
    tenantCountryCodes: ["CN"],
    hostedUnits: ["PLA reef garrison"],
    hostedSystems: ["YJ-12B anti-ship cruise missile", "HQ-9B SAM", "J-11 (rotational)"],
    role: "Largest militarized PRC reef outpost in the Spratlys; supports PLA presence operations across the South China Sea.",
  },
  {
    slug: "ru-severomorsk",
    name: "Severomorsk Naval Base",
    hostCountryCode: "RU",
    region: "Arctic",
    location: "Murmansk Oblast",
    type: "naval",
    primaryServiceBranch: "Russian Navy",
    tenantCountryCodes: ["RU"],
    hostedUnits: ["Northern Fleet HQ"],
    hostedSystems: ["Borei SSBN", "Yasen SSGN", "Admiral Kuznetsov"],
    role: "Russia's principal SSBN bastion and Northern Fleet headquarters.",
  },
  {
    slug: "ru-vladivostok",
    name: "Vladivostok Naval Base",
    hostCountryCode: "RU",
    region: "Indo-Pacific",
    location: "Primorsky Krai",
    type: "naval",
    primaryServiceBranch: "Russian Navy",
    tenantCountryCodes: ["RU"],
    hostedUnits: ["Pacific Fleet HQ"],
    hostedSystems: ["Borei SSBN (Pacific)", "Slava-class CG", "Akula-class SSN"],
    role: "Russian Pacific Fleet HQ; SLBM patrols against US Pacific approaches.",
  },
  {
    slug: "ru-kaliningrad",
    name: "Baltiysk Naval Base / Kaliningrad",
    hostCountryCode: "RU",
    region: "Europe",
    location: "Kaliningrad Oblast",
    type: "joint",
    primaryServiceBranch: "Russian Armed Forces",
    tenantCountryCodes: ["RU"],
    hostedUnits: ["Baltic Fleet", "11th Army Corps"],
    hostedSystems: ["Iskander-M SRBM (nuclear-capable)", "S-400 Triumf", "Bastion-P coastal defence"],
    role: "Russian exclusive A2/AD bastion in the Baltic; threatens NATO eastern flank and Suwałki Gap.",
  },
  {
    slug: "ru-khmeimim",
    name: "Khmeimim Air Base",
    hostCountryCode: "SY",
    region: "Middle East",
    location: "Latakia",
    type: "air",
    primaryServiceBranch: "Russian Aerospace Forces",
    tenantCountryCodes: ["RU"],
    hostedUnits: ["Russian Group of Forces in Syria"],
    hostedSystems: ["Su-35S", "Su-34", "S-400 Triumf"],
    role: "Russia's principal Mediterranean air base; lever in Levant and African operations.",
  },
  {
    slug: "kp-yongbyon",
    name: "Yongbyon Nuclear Scientific Research Center",
    hostCountryCode: "KP",
    region: "Indo-Pacific",
    location: "Pyongan",
    type: "nuclear",
    primaryServiceBranch: "DPRK government",
    tenantCountryCodes: ["KP"],
    hostedUnits: ["DPRK Atomic Energy Bureau"],
    hostedSystems: ["5MWe gas-graphite reactor", "uranium enrichment facility"],
    role: "Core node of the DPRK plutonium and uranium programs; long-standing IAEA non-compliance subject.",
  },
];
