import type { MilitaryBase } from "./types";

export const basesD: MilitaryBase[] = [
  {
    slug: "il-nevatim",
    name: "Nevatim Airbase",
    hostCountryCode: "IL",
    region: "Middle East",
    location: "Negev",
    type: "air",
    primaryServiceBranch: "Israeli Air Force",
    tenantCountryCodes: ["IL"],
    hostedUnits: ["140 Squadron 'Golden Eagle'", "116 'Lions of the South'"],
    hostedSystems: ["F-35I Adir", "G550 Eitam AEW", "C-130J Super Hercules"],
    role: "Principal IAF F-35I fleet base; long-range strike platform.",
  },
  {
    slug: "il-tel-nof",
    name: "Tel Nof Airbase",
    hostCountryCode: "IL",
    region: "Middle East",
    location: "Rehovot",
    type: "air",
    primaryServiceBranch: "Israeli Air Force",
    tenantCountryCodes: ["IL"],
    hostedUnits: ["F-15 squadrons", "Sayeret Shaldag"],
    hostedSystems: ["F-15I Ra'am", "AH-64D Apache Longbow"],
    role: "Strategic strike base for long-range operations and SOF aviation.",
  },
  {
    slug: "il-palmachim",
    name: "Palmachim Airbase",
    hostCountryCode: "IL",
    region: "Middle East",
    location: "Mediterranean coast",
    type: "missile_defense",
    primaryServiceBranch: "Israeli Air Force",
    tenantCountryCodes: ["IL"],
    hostedUnits: ["Israeli space and missile test range"],
    hostedSystems: ["Arrow 3", "Shavit space launch vehicle"],
    role: "Missile and space launch test range; Arrow ballistic-missile-defence engagement node.",
  },
  {
    slug: "il-haifa",
    name: "Haifa Naval Base",
    hostCountryCode: "IL",
    region: "Middle East",
    location: "Haifa",
    type: "naval",
    primaryServiceBranch: "Israeli Navy",
    tenantCountryCodes: ["IL"],
    hostedUnits: ["Israeli Navy Northern Command"],
    hostedSystems: ["Sa'ar 6 corvette", "Dolphin-class SSK"],
    role: "Principal Israeli naval base; protects gas fields in the Eastern Mediterranean.",
  },
  {
    slug: "sa-prince-sultan",
    name: "Prince Sultan Air Base",
    hostCountryCode: "SA",
    region: "Middle East",
    location: "Al Kharj",
    type: "air",
    primaryServiceBranch: "Royal Saudi Air Force",
    tenantCountryCodes: ["SA", "US"],
    hostedUnits: ["378th Air Expeditionary Wing (US, rotational)"],
    hostedSystems: ["F-15SA Eagle", "F-22 Raptor (rotational)"],
    role: "Major Gulf air base hosting rotational US fifth-gen fighters.",
  },
  {
    slug: "sa-king-abdulaziz",
    name: "King Abdulaziz Air Base",
    hostCountryCode: "SA",
    region: "Middle East",
    location: "Dhahran",
    type: "air",
    primaryServiceBranch: "Royal Saudi Air Force",
    tenantCountryCodes: ["SA"],
    hostedUnits: ["RSAF 1 Wing"],
    hostedSystems: ["F-15C/D Eagle", "Tornado IDS"],
    role: "Eastern Province air base covering oil infrastructure.",
  },
  {
    slug: "ae-jebel-ali",
    name: "Jebel Ali Port",
    hostCountryCode: "AE",
    region: "Middle East",
    location: "Dubai",
    type: "naval",
    primaryServiceBranch: "UAE Navy / US Navy",
    tenantCountryCodes: ["AE", "US"],
    hostedUnits: ["US 5th Fleet logistics hub"],
    hostedSystems: ["US carrier port-of-call"],
    role: "Largest non-US deepwater port that can host a US Nimitz/Ford-class carrier; vital Gulf logistics node.",
  },
  {
    slug: "bh-naval-support-activity",
    name: "Naval Support Activity Bahrain",
    hostCountryCode: "BH",
    region: "Middle East",
    location: "Manama",
    type: "naval",
    primaryServiceBranch: "US Navy",
    tenantCountryCodes: ["US", "BH"],
    hostedUnits: ["US 5th Fleet HQ", "Combined Maritime Forces"],
    hostedSystems: ["Patrol Coastal ships", "Avenger-class MCM"],
    role: "US 5th Fleet headquarters and CMF coalition HQ.",
  },
  {
    slug: "kw-camp-arifjan",
    name: "Camp Arifjan",
    hostCountryCode: "KW",
    region: "Middle East",
    location: "Al Ahmadi Governorate",
    type: "army",
    primaryServiceBranch: "US Army",
    tenantCountryCodes: ["US", "KW"],
    hostedUnits: ["US Army Central Command (forward)"],
    hostedSystems: ["Patriot PAC-3 battery"],
    role: "ARCENT logistics hub for the Gulf and Iraq-Syria operations.",
  },
  {
    slug: "iq-al-asad",
    name: "Al Asad Air Base",
    hostCountryCode: "IQ",
    region: "Middle East",
    location: "Al Anbar",
    type: "joint",
    primaryServiceBranch: "Iraqi Armed Forces",
    tenantCountryCodes: ["IQ", "US"],
    hostedUnits: ["Operation Inherent Resolve elements"],
    hostedSystems: ["MQ-9 Reaper (rotational)", "C-RAM"],
    role: "Western Iraq joint base; under periodic Iranian-aligned militia rocket and missile attack since 2020.",
  },
  {
    slug: "ir-bandar-abbas",
    name: "Bandar Abbas Naval Base",
    hostCountryCode: "IR",
    region: "Middle East",
    location: "Hormozgan",
    type: "naval",
    primaryServiceBranch: "IRGC Navy / Islamic Republic of Iran Navy",
    tenantCountryCodes: ["IR"],
    hostedUnits: ["IRIN HQ"],
    hostedSystems: [
      "Moudge-class FFG",
      "Ghadir / Fateh midget subs",
      "Bavar-373 SAM",
    ],
    role: "Iran's principal Persian Gulf naval base; controls northern Strait of Hormuz approaches.",
  },
  {
    slug: "ir-chabahar",
    name: "Chabahar Naval Base",
    hostCountryCode: "IR",
    region: "Middle East",
    location: "Sistan and Baluchestan",
    type: "naval",
    primaryServiceBranch: "Islamic Republic of Iran Navy",
    tenantCountryCodes: ["IR"],
    hostedUnits: ["IRIN forward elements"],
    hostedSystems: [],
    role: "Iran's principal Indian Ocean port outside the Hormuz chokepoint.",
  },
  {
    slug: "ir-natanz",
    name: "Natanz Fuel Enrichment Plant",
    hostCountryCode: "IR",
    region: "Middle East",
    location: "Natanz, Isfahan",
    type: "nuclear",
    primaryServiceBranch: "Atomic Energy Organization of Iran",
    tenantCountryCodes: ["IR"],
    hostedUnits: ["Iranian uranium enrichment program"],
    hostedSystems: ["IR-2m / IR-6 centrifuges"],
    role: "Primary declared Iranian uranium enrichment site; long-running IAEA verification subject and sabotage target.",
  },
  {
    slug: "ir-fordow",
    name: "Fordow Fuel Enrichment Plant",
    hostCountryCode: "IR",
    region: "Middle East",
    location: "Qom",
    type: "nuclear",
    primaryServiceBranch: "Atomic Energy Organization of Iran",
    tenantCountryCodes: ["IR"],
    hostedUnits: ["Iranian uranium enrichment program"],
    hostedSystems: ["IR-6 centrifuge cascades"],
    role: "Hardened underground enrichment site; centerpiece of Iran's threshold capability.",
  },
  {
    slug: "tr-kabul-equiv-konya-ed",
    name: "Aksaz Naval Base",
    hostCountryCode: "TR",
    region: "Europe",
    location: "Marmaris",
    type: "naval",
    primaryServiceBranch: "Turkish Navy",
    tenantCountryCodes: ["TR"],
    hostedUnits: ["Turkish Navy Aegean Sea Command"],
    hostedSystems: ["Reis-class (Type 214TN) SSK", "İstanbul-class FFG"],
    role: "Major Turkish naval base on the Aegean; submarine homeport.",
  },
  {
    slug: "tr-golcuk",
    name: "Gölcük Naval Base",
    hostCountryCode: "TR",
    region: "Europe",
    location: "Kocaeli",
    type: "naval",
    primaryServiceBranch: "Turkish Navy",
    tenantCountryCodes: ["TR"],
    hostedUnits: ["Turkish Naval Forces HQ"],
    hostedSystems: [
      "TCG Anadolu (L-400)",
      "Ada-class corvette",
      "Gür-class SSK",
    ],
    role: "Turkish Navy headquarters and shipyard on the Sea of Marmara.",
  },
  {
    slug: "eg-berenice",
    name: "Berenice Naval Base",
    hostCountryCode: "EG",
    region: "Africa",
    location: "Red Sea coast",
    type: "naval",
    primaryServiceBranch: "Egyptian Navy",
    tenantCountryCodes: ["EG"],
    hostedUnits: ["Egyptian Red Sea Fleet"],
    hostedSystems: ["Mistral-class LHD (Anwar el Sadat)", "FREMM Tahya Misr"],
    role: "Modern Red Sea base anchoring Egyptian Suez and southern Red Sea security.",
  },
  {
    slug: "eg-mohammed-naguib",
    name: "Mohammed Naguib Military Base",
    hostCountryCode: "EG",
    region: "Africa",
    location: "Marsa Matruh",
    type: "joint",
    primaryServiceBranch: "Egyptian Armed Forces",
    tenantCountryCodes: ["EG"],
    hostedUnits: ["Egyptian Western Military District"],
    hostedSystems: ["M1A1 Abrams", "Rafale", "Ka-52 Alligator"],
    role: "Largest Egyptian military base; western desert posture toward Libya.",
  },
  {
    slug: "ke-manda-bay",
    name: "Camp Simba (Manda Bay)",
    hostCountryCode: "KE",
    region: "Africa",
    location: "Lamu",
    type: "joint",
    primaryServiceBranch: "Kenya Defence Forces / US",
    tenantCountryCodes: ["KE", "US"],
    hostedUnits: ["AFRICOM rotational ISR detachment"],
    hostedSystems: ["MQ-9 Reaper (historic)"],
    role: "Coastal Kenya base for ISR and counter-Al-Shabaab operations.",
  },
  {
    slug: "ne-air-base-201",
    name: "Air Base 201 (Niger)",
    hostCountryCode: "NE",
    region: "Africa",
    location: "Agadez",
    type: "air",
    primaryServiceBranch: "US Air Force",
    tenantCountryCodes: ["NE"],
    hostedUnits: ["(Drawdown 2024)"],
    hostedSystems: ["MQ-9 Reaper"],
    role: "Sahel ISR hub; US withdrew under 2024 junta directive.",
  },
  {
    slug: "ml-historical-french",
    name: "FFDj-aligned Sahel posture (closed)",
    hostCountryCode: "ML",
    region: "Africa",
    location: "Mali",
    type: "joint",
    primaryServiceBranch: "Forces armées maliennes",
    tenantCountryCodes: ["ML"],
    hostedUnits: ["French Operation Barkhane (closed 2022)"],
    hostedSystems: [],
    role: "Former French counter-terror Sahel hub closed amid junta-Wagner alignment.",
  },
  {
    slug: "br-itaguai",
    name: "Itaguaí Naval Base",
    hostCountryCode: "BR",
    region: "South America",
    location: "Itaguaí, Rio de Janeiro",
    type: "nuclear",
    primaryServiceBranch: "Brazilian Navy",
    tenantCountryCodes: ["BR"],
    hostedUnits: ["Brazilian SSN Program (PROSUB)"],
    hostedSystems: [
      "Riachuelo-class SSK",
      "SN-Álvaro Alberto SSN (under construction)",
    ],
    role: "Brazilian SSN program shipyard and nuclear-program nucleus.",
  },
  {
    slug: "br-rio",
    name: "Naval Base of Rio de Janeiro",
    hostCountryCode: "BR",
    region: "South America",
    location: "Rio de Janeiro",
    type: "naval",
    primaryServiceBranch: "Brazilian Navy",
    tenantCountryCodes: ["BR"],
    hostedUnits: ["Brazilian Navy Squadron"],
    hostedSystems: ["NAM Atlântico (A140) helicopter carrier"],
    role: "Largest Brazilian naval base; flagship homeport.",
  },
  {
    slug: "ar-puerto-belgrano",
    name: "Puerto Belgrano Naval Base",
    hostCountryCode: "AR",
    region: "South America",
    location: "Punta Alta, Buenos Aires",
    type: "naval",
    primaryServiceBranch: "Argentine Navy",
    tenantCountryCodes: ["AR"],
    hostedUnits: ["Argentine Naval Aviation"],
    hostedSystems: ["MEKO 360H2 destroyer"],
    role: "Largest Argentine naval base; principal Atlantic fleet homeport.",
  },
  {
    slug: "mx-mar-del-plata",
    name: "Naval Base Mar del Plata (AR)",
    hostCountryCode: "AR",
    region: "South America",
    location: "Mar del Plata",
    type: "naval",
    primaryServiceBranch: "Argentine Navy",
    tenantCountryCodes: ["AR"],
    hostedUnits: ["Argentine Submarine Force"],
    hostedSystems: ["TR-1700-class SSK"],
    role: "Argentine submarine base; site of ARA San Juan 2017 loss.",
  },
  {
    slug: "ca-cfb-esquimalt",
    name: "CFB Esquimalt",
    hostCountryCode: "CA",
    region: "North America",
    location: "Vancouver Island, British Columbia",
    type: "naval",
    primaryServiceBranch: "Royal Canadian Navy",
    tenantCountryCodes: ["CA"],
    hostedUnits: ["Maritime Forces Pacific"],
    hostedSystems: ["Halifax-class FFG", "Victoria-class SSK"],
    role: "Pacific fleet headquarters of the Royal Canadian Navy.",
  },
  {
    slug: "ca-cfb-halifax",
    name: "CFB Halifax",
    hostCountryCode: "CA",
    region: "North America",
    location: "Halifax, Nova Scotia",
    type: "naval",
    primaryServiceBranch: "Royal Canadian Navy",
    tenantCountryCodes: ["CA"],
    hostedUnits: ["Maritime Forces Atlantic"],
    hostedSystems: ["Halifax-class FFG", "Harry DeWolf-class AOPV"],
    role: "Atlantic fleet headquarters; NATO Standing Maritime Group support node.",
  },
  {
    slug: "ca-cfs-alert",
    name: "CFS Alert",
    hostCountryCode: "CA",
    region: "Arctic",
    location: "Ellesmere Island, Nunavut",
    type: "intel",
    primaryServiceBranch: "Canadian Armed Forces",
    tenantCountryCodes: ["CA"],
    hostedUnits: ["CAF SIGINT detachment"],
    hostedSystems: [],
    role: "Northernmost permanently-inhabited military installation; Five Eyes Arctic SIGINT collection.",
  },
  {
    slug: "us-fairbanks-eielson",
    name: "Eielson Air Force Base",
    hostCountryCode: "US",
    region: "Arctic",
    location: "Fairbanks, Alaska",
    type: "air",
    primaryServiceBranch: "US Air Force",
    tenantCountryCodes: ["US"],
    hostedUnits: ["354th Fighter Wing"],
    hostedSystems: ["F-35A Lightning II"],
    role: "Northern Pacific F-35A wing; QRA against Russian Far East.",
  },
  {
    slug: "us-jber",
    name: "Joint Base Elmendorf-Richardson",
    hostCountryCode: "US",
    region: "Arctic",
    location: "Anchorage, Alaska",
    type: "joint",
    primaryServiceBranch: "US Air Force / US Army",
    tenantCountryCodes: ["US"],
    hostedUnits: ["3rd Wing", "11th Airborne Division"],
    hostedSystems: ["F-22A Raptor", "C-17A Globemaster III", "E-3 Sentry"],
    role: "Indo-Pacific and Arctic air defense / power projection hub.",
  },
];
