import type { StrategicChokepoint } from "./types";

export const CHOKEPOINTS: StrategicChokepoint[] = [
  {
    slug: "strait-of-hormuz",
    name: "Strait of Hormuz",
    region: "Middle East",
    type: "strait",
    widthKm: 39,
    annualTraffic: "~21M barrels/day of oil (~30% of world seaborne oil)",
    bordersCountryCodes: ["IR", "OM", "AE"],
    controllingPowers: ["IR", "US (5th Fleet)", "OM"],
    alternativeRoutes: [
      "Habshan-Fujairah pipeline (UAE, ~1.5M bpd)",
      "East-West / Petroline (Saudi Arabia, ~5M bpd)",
    ],
    significance:
      "World's most strategically important oil chokepoint. Iran has repeatedly threatened closure during regional crises. US 5th Fleet HQ (Bahrain) and CMF coalition forces maintain freedom-of-navigation presence.",
    historicalIncidents: [
      "1980-88 Tanker War (Iran-Iraq)",
      "Operation Earnest Will 1987-88 (US reflagging)",
      "2019 Gulf of Oman tanker attacks",
      "2024 Houthi/IRGC harassment incidents",
    ],
  },
  {
    slug: "bab-el-mandeb",
    name: "Bab-el-Mandeb",
    region: "Middle East / Africa",
    type: "strait",
    widthKm: 29,
    annualTraffic:
      "~9-10% of seaborne oil and ~12% of world trade transits via Suez/Bab el-Mandeb",
    bordersCountryCodes: ["YE", "DJ", "ER"],
    controllingPowers: [
      "US (CTF-153)",
      "FR",
      "CN (Djibouti)",
      "Houthi forces (north shore)",
    ],
    alternativeRoutes: ["Cape of Good Hope (adds ~10-14 days transit)"],
    significance:
      "Choke between Red Sea and Gulf of Aden; entrance to the Suez Canal route. Houthi anti-ship missile and UAV campaign since late 2023 has materially diverted global shipping to the Cape route.",
    historicalIncidents: [
      "Houthi anti-ship campaign 2023-present (Operation Prosperity Guardian)",
      "MSC Aries seizure by IRGC 2024",
    ],
  },
  {
    slug: "suez-canal",
    name: "Suez Canal",
    region: "Middle East",
    type: "canal",
    widthKm: 0.205,
    annualTraffic: "~12% of world trade; ~8% of seaborne LNG",
    bordersCountryCodes: ["EG"],
    controllingPowers: ["EG"],
    alternativeRoutes: ["Cape of Good Hope (adds ~10-14 days transit)"],
    significance:
      "Egyptian-controlled artificial waterway connecting Mediterranean and Red Sea. Critical for European-Asian trade flows. Vulnerable to single-vessel grounding (Ever Given 2021).",
    historicalIncidents: [
      "1956 Suez Crisis (UK/FR/IL invasion, US-USSR pressure)",
      "1967-75 closure following Six-Day War",
      "2021 Ever Given grounding (6-day blockage)",
    ],
  },
  {
    slug: "strait-of-malacca",
    name: "Strait of Malacca",
    region: "Indo-Pacific",
    type: "strait",
    widthKm: 2.8,
    annualTraffic: "~25% of world's seaborne trade; ~15M barrels/day oil",
    bordersCountryCodes: ["MY", "ID", "SG"],
    controllingPowers: ["SG", "MY", "ID", "US (FONOPS)"],
    alternativeRoutes: [
      "Sunda Strait (Indonesia)",
      "Lombok Strait (Indonesia)",
      "Northern Sea Route (limited, seasonal)",
    ],
    significance:
      "Principal SLOC linking Indian Ocean and South China Sea. Heavy reliance by China for oil imports drives the so-called 'Malacca Dilemma' and motivates BRI alternative pathways.",
    historicalIncidents: [
      "Endemic piracy reduced significantly post-2005 by littoral states",
    ],
  },
  {
    slug: "lombok-strait",
    name: "Lombok Strait",
    region: "Indo-Pacific",
    type: "strait",
    widthKm: 18,
    bordersCountryCodes: ["ID"],
    controllingPowers: ["ID"],
    alternativeRoutes: ["Sunda Strait", "Strait of Malacca"],
    significance:
      "Deeper alternative to Malacca; preferred for VLCCs and submerged submarine transits. Indonesian Archipelagic Sea Lane I.",
  },
  {
    slug: "sunda-strait",
    name: "Sunda Strait",
    region: "Indo-Pacific",
    type: "strait",
    widthKm: 24,
    bordersCountryCodes: ["ID"],
    controllingPowers: ["ID"],
    alternativeRoutes: ["Lombok Strait", "Strait of Malacca"],
    significance:
      "Indonesian Archipelagic Sea Lane II; alternative to Malacca for north-south Indian Ocean transits.",
  },
  {
    slug: "taiwan-strait",
    name: "Taiwan Strait",
    region: "Indo-Pacific",
    type: "strait",
    widthKm: 130,
    bordersCountryCodes: ["TW", "CN"],
    controllingPowers: ["TW", "CN", "US (FONOPS)"],
    alternativeRoutes: ["Eastward Pacific routes around Taiwan"],
    significance:
      "Separates Taiwan from mainland China; principal flashpoint for cross-Strait crises. Critical SLOC for Japanese, Korean, and Chinese seaborne energy and trade. PLA exercises and gray-zone operations have intensified since 2022.",
    historicalIncidents: [
      "Taiwan Strait Crises 1954-55, 1958, 1995-96",
      "2022 Pelosi visit response (PLA missile overflight)",
      "Joint Sword 2024A/2024B exercises",
    ],
  },
  {
    slug: "luzon-strait",
    name: "Luzon Strait / Bashi Channel",
    region: "Indo-Pacific",
    type: "strait",
    widthKm: 250,
    bordersCountryCodes: ["TW", "PH"],
    controllingPowers: ["TW", "PH", "US (with PH under MDT)"],
    alternativeRoutes: ["Miyako Strait (north of Taiwan)"],
    significance:
      "Principal egress point for PLA Navy from East China Sea / South China Sea into the deep Pacific. PLA submarine transits routinely monitored by Taiwan and Philippines.",
  },
  {
    slug: "miyako-strait",
    name: "Miyako Strait",
    region: "Indo-Pacific",
    type: "strait",
    widthKm: 250,
    bordersCountryCodes: ["JP"],
    controllingPowers: ["JP"],
    alternativeRoutes: ["Luzon Strait", "Tsushima Strait"],
    significance:
      "Gap in the First Island Chain between Okinawa and Miyako; primary PLA Navy and Air Force route to the broader Pacific. Heavily monitored by Japan.",
  },
  {
    slug: "tsushima-strait",
    name: "Tsushima Strait / Korea Strait",
    region: "Indo-Pacific",
    type: "strait",
    widthKm: 200,
    bordersCountryCodes: ["JP", "KR"],
    controllingPowers: ["JP", "KR"],
    alternativeRoutes: ["Soya Strait (north of Hokkaido)"],
    significance:
      "Connects Sea of Japan to East China Sea; transit route for Russian Pacific Fleet to access wider Pacific.",
  },
  {
    slug: "bosphorus",
    name: "Bosphorus / Turkish Straits",
    region: "Europe",
    type: "strait",
    widthKm: 0.7,
    bordersCountryCodes: ["TR"],
    controllingPowers: ["TR (Montreux Convention 1936)"],
    alternativeRoutes: [],
    significance:
      "Sole maritime exit from Black Sea to Mediterranean. Türkiye regulates transit under the 1936 Montreux Convention, including warship tonnage limits and wartime closure. Closed to belligerent warships since February 2022.",
    historicalIncidents: [
      "Closed to RU/UA warships under Montreux 2022-present",
    ],
  },
  {
    slug: "dardanelles",
    name: "Dardanelles",
    region: "Europe",
    type: "strait",
    widthKm: 1.2,
    bordersCountryCodes: ["TR"],
    controllingPowers: ["TR (Montreux Convention)"],
    alternativeRoutes: [],
    significance:
      "Aegean-side passage of the Turkish Straits, paired with Bosphorus. Same Montreux regime applies.",
  },
  {
    slug: "strait-of-gibraltar",
    name: "Strait of Gibraltar",
    region: "Europe",
    type: "strait",
    widthKm: 13,
    bordersCountryCodes: ["ES", "MA", "GI"],
    controllingPowers: ["ES", "GB (Gibraltar)", "MA", "US/NATO"],
    alternativeRoutes: [],
    significance:
      "Sole transit between Atlantic and Mediterranean; primary route for US 6th Fleet, NATO carriers, and Russian Mediterranean access. Heavy submarine and surface ISR.",
  },
  {
    slug: "english-channel-dover",
    name: "Strait of Dover / English Channel",
    region: "Europe",
    type: "strait",
    widthKm: 33,
    bordersCountryCodes: ["GB", "FR"],
    controllingPowers: ["GB", "FR"],
    alternativeRoutes: ["North-around UK (Pentland Firth)"],
    significance:
      "Busiest international shipping lane in the world; entry to North Sea ports.",
  },
  {
    slug: "danish-straits",
    name: "Danish Straits (Skagerrak/Kattegat/Øresund)",
    region: "Europe",
    type: "strait",
    bordersCountryCodes: ["DK", "SE", "NO", "DE"],
    controllingPowers: ["DK", "SE", "NO"],
    alternativeRoutes: ["Kiel Canal (DE)"],
    significance:
      "Sole exit from Baltic Sea to North Atlantic; Russian Baltic Fleet must transit. With Sweden and Finland in NATO, the Baltic is effectively a NATO interior sea.",
  },
  {
    slug: "giuk-gap",
    name: "GIUK Gap",
    region: "Europe / Arctic",
    type: "gap",
    bordersCountryCodes: ["IS", "GB", "NO", "FO", "GL"],
    controllingPowers: ["US", "GB", "NO", "IS", "DK"],
    alternativeRoutes: ["Arctic Northern Sea Route"],
    significance:
      "Greenland-Iceland-UK gap; classical NATO ASW barrier against Russian Northern Fleet SSBN/SSGN sortie. Renewed importance with re-stood US 2nd Fleet and Iceland P-8A rotations.",
  },
  {
    slug: "panama-canal",
    name: "Panama Canal",
    region: "Americas",
    type: "canal",
    widthKm: 0.16,
    annualTraffic: "~6% of world seaborne trade",
    bordersCountryCodes: ["PA"],
    controllingPowers: ["PA"],
    alternativeRoutes: ["Strait of Magellan", "Cape Horn"],
    significance:
      "Connects Atlantic and Pacific oceans; major route for US East Coast - Asia and intra-Americas trade. Capacity affected by Lake Gatún drought conditions in 2023-2024.",
  },
  {
    slug: "bering-strait",
    name: "Bering Strait",
    region: "Arctic",
    type: "strait",
    widthKm: 82,
    bordersCountryCodes: ["US", "RU"],
    controllingPowers: ["US", "RU"],
    alternativeRoutes: [],
    significance:
      "Only natural maritime border between Russia and the United States; gateway to the Arctic from the Pacific. Strategic significance growing with Northern Sea Route navigability.",
  },
  {
    slug: "northern-sea-route",
    name: "Northern Sea Route",
    region: "Arctic",
    type: "passage",
    bordersCountryCodes: ["RU"],
    controllingPowers: ["RU"],
    alternativeRoutes: ["Suez route", "Cape of Good Hope"],
    significance:
      "Russian-claimed Arctic shipping route along Siberian coast; reduces Asia-Europe transit by ~10 days vs. Suez. Status under UNCLOS contested by US (transit passage) vs. Russia (internal waters).",
  },
  {
    slug: "mozambique-channel",
    name: "Mozambique Channel",
    region: "Africa / Indian Ocean",
    type: "passage",
    widthKm: 460,
    bordersCountryCodes: ["MZ", "MG", "KM", "FR (Mayotte)"],
    controllingPowers: ["FR (FAZSOI)", "MZ", "MG"],
    alternativeRoutes: ["Cape route around Madagascar"],
    significance:
      "Major LNG and bulk-carrier corridor between Eastern Africa and Asia; transits roughly 30% of global oil. Insurgency in Cabo Delgado has disrupted regional gas projects.",
    historicalIncidents: [
      "ISIS-Mozambique insurgency 2017-present",
      "Operation Daphne (FR/EU NAVFOR Atalanta)",
    ],
  },
  {
    slug: "strait-of-otranto",
    name: "Strait of Otranto",
    region: "Europe",
    type: "strait",
    widthKm: 72,
    bordersCountryCodes: ["IT", "AL"],
    controllingPowers: ["IT", "AL", "NATO"],
    alternativeRoutes: [],
    significance:
      "Connects Adriatic Sea to the Ionian and Mediterranean. Italian Operation Constant Vigilance and EU NAVFOR Med operations.",
  },
  {
    slug: "torres-strait",
    name: "Torres Strait",
    region: "Indo-Pacific",
    type: "strait",
    widthKm: 150,
    bordersCountryCodes: ["AU", "PG"],
    controllingPowers: ["AU", "PG"],
    alternativeRoutes: ["South of Australia route"],
    significance:
      "Connects Coral Sea (Pacific) to Arafura Sea (Indian Ocean approaches). Strategic alternative if Indonesian archipelagic routes are denied.",
  },
  {
    slug: "cook-strait",
    name: "Cook Strait",
    region: "Oceania",
    type: "strait",
    widthKm: 22,
    bordersCountryCodes: ["NZ"],
    controllingPowers: ["NZ"],
    alternativeRoutes: ["Around South Island"],
    significance:
      "Separates New Zealand's North and South Islands; chokepoint for trans-Tasman commerce.",
  },
  {
    slug: "skagerrak",
    name: "Skagerrak",
    region: "Europe",
    type: "strait",
    widthKm: 130,
    bordersCountryCodes: ["NO", "DK", "SE"],
    controllingPowers: ["NO", "DK", "SE"],
    alternativeRoutes: ["North-around UK / Pentland Firth"],
    significance:
      "Northern part of Danish Straits system; with Sweden and Finland in NATO, the Baltic exit is fully NATO-controlled.",
  },
  {
    slug: "strait-of-tiran",
    name: "Strait of Tiran",
    region: "Middle East",
    type: "strait",
    widthKm: 13,
    bordersCountryCodes: ["EG", "SA", "IL", "JO"],
    controllingPowers: ["EG", "SA", "IL"],
    alternativeRoutes: [],
    significance:
      "Sole maritime access to Israeli port of Eilat and Jordanian port of Aqaba; closure historically casus belli (1967 Six-Day War).",
    historicalIncidents: [
      "1967 Egyptian closure triggered Six-Day War",
      "Houthi disruption since 2023 affecting Red Sea approach",
    ],
  },
];
