import type { CountryProfile } from "./types";

export const countriesC: CountryProfile[] = [
  {
    code: "IR",
    name: "Iran",
    region: "Middle East",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 10,
    activeMilitaryPersonnel: 610000,
    doctrine:
      "Asymmetric deterrence via missile and drone forces, forward defence through proxy network ('Axis of Resistance'), naval area denial in the Persian Gulf, and threshold nuclear capability.",
    aircraft: [
      "F-14A Tomcat (overhauled)",
      "MiG-29A",
      "F-4E Phantom II",
      "F-5E/F Tiger II / Saeqeh / Kowsar",
      "Su-24MK Fencer",
      "Su-35S (procurement from Russia)",
      "Shahed-129 / -136 / -191 UCAVs",
    ],
    missiles: [
      "Shahab-3 / Ghadr / Emad MRBM",
      "Khorramshahr / Khaybar IRBM",
      "Kheibar Shekan MRBM",
      "Fattah hypersonic MRBM",
      "Soumar / Hoveyzeh cruise missile",
      "Bavar-373 long-range SAM",
      "Khordad-15 SAM",
      "Quds-1 / Paveh cruise missiles",
    ],
    naval: [
      "Moudge-class (Jamaran) frigate",
      "Bayandor / Alvand-class corvette",
      "Tareq / Fateh / Ghadir-class SSK / midget subs",
      "Shahid Bagheri (drone carrier, ex-container ship)",
      "Boghammer-style fast attack craft (IRGCN)",
    ],
    groundForces: [
      "Karrar MBT",
      "Zulfiqar MBT",
      "T-72S MBT",
      "Boragh / Cobra IFV",
      "IRGC Quds Force",
      "IRGC Aerospace Force (missile + drone)",
    ],
    bases: [
      "Bandar Abbas Naval Base (HQ)",
      "Chabahar Naval Base",
      "Konarak Naval Base",
      "Hamadan Air Base",
      "Bushehr (nuclear power plant adjacent)",
      "Fordow / Natanz enrichment facilities",
      "Imam Ali Base, Syria (IRGC)",
    ],
    alliances: [
      "Axis of Resistance (Hezbollah, Houthis, Iraqi PMUs)",
      "SCO (full member 2023)",
      "Russia-Iran defense cooperation",
      "BRICS+",
    ],
    notableCapabilities: [
      "Largest ballistic missile arsenal in the Middle East",
      "Threshold nuclear status (>60% enrichment)",
      "Drone exports including Shahed-136 to Russia",
      "Maritime swarm tactics in Strait of Hormuz",
    ],
  },
  {
    code: "KP",
    name: "North Korea",
    region: "East Asia",
    nuclearStatus: "declared",
    militaryBudgetUsdBillions: 4,
    activeMilitaryPersonnel: 1280000,
    doctrine:
      "Byungjin (parallel nuclear and economic development), preemptive nuclear use authorized by 2022 nuclear law, asymmetric provocations, and forward-deployed long-range artillery against Seoul.",
    aircraft: [
      "MiG-29 Fulcrum",
      "MiG-23 Flogger",
      "Su-25 Frogfoot",
      "MiG-21 Fishbed",
      "An-2 special operations infiltration",
      "H-5 (Il-28) light bomber",
    ],
    missiles: [
      "KN-23 / KN-24 / KN-25 SRBMs",
      "Hwasong-12 IRBM",
      "Hwasong-15 / -17 / -18 ICBM (solid-fuel Hwasong-18)",
      "Pukguksong-3 / -4 / -5 SLBM",
      "Hwasal-1 / -2 cruise missile",
      "Pyongyang-Pelinmun ASAT (claimed)",
    ],
    naval: [
      "Romeo-class SSK (modernized 8.24 Yongung)",
      "Sang-O / Yono midget submarines",
      "Najin / Soho-class frigate",
      "Nampo-class missile boat",
      "Numerous infiltration mini-subs",
    ],
    groundForces: [
      "Pokpung-ho MBT",
      "Chonma-ho MBT",
      "T-62 / T-55 (legacy)",
      "M-1989 170mm Koksan SP gun",
      "M-1985 240mm MRL",
      "Reconnaissance General Bureau (RGB)",
      "VIII Special Operations Corps",
    ],
    bases: [
      "Pyongyang Sunan International (military use)",
      "Sunchon Air Base",
      "Wonsan Naval Base",
      "Nampo Naval Shipyard",
      "Sinpo South Naval Shipyard (SLBM)",
      "Yongbyon Nuclear Complex",
      "Punggye-ri test site",
    ],
    alliances: [
      "China-North Korea Mutual Aid Treaty (1961)",
      "Russia-DPRK Strategic Partnership Treaty (2024)",
    ],
    notableCapabilities: [
      "Solid-fuel ICBM (Hwasong-18) capability",
      "Estimated 50+ nuclear warheads",
      "Massive forward-deployed long-range artillery (~14,000 systems)",
      "Cyber operations (Lazarus, Bureau 121)",
    ],
  },
  {
    code: "EG",
    name: "Egypt",
    region: "Middle East",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 5,
    activeMilitaryPersonnel: 450000,
    doctrine:
      "Suez Canal security, counter-terror in Sinai, Eastern Mediterranean and Red Sea balancing, and diversified procurement (US, France, Russia, Germany, Korea).",
    aircraft: [
      "F-16C/D Block 40",
      "Mirage 2000-5",
      "Rafale DM/EM",
      "MiG-29M/M2",
      "AH-64D Apache",
      "Ka-52 Alligator",
    ],
    missiles: [
      "AIM-120C AMRAAM",
      "MICA",
      "Storm Shadow / SCALP",
      "AGM-84 Harpoon",
      "Buk-M2E / Tor-M2E SAM",
      "S-300VM / Antey-2500 SAM",
    ],
    naval: [
      "Mistral-class LHD (Gamal Abdel Nasser, Anwar el Sadat)",
      "FREMM Tahya Misr",
      "Meko A-200 frigate",
      "Type 209/1400 SSK",
      "S43-class FAC(M)",
    ],
    groundForces: [
      "M1A1 Abrams MBT (locally assembled)",
      "T-90MS MBT",
      "M60A3 TTS",
      "M2A2 Bradley IFV",
      "K9 Thunder SP howitzer",
      "Unit 777 / Sa'ka Forces",
    ],
    bases: [
      "Cairo West Air Base",
      "Berenice Naval Base (Red Sea)",
      "Mohammed Naguib Military Base (largest in MENA)",
      "Ras Banas / Beranis (Red Sea)",
      "Alexandria Naval Base",
    ],
    alliances: [
      "Major Non-NATO Ally of US",
      "Arab League",
      "African Union",
    ],
    notableCapabilities: [
      "Two Mistral LHDs (only Arab state with operational helicopter carriers)",
      "Suez Canal sovereignty (12% world trade)",
      "Most diversified Arab arsenal (US/FR/RU/DE/KR)",
    ],
  },
  {
    code: "UA",
    name: "Ukraine",
    region: "Europe",
    nuclearStatus: "former",
    militaryBudgetUsdBillions: 65,
    activeMilitaryPersonnel: 900000,
    doctrine:
      "Active defence and counter-offensive against Russian invasion, integration with NATO standards (Bilateral Security Agreements), drone-led ISR-strike, and long-range disruption of Russian rear.",
    aircraft: [
      "F-16AM/BM Fighting Falcon (donated)",
      "MiG-29 (legacy)",
      "Su-27 (legacy)",
      "Su-25 Frogfoot",
      "Su-24 Fencer",
      "Bayraktar TB2 UCAV",
      "FPV/loitering drones at scale",
    ],
    missiles: [
      "Storm Shadow / SCALP",
      "ATACMS Block IA",
      "Neptune anti-ship cruise missile",
      "HIMARS / GMLRS / GLSDB",
      "Patriot PAC-3 / NASAMS / IRIS-T SLM",
      "AIM-120 AMRAAM (NASAMS)",
      "Long-range strike UAV (Liutyi, Bober)",
    ],
    naval: [
      "Most surface fleet lost or scuttled (Hetman Sahaidachny)",
      "Magura V5 / Sea Baby naval drones (game-changing)",
      "Centaur-class fast assault craft",
    ],
    groundForces: [
      "Leopard 1A5 / Leopard 2A4/A6",
      "M1A1 SA Abrams",
      "Challenger 2 (limited)",
      "T-64BV / T-72AMT / T-80U",
      "Bradley M2A2 ODS-SA",
      "Marder 1A3",
      "PzH 2000 / CAESAR / Krab / M109",
      "M270 / M142 HIMARS",
      "Kraken / Azov / 3rd Assault SOF",
    ],
    bases: [
      "Vasylkiv Air Base",
      "Starokostiantyniv Air Base (Storm Shadow operations)",
      "Odesa Naval Base",
      "Mykolaiv Shipyard",
      "Kyiv Patriot battery",
    ],
    alliances: [
      "Ramstein Format (UDCG)",
      "EU candidate state (since June 2022)",
      "Bilateral Security Agreements with G7+",
      "NATO Enhanced Opportunities Partner",
    ],
    notableCapabilities: [
      "Largest combat-experienced force in Europe",
      "Maritime drone campaign denying Black Sea Fleet operations",
      "FPV / loitering drone production at industrial scale",
      "Voluntarily denuclearized 1994 (Budapest Memorandum)",
    ],
  },
  {
    code: "TW",
    name: "Taiwan",
    region: "East Asia",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 19,
    activeMilitaryPersonnel: 169000,
    doctrine:
      "Overall Defense Concept: porcupine asymmetric defence, multi-domain deterrence-by-denial, coastal anti-ship missile saturation, and resilience under PLA blockade.",
    aircraft: [
      "F-16V Block 70/72 Viper",
      "F-CK-1 Ching-kuo IDF",
      "Mirage 2000-5",
      "P-3C Orion MPA",
      "AH-64E Apache Guardian",
      "AH-1W SuperCobra",
    ],
    missiles: [
      "Hsiung Feng II / III anti-ship missile",
      "Hsiung Feng IIE land-attack cruise missile",
      "Sky Bow III SAM",
      "Patriot PAC-3 MSE (Tien Kung)",
      "HIMARS (procurement)",
      "Harpoon Coastal Defense System (HCDS)",
      "Yun Feng cruise missile (developmental)",
    ],
    naval: [
      "Kee Lung-class destroyer (ex-Kidd)",
      "Cheng Kung-class FFG (ex-OHP)",
      "Kang Ding-class (La Fayette) FFG",
      "Tuo Chiang-class corvette (catamaran)",
      "Hai Lung-class SSK",
      "Hai Kun-class indigenous SSK (sea trials)",
    ],
    groundForces: [
      "M1A2T Abrams (incoming)",
      "CM-11 Brave Tiger MBT",
      "M60A3 TTS",
      "CM-32 Yunpao 8x8",
      "Thunderbolt-2000 MLRS",
      "Airborne Special Service Company / Navy ARP",
    ],
    bases: [
      "Taoyuan Air Base",
      "Hsinchu Air Base",
      "Chiashan Air Base (mountain shelter)",
      "Zuoying Naval Base",
      "Suao Naval Base",
      "Penghu (frontline islands)",
      "Kinmen / Matsu (frontline islands)",
    ],
    alliances: [
      "Taiwan Relations Act (US, 1979)",
      "Six Assurances (US, 1982)",
      "Taiwan Policy Act (US support packages)",
    ],
    notableCapabilities: [
      "Indigenous submarine program (Hai Kun) breaking 70-year drought",
      "Densest anti-ship missile saturation per coastline globally",
      "Hardened underground command and shelter network",
      "TSMC strategic semiconductor industry",
    ],
  },
  {
    code: "ID",
    name: "Indonesia",
    region: "Southeast Asia",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 9,
    activeMilitaryPersonnel: 395000,
    doctrine:
      "Total people's defence (Sishankamrata), maritime sovereignty across the archipelago, balancing major powers, and ASEAN centrality.",
    aircraft: [
      "F-16C/D Block 25/52ID",
      "Su-27SK / Su-30MK2",
      "Rafale (procurement)",
      "F-15EX (announced)",
      "T-50i Golden Eagle",
      "CN-235 MPA",
    ],
    missiles: [
      "AIM-9 Sidewinder",
      "AIM-120C AMRAAM",
      "Exocet MM40 Block 3",
      "C-705 / C-802 (Chinese)",
      "VL MICA SAM",
      "NASAMS-2 (procurement)",
    ],
    naval: [
      "Martadinata-class FFG (SIGMA 10514)",
      "Bung Tomo-class corvette",
      "Diponegoro-class SIGMA corvette",
      "Nagapasa-class (Type 209/1400) SSK",
      "Cakra-class (Type 209/1300) SSK",
    ],
    groundForces: [
      "Leopard 2A4 / 2RI MBT",
      "Marder 1A3 IFV",
      "Tarantula 6x6",
      "Kopassus / Marinir Taifib SOF",
    ],
    bases: [
      "Halim Perdanakusuma Air Base",
      "Iswahyudi Air Base",
      "Surabaya Naval Base (Eastern Fleet HQ)",
      "Natuna Besar (South China Sea outpost)",
      "Sorong (Papua, expanding)",
    ],
    alliances: [
      "ASEAN",
      "Non-Aligned Movement",
      "BRICS+ (joining)",
    ],
    notableCapabilities: [
      "Largest military in Southeast Asia",
      "Strategic location across SLOCs (Malacca, Sunda, Lombok straits)",
      "Mixed Russian/Western/Korean equipment portfolio",
    ],
  },
  {
    code: "VN",
    name: "Vietnam",
    region: "Southeast Asia",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 7,
    activeMilitaryPersonnel: 482000,
    doctrine:
      "People's war + four-no policy (no alliances, no foreign bases, no taking sides, no using force first), maritime denial in South China Sea, defence diplomacy with all majors.",
    aircraft: [
      "Su-30MK2V Flanker-G",
      "Su-22M4 (retiring)",
      "Yak-130 trainer",
      "CASA C-295 MPA",
    ],
    missiles: [
      "P-800 Oniks (Bastion-P coastal defense)",
      "Kh-35E Uran",
      "S-300PMU-1 SAM",
      "Spyder-MR/SR SAM",
      "BrahMos (procurement, first SE Asian buyer)",
    ],
    naval: [
      "Gepard 3.9-class FFG",
      "Molniya-class missile corvette",
      "Pohang-class corvette (donated)",
      "Kilo-class (Project 636) SSK (6 boats)",
    ],
    groundForces: [
      "T-90S/SK MBT",
      "T-62 / T-54/55 (legacy in numbers)",
      "BMP-2 IFV",
      "Special Forces Command (Đặc công)",
    ],
    bases: [
      "Cam Ranh Bay Naval Base",
      "Da Nang Air Base",
      "Phu Cat Air Base",
      "Hai Phong Naval Base",
      "Spratly Islands outposts (Vietnamese-held)",
    ],
    alliances: [
      "ASEAN",
      "Comprehensive Strategic Partnerships (US, RU, CN, IN, JP, KR, AU)",
    ],
    notableCapabilities: [
      "Modern Kilo SSK fleet (largest in SE Asia)",
      "Bastion-P coastal defence covering Spratlys",
      "Long combat experience and discipline",
      "Strategic non-alignment ('bamboo diplomacy')",
    ],
  },
  {
    code: "TH",
    name: "Thailand",
    region: "Southeast Asia",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 6,
    activeMilitaryPersonnel: 360000,
    doctrine:
      "Internal stability, US treaty alliance, balancing US and China procurement, and counter-insurgency in Deep South.",
    aircraft: [
      "F-16A/B ADF",
      "Gripen C/D",
      "Alpha Jet",
      "Saab 340 AEW",
      "T-50TH",
    ],
    missiles: [
      "AIM-120C AMRAAM",
      "Meteor BVRAAM",
      "RBS 15F",
      "Spyder SR / KS-1C SAM",
      "DTI-1G MLRS",
    ],
    naval: [
      "HTMS Chakri Naruebet (V/STOL carrier, no fixed-wing)",
      "Naresuan-class FFG",
      "Bhumibol Adulyadej-class FFG",
      "Pattani-class OPV",
      "Type 041 Yuan SSK (procurement, contested)",
    ],
    groundForces: [
      "VT4 MBT (Chinese)",
      "Oplot-T MBT (Ukrainian)",
      "M60A3 TTS",
      "Stryker ICV",
      "Royal Thai Special Forces",
    ],
    bases: [
      "Don Muang Air Base",
      "U-Tapao International Airport (military use)",
      "Sattahip Naval Base",
      "Phang Nga Naval Base (Andaman)",
    ],
    alliances: [
      "US-Thailand Treaty of Amity (1833) and SEATO legacy",
      "Major Non-NATO Ally of US",
      "ASEAN",
    ],
    notableCapabilities: [
      "Only ASEAN state with aircraft carrier (limited utility)",
      "Mixed US/Chinese/Ukrainian armoured fleet",
      "Hosts annual Cobra Gold exercise",
    ],
  },
  {
    code: "MX",
    name: "Mexico",
    region: "North America",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 8,
    activeMilitaryPersonnel: 277000,
    doctrine:
      "Internal security, counter-narcotics, civil protection, and cooperation with US under Bicentennial Framework. Constitutional non-intervention foreign policy.",
    aircraft: [
      "F-5E/F Tiger II",
      "Pilatus PC-7",
      "T-6C+ Texan II",
      "C-130E/H Hercules",
      "MD-902 Explorer",
    ],
    missiles: ["AIM-9 Sidewinder", "Sea Sparrow"],
    naval: [
      "Reformador-class (SIGMA 10514) FFG",
      "Bravo-class (Holzinger) frigate",
      "Oaxaca-class OPV",
      "Tenochtitlan-class POLA",
    ],
    groundForces: [
      "ERC-90 Sagaie",
      "M3 Stuart (legacy)",
      "Sandcat / SCDF / DN-XI armoured vehicles",
      "FES (Marina) special forces",
      "GAFE Army special forces",
    ],
    bases: [
      "Santa Lucía Air Base / Felipe Ángeles International",
      "Manzanillo Naval Base",
      "Veracruz Naval Base",
      "Acapulco Naval Base",
    ],
    alliances: [
      "Rio Treaty (TIAR)",
      "USMCA (economic)",
      "Bicentennial Framework with US",
    ],
    notableCapabilities: [
      "Largest Spanish-speaking military",
      "Naval focus on counter-narcotics and SAR",
      "Strategic land border with US",
    ],
  },
  {
    code: "ZA",
    name: "South Africa",
    region: "Africa",
    nuclearStatus: "former",
    militaryBudgetUsdBillions: 3,
    activeMilitaryPersonnel: 73000,
    doctrine:
      "Defence of constitution, regional peace support operations (SADC), and African Standby Force. Voluntarily denuclearized in 1989-1991.",
    aircraft: [
      "Gripen C/D",
      "Hawk Mk120",
      "Rooivalk attack helicopter",
      "C-130BZ Hercules",
    ],
    missiles: [
      "A-Darter air-to-air",
      "R-Darter / Umkhonto-IR SAM",
      "Mokopa anti-tank",
      "ZT3 Ingwe anti-tank",
    ],
    naval: [
      "Valour-class FFG (Meko A-200SAN)",
      "Heroine-class (Type 209/1400) SSK",
      "Warrior-class fast attack craft",
    ],
    groundForces: [
      "Olifant Mk2 MBT",
      "Ratel IFV",
      "Rooikat 76 fire-support",
      "Badger / Patria AMV",
      "Special Forces Brigade (Recces)",
    ],
    bases: [
      "AFB Waterkloof",
      "AFB Makhado",
      "Naval Base Simon's Town",
      "AFB Hoedspruit",
    ],
    alliances: [
      "African Union",
      "SADC",
      "BRICS+",
      "Non-Aligned Movement",
    ],
    notableCapabilities: [
      "Only state to indigenously develop and dismantle nuclear weapons",
      "Indigenous defence-industrial base (Denel, Paramount)",
      "Rooivalk attack helicopter",
      "Africa's most advanced submarine fleet",
    ],
  },
];
