import type { CountryProfile } from "./types";

export const countriesB: CountryProfile[] = [
  {
    code: "AU",
    name: "Australia",
    region: "Oceania",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 32,
    activeMilitaryPersonnel: 60000,
    doctrine:
      "Defence of Australia and the immediate region with forward partnership posture, AUKUS-enabled long-range strike, and integrated US allied force posture in the north.",
    aircraft: [
      "F-35A Lightning II",
      "F/A-18F Super Hornet",
      "EA-18G Growler",
      "E-7A Wedgetail AEW&C",
      "P-8A Poseidon MPA",
      "MQ-4C Triton (entering service)",
      "C-17A Globemaster III",
    ],
    missiles: [
      "AGM-158C LRASM",
      "Tomahawk Block V (procurement)",
      "AGM-158B JASSM-ER",
      "SM-2 / SM-6",
      "RGM-84L Harpoon Block II",
      "PrSM (procurement)",
    ],
    naval: [
      "Hobart-class Aegis destroyer",
      "Anzac-class frigate",
      "Hunter-class FFG (under construction)",
      "Canberra-class LHD",
      "Collins-class SSK",
      "AUKUS Virginia-class SSN (planned 2030s)",
    ],
    groundForces: [
      "M1A2 Abrams SEPv3 (incoming)",
      "Boxer CRV",
      "Redback IFV (procurement)",
      "AS9 Huntsman SP howitzer (HIMARS supplement)",
      "Special Air Service Regiment (SASR)",
      "2nd Commando Regiment",
    ],
    bases: [
      "RAAF Tindal (F-35A, B-52 rotational)",
      "RAAF Darwin",
      "RAAF Curtin / Learmonth (bare bases)",
      "HMAS Stirling (Fleet Base West)",
      "Pine Gap (joint US SIGINT)",
      "North West Cape (US/Australian comms)",
    ],
    alliances: [
      "ANZUS Treaty",
      "AUKUS",
      "Quad",
      "Five Eyes",
      "Five Power Defence Arrangements",
    ],
    notableCapabilities: [
      "AUKUS pillar I (SSN-AUKUS) and pillar II tech sharing",
      "Forward-deployed US Marine rotational force in Darwin",
      "Tier-1 SIGINT via ASD",
      "Long-range strike via LRASM / Tomahawk",
    ],
  },
  {
    code: "IT",
    name: "Italy",
    region: "Europe",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 33,
    activeMilitaryPersonnel: 165000,
    doctrine:
      "NATO Mediterranean and Southern Flank security, host to US B61 nuclear sharing under DCA, expeditionary maritime power, and counter-piracy / counter-terror role.",
    aircraft: [
      "Eurofighter Typhoon",
      "F-35A / F-35B",
      "Tornado IDS (DCA role, retiring)",
      "AV-8B+ Harrier II Plus",
      "C-27J Spartan",
      "KC-767A tanker",
    ],
    missiles: [
      "Storm Shadow / SCALP",
      "MBDA Meteor",
      "Aster 15 / Aster 30",
      "CAMM-ER",
      "Marte ER anti-ship missile",
    ],
    naval: [
      "ITS Cavour (C 550) carrier",
      "ITS Trieste (LHD, F-35B)",
      "Andrea Doria-class destroyer",
      "FREMM frigate (Carlo Bergamini-class)",
      "Todaro-class (U212A) SSK",
    ],
    groundForces: [
      "Ariete C1 / C2 MBT",
      "Centauro / Centauro II tank destroyer",
      "Dardo IFV",
      "Freccia AIFV",
      "PzH 2000 SP howitzer",
      "Comando Subacquei e Incursori (COMSUBIN)",
      "9° Reggimento d'Assalto Paracadutisti Col Moschin",
    ],
    bases: [
      "Aviano Air Base (US 31st FW host)",
      "Ghedi Air Base (B61 storage)",
      "Sigonella NAS (US/IT MPA hub)",
      "Decimomannu Air Base",
      "La Spezia Naval Base",
      "Taranto Naval Base",
    ],
    alliances: ["NATO Article 5", "EU Article 42.7", "Quint"],
    notableCapabilities: [
      "DCA nuclear sharing role at Ghedi",
      "Two flat-deck STOVL ships with F-35B",
      "Co-developer of Eurofighter, FREMM, U212A",
    ],
  },
  {
    code: "ES",
    name: "Spain",
    region: "Europe",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 21,
    activeMilitaryPersonnel: 121000,
    doctrine:
      "NATO collective defence with focus on the Atlantic and Mediterranean approaches, host to US naval and air bases, and counter-terror in the Sahel.",
    aircraft: [
      "Eurofighter Typhoon",
      "F/A-18 Hornet (EF-18M)",
      "AV-8B+ Harrier II Plus",
      "A400M Atlas",
      "P-3M Orion (replacement planned)",
    ],
    missiles: [
      "MBDA Meteor",
      "AIM-120 AMRAAM",
      "Harpoon Block II",
      "Aster 15 / Aster 30",
      "ESSM",
    ],
    naval: [
      "Juan Carlos I (L-61) LHD/STOVL carrier",
      "Álvaro de Bazán-class F100 Aegis frigate",
      "Santa María-class FFG",
      "S-80 Plus class submarine (Isaac Peral)",
    ],
    groundForces: [
      "Leopard 2E MBT",
      "Pizarro IFV",
      "Centauro tank destroyer",
      "VCR 8x8 Dragón (incoming)",
      "Spanish Legion (BRILEG)",
      "GOE / UOE special forces",
    ],
    bases: [
      "Naval Station Rota (US Aegis BMD destroyers host)",
      "Morón Air Base (US AFRICOM hub)",
      "Zaragoza Air Base",
      "Albacete (Tactical Leadership Programme)",
    ],
    alliances: ["NATO Article 5", "EU Article 42.7"],
    notableCapabilities: [
      "Hosts forward-deployed US Aegis BMD destroyers at Rota",
      "STOVL operations from Juan Carlos I",
      "Mediterranean MPA and SAR coverage",
    ],
  },
  {
    code: "NL",
    name: "Netherlands",
    region: "Europe",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 16,
    activeMilitaryPersonnel: 41000,
    doctrine:
      "NATO collective defence as DCA participant, expeditionary contributor, and integrated logistics hub via Rotterdam.",
    aircraft: [
      "F-35A Lightning II",
      "F-16AM/BM (retiring)",
      "AH-64E Apache Guardian",
      "CH-47F Chinook",
      "MQ-9A Reaper",
    ],
    missiles: [
      "AIM-120C AMRAAM",
      "ESSM",
      "SM-2 Block IIIB",
      "Harpoon Block II",
      "Patriot PAC-3 MSE",
    ],
    naval: [
      "De Zeven Provinciën-class air-defence and command frigate",
      "Karel Doorman-class M-frigate",
      "Holland-class OPV",
      "Walrus-class SSK",
    ],
    groundForces: [
      "Leopard 2A6/A7 MBT (joint with Germany)",
      "CV9035NL IFV",
      "Boxer wheeled APC",
      "PzH 2000 SP howitzer",
      "Korps Commandotroepen (KCT) / NLMARSOF",
    ],
    bases: [
      "Volkel Air Base (B61 storage, F-35A DCA)",
      "Leeuwarden Air Base",
      "Den Helder Naval Base",
      "Eindhoven Air Base (transport hub)",
    ],
    alliances: [
      "NATO Article 5",
      "EU Article 42.7",
      "European Sky Shield Initiative",
      "1st German-Netherlands Corps",
    ],
    notableCapabilities: [
      "DCA nuclear sharing role at Volkel",
      "Joint armoured brigade structure with Germany",
      "Integrated air defence with German Patriot units",
    ],
  },
  {
    code: "TR",
    name: "Türkiye",
    region: "Middle East",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 22,
    activeMilitaryPersonnel: 425000,
    doctrine:
      "Independent regional power posture, NATO southern flank, cross-border counter-PKK operations, and indigenous arms development for export and self-reliance.",
    aircraft: [
      "F-16C/D Block 30/40/50",
      "F-4E 2020 Terminator (retiring)",
      "Bayraktar TB2 / Akıncı UCAV",
      "Anka-S MALE UAV",
      "A400M Atlas",
      "KAAN (TF-X) fifth-gen prototype",
    ],
    missiles: [
      "SOM-J cruise missile",
      "Bozdoğan / Gökdoğan air-to-air",
      "Atmaca anti-ship missile",
      "HISAR-O / SIPER air defence",
      "S-400 Triumf (Russian, suspended F-35)",
      "TAYFUN tactical ballistic missile",
    ],
    naval: [
      "TCG Anadolu (L-400) UAV-carrier LHD",
      "Ada-class corvette (Milgem)",
      "İstanbul-class frigate",
      "Reis-class (Type 214TN) SSK",
      "Gür-class (Type 209/1400) SSK",
    ],
    groundForces: [
      "Altay MBT (entering)",
      "Leopard 2A4 MBT",
      "M60T Sabra MBT",
      "Kaplan / Tulpar AIFV",
      "T-155 Fırtına SP howitzer",
      "Maroon Berets (Bordo Bereliler)",
    ],
    bases: [
      "Incirlik Air Base (US B61 storage)",
      "Konya Air Base",
      "Aksaz Naval Base",
      "Gölcük Naval Base (submarine base)",
      "Camp TURKSOM, Mogadishu, Somalia",
      "Bashiqa, Iraq",
    ],
    alliances: ["NATO Article 5", "Organization of Turkic States"],
    notableCapabilities: [
      "World leader in armed UCAV exports (TB2)",
      "Indigenous LHD with UCAV air wing",
      "Hosts US B61 weapons at Incirlik",
      "Manufacturer of S-400 systems alongside NATO equipment",
    ],
  },
  {
    code: "PL",
    name: "Poland",
    region: "Europe",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 31,
    activeMilitaryPersonnel: 202000,
    doctrine:
      "Forward defence on NATO eastern flank, rapid mass-buildup of armoured and rocket forces, and procurement of Korean and US systems for deterrence-by-denial against Russia.",
    aircraft: [
      "F-35A Lightning II (incoming)",
      "F-16C/D Block 52+",
      "FA-50 Fighting Eagle (Korean)",
      "MiG-29 (retiring)",
      "AH-64E Apache (procurement)",
    ],
    missiles: [
      "HIMARS / Homar-K MLRS",
      "K239 Chunmoo MLRS",
      "JASSM-ER",
      "AGM-158C LRASM",
      "Patriot PAC-3 MSE (Wisła program)",
      "CAMM (Narew air defence)",
    ],
    naval: [
      "Orkan-class missile boat",
      "Kormoran-II MCM",
      "Miecznik-class frigate (under construction)",
      "Kobben-class SSK (retiring)",
    ],
    groundForces: [
      "M1A2 SEPv3 Abrams MBT",
      "K2 Black Panther / K2PL MBT",
      "Leopard 2A4/A5 MBT (legacy)",
      "Borsuk IFV",
      "K9A1 Thunder SP howitzer",
      "GROM / FORMOZA / AGAT special forces",
    ],
    bases: [
      "Powidz Air Base (US Army APS-2)",
      "Łask Air Base (NATO ASP)",
      "Redzikowo Aegis Ashore site",
      "Warsaw V Corps Forward HQ (US Army)",
      "Żagań / Świętoszów armoured base",
    ],
    alliances: [
      "NATO Article 5",
      "EU Article 42.7",
      "Bucharest Nine (B9)",
      "Lublin Triangle",
    ],
    notableCapabilities: [
      "Hosts Aegis Ashore at Redzikowo",
      "One of fastest-growing NATO armies in Europe",
      "Massive K2 / Abrams / K9 procurement (>1000 tanks ordered)",
      "Permanent US V Corps Forward HQ",
    ],
  },
  {
    code: "CA",
    name: "Canada",
    region: "North America",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 27,
    activeMilitaryPersonnel: 68000,
    doctrine:
      "Continental defence with US under NORAD, Arctic sovereignty, NATO collective defence, and expeditionary contribution to UN/coalition operations.",
    aircraft: [
      "CF-18 Hornet (replacement F-35A starting 2026)",
      "CP-140 Aurora MPA",
      "CC-130J Super Hercules",
      "CC-150 Polaris",
      "MQ-9B SkyGuardian (procurement)",
    ],
    missiles: [
      "AIM-120C AMRAAM",
      "AGM-84 Harpoon",
      "ESSM",
      "RIM-162 ESSM",
      "AIM-9X Sidewinder",
    ],
    naval: [
      "Halifax-class FFG",
      "Harry DeWolf-class AOPV",
      "Victoria-class SSK",
      "River-class destroyer (CSC, future)",
    ],
    groundForces: [
      "Leopard 2A6M / 2A4 MBT",
      "LAV 6.0 ICV",
      "M777 howitzer",
      "Joint Task Force 2 (JTF2)",
      "Canadian Special Operations Regiment (CSOR)",
    ],
    bases: [
      "CFB Cold Lake",
      "CFB Bagotville",
      "CFB Esquimalt (Pacific Fleet)",
      "CFB Halifax (Atlantic Fleet)",
      "CFS Alert (Arctic SIGINT)",
      "CFB Trenton (airlift hub)",
    ],
    alliances: [
      "NATO Article 5",
      "NORAD (binational with US)",
      "Five Eyes",
      "Combined Maritime Forces",
    ],
    notableCapabilities: [
      "NORAD shared continental aerospace defence with US",
      "Arctic territory and surveillance footprint",
      "CSE SIGINT integration with Five Eyes",
    ],
  },
  {
    code: "BR",
    name: "Brazil",
    region: "South America",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 22,
    activeMilitaryPersonnel: 366000,
    doctrine:
      "Defence of the Amazon and South Atlantic 'Blue Amazon', strategic autonomy, and regional leadership without offensive force projection. Civilian-controlled nuclear program for naval propulsion.",
    aircraft: [
      "F-39E Gripen",
      "AMX A-1M (retiring)",
      "Super Tucano A-29",
      "KC-390 Millennium",
      "H225M Caracal",
    ],
    missiles: [
      "MAA-1B Piranha",
      "MAR-1 anti-radiation missile",
      "Exocet MM40 Block 3",
      "AV-TM 300 cruise missile (developmental)",
      "AS-AS Astros II MLRS",
    ],
    naval: [
      "NAM Atlântico (A140) helicopter carrier (ex-Ocean)",
      "Tamandaré-class corvette",
      "Niterói-class frigate",
      "Riachuelo-class (Scorpène) SSK",
      "SN-Álvaro Alberto SSN (in development)",
    ],
    groundForces: [
      "Leopard 1A5 BR / M60A3 TTS MBT",
      "Guarani 6x6 APC",
      "Astros II SS-30/40/60 MLRS",
      "Brigada de Operações Especiais (COMANF)",
    ],
    bases: [
      "Anápolis Air Base (Gripen)",
      "Santa Cruz Air Base",
      "Manaus (Amazon Military Command)",
      "Itaguaí Naval Base (SSN program)",
      "Aramar (uranium enrichment)",
    ],
    alliances: [
      "Rio Treaty (TIAR)",
      "BRICS+",
      "Mercosur",
      "South Atlantic Peace and Cooperation Zone (ZPCAS)",
    ],
    notableCapabilities: [
      "Indigenous SSN program (PROSUB) with French cooperation",
      "Largest military in Latin America",
      "Civilian-controlled uranium enrichment for naval reactor",
    ],
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    region: "Middle East",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 75,
    activeMilitaryPersonnel: 257000,
    doctrine:
      "Counter-Iran deterrence, regime security via SANG, layered air defence over critical oil infrastructure, and coalition operations in Yemen.",
    aircraft: [
      "F-15SA Eagle",
      "F-15C/D Eagle",
      "Eurofighter Typhoon",
      "Tornado IDS",
      "AH-64E Apache",
      "E-3A Sentry AWACS",
    ],
    missiles: [
      "AIM-120C AMRAAM",
      "Storm Shadow",
      "AGM-84 Harpoon",
      "Patriot PAC-3 GEM-T",
      "THAAD (US procurement)",
      "DF-3A / DF-21 (legacy Chinese, Strategic Missile Force)",
    ],
    naval: [
      "Al Riyadh-class frigate (F3000)",
      "Al Jubail-class corvette (Avante 2200)",
      "Sawari II frigates",
      "Badr-class corvette",
    ],
    groundForces: [
      "M1A2S Abrams MBT",
      "AMX-30 / M60A3 TTS (legacy)",
      "Bradley M2A2 IFV",
      "LAV-25 / LAV III",
      "Saudi Royal Guard",
      "SANG (Saudi Arabian National Guard)",
    ],
    bases: [
      "King Abdulaziz Air Base, Dhahran",
      "Prince Sultan Air Base, Al Kharj (US AFCENT host)",
      "King Faisal Naval Base, Jeddah",
      "King Abdulaziz Naval Base, Jubail",
      "Tabuk military complex",
    ],
    alliances: [
      "GCC Defense Cooperation",
      "US-Saudi Arabia Joint Commission",
      "Islamic Military Counter Terrorism Coalition (IMCTC)",
      "OPEC+",
    ],
    notableCapabilities: [
      "Largest defense budget in MENA",
      "Layered Patriot/THAAD missile defence over oil infrastructure",
      "Strategic Missile Force with legacy Chinese IRBMs",
      "World's largest oil producer (Aramco)",
    ],
  },
  {
    code: "PK",
    name: "Pakistan",
    region: "South Asia",
    nuclearStatus: "declared",
    militaryBudgetUsdBillions: 10,
    activeMilitaryPersonnel: 654000,
    doctrine:
      "Full-spectrum deterrence including tactical nuclear weapons against Indian Cold Start, defence-in-depth, and ISI-managed asymmetric leverage across the region.",
    aircraft: [
      "JF-17 Block II/III Thunder",
      "F-16C/D Block 52",
      "Mirage III / V (retiring)",
      "J-10C (Chinese)",
      "ZDK-03 Karakoram Eagle AEW&C",
    ],
    missiles: [
      "Babur cruise missile (land/sea)",
      "Ra'ad / Ra'ad-II ALCM",
      "Nasr (Hatf-IX) tactical SRBM",
      "Shaheen-II / III MRBM/IRBM",
      "Ghauri MRBM",
      "Ababeel MIRV (developmental)",
    ],
    naval: [
      "Tughril-class frigate (Type 054A/P)",
      "Zulfiquar-class frigate (F22P)",
      "Agosta-90B Khalid-class SSK",
      "Hangor-II SSK (Chinese, under construction)",
    ],
    groundForces: [
      "Al-Khalid / Al-Khalid-II MBT",
      "T-80UD MBT",
      "Type 85-IIAP MBT",
      "Al-Zarrar (upgraded T-59)",
      "Special Service Group (SSG)",
      "SSG Navy / SSW",
    ],
    bases: [
      "Sargodha Air Base / Mushaf",
      "Kamra Aeronautical Complex",
      "Karachi Naval Base",
      "Ormara Naval Base / Jinnah Naval Base",
      "Gwadar (Chinese-financed port)",
    ],
    alliances: [
      "China-Pakistan Strategic Partnership",
      "Major Non-NATO Ally (US, since 2004)",
      "OIC",
      "SCO",
    ],
    notableCapabilities: [
      "Tactical nuclear weapons (Nasr) for battlefield use",
      "Cruise-missile triad (land, sea, air)",
      "Largest army in the Islamic world",
      "Co-developer with China of JF-17",
    ],
  },
];
