import type { CountryProfile } from "./types";

export const countriesD: CountryProfile[] = [
  {
    code: "SE",
    name: "Sweden",
    region: "Europe",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 13,
    activeMilitaryPersonnel: 24000,
    doctrine:
      "Total defence (Totalförsvar) reactivated, NATO Article 5 newly integrated (2024), focus on Baltic and Arctic, indigenous high-end systems.",
    aircraft: [
      "JAS 39C/D Gripen / JAS 39E Gripen E",
      "C-130H Hercules",
      "S 100B Argus AEW&C (Saab 340)",
      "GlobalEye AEW&C (procurement)",
    ],
    missiles: [
      "Meteor BVRAAM",
      "RBS 15 Mk3 anti-ship cruise",
      "RBS 70 NG MANPADS",
      "RBS 98 (IRIS-T SLS)",
      "Patriot PAC-3 MSE",
    ],
    naval: [
      "Visby-class stealth corvette",
      "Gotland-class AIP SSK",
      "Blekinge-class (A26) SSK (under construction)",
      "Stockholm-class corvette",
    ],
    groundForces: [
      "Strv 122 (Leopard 2A5 SE) MBT",
      "CV9040 IFV",
      "Patgb 360 (Patria AMV)",
      "Archer 155mm SP howitzer",
      "Särskilda operationsgruppen (SOG)",
    ],
    bases: [
      "F 7 Såtenäs (Gripen)",
      "F 17 Kallinge",
      "F 21 Luleå",
      "Berga Naval Base",
      "Karlskrona Naval Base",
      "Muskö (hardened underground)",
    ],
    alliances: [
      "NATO Article 5 (joined March 2024)",
      "EU Article 42.7",
      "Joint Expeditionary Force (JEF)",
      "Nordic Defence Cooperation (NORDEFCO)",
    ],
    notableCapabilities: [
      "Indigenous Gripen fighter line (E variant active)",
      "Air-independent propulsion submarine fleet",
      "Archer SP artillery exported to UK and US",
    ],
  },
  {
    code: "NO",
    name: "Norway",
    region: "Europe",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 9,
    activeMilitaryPersonnel: 23000,
    doctrine:
      "Defence of the High North, NATO maritime gateway to the Arctic, host of US Marine prepositioning, and strategic SIGINT (Norwegian Intelligence Service).",
    aircraft: [
      "F-35A Lightning II",
      "P-8A Poseidon MPA",
      "AW101 SAR",
      "C-130J Super Hercules",
    ],
    missiles: [
      "Naval Strike Missile (NSM)",
      "Joint Strike Missile (JSM)",
      "AIM-9X Sidewinder",
      "AIM-120C-7 AMRAAM",
      "NASAMS (co-developed with US)",
    ],
    naval: [
      "Fridtjof Nansen-class FFG (Aegis)",
      "Skjold-class corvette",
      "Ula-class SSK",
      "Type 212CD (under construction, joint with Germany)",
    ],
    groundForces: [
      "Leopard 2A4NO (replacement K2 NO under negotiation)",
      "CV9030N IFV",
      "M109A3GNM SP howitzer (replaced by K9)",
      "K9 Vidar SP howitzer",
      "Forsvarets Spesialkommando (FSK)",
    ],
    bases: [
      "Ørland Air Station (F-35A)",
      "Evenes Air Station (P-8A, F-35A QRA)",
      "Bardufoss Air Station",
      "Haakonsvern Naval Base (largest in Northern Europe)",
      "MCPP-N Trondheim (US Marines prepositioning)",
    ],
    alliances: ["NATO Article 5 (founding member)", "JEF", "NORDEFCO"],
    notableCapabilities: [
      "Frontline NATO airspace adjacent to Russian Northern Fleet",
      "Joint Strike Missile co-developed with Lockheed",
      "Tier-1 SIGINT collection on Russian SSBNs",
      "Prepositioned US Marine equipment caves",
    ],
  },
  {
    code: "FI",
    name: "Finland",
    region: "Europe",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 7,
    activeMilitaryPersonnel: 23000,
    doctrine:
      "Total defence with universal conscription, ~280k wartime strength, NATO collective defence on Russia's longest western border.",
    aircraft: [
      "F/A-18C/D Hornet (replacement F-35A)",
      "F-35A Lightning II (incoming)",
      "Hawk Mk66 trainer",
      "C-295 transport",
    ],
    missiles: [
      "AIM-120C AMRAAM",
      "AIM-9X Sidewinder",
      "JASSM-ER (procurement with F-35A)",
      "M270 MLRS / GMLRS-ER",
      "NASAMS-2",
      "Crotale NG / ASRAD-R",
    ],
    naval: [
      "Hamina-class missile boat",
      "Pohjanmaa-class (Squadron 2020) corvette (under construction)",
      "Hämeenmaa-class minelayer",
    ],
    groundForces: [
      "Leopard 2A4 / 2A6 MBT",
      "CV9030FI IFV",
      "BMP-2MD (legacy)",
      "K9 Moukari SP howitzer",
      "Special Jaeger Battalion (Erikoisjääkäripataljoona)",
    ],
    bases: [
      "Karelia Air Command (Rissala)",
      "Lapland Air Command (Rovaniemi)",
      "Satakunta Air Command (Tampere-Pirkkala)",
      "Pansio Naval Base (Turku)",
      "Upinniemi Naval Base",
    ],
    alliances: [
      "NATO Article 5 (joined April 2023)",
      "EU Article 42.7",
      "JEF",
      "NORDEFCO",
    ],
    notableCapabilities: [
      "Largest reserve force per capita in NATO (~870k including reserves)",
      "Universal conscription with ~30k trainees per year",
      "Largest artillery in Western Europe",
      "1340 km direct land border with Russia",
    ],
  },
  {
    code: "DK",
    name: "Denmark",
    region: "Europe",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 7,
    activeMilitaryPersonnel: 17000,
    doctrine:
      "NATO collective defence, Arctic sovereignty (Greenland), expeditionary contributions, and EU CSDP integration.",
    aircraft: [
      "F-35A Lightning II",
      "F-16AM/BM (retiring)",
      "MH-60R Seahawk",
      "EH101 Merlin",
    ],
    missiles: [
      "AIM-120C AMRAAM",
      "AIM-9X Sidewinder",
      "Harpoon Block II",
      "ESSM",
      "RBS 70 / Stinger",
    ],
    naval: [
      "Iver Huitfeldt-class FFG",
      "Absalon-class command/support ship",
      "Knud Rasmussen-class Arctic OPV",
      "Thetis-class Arctic OPV",
    ],
    groundForces: [
      "Leopard 2A7DK MBT",
      "CV9035DK IFV",
      "Piranha V",
      "M109A3 (replaced by CAESAR 8x8)",
      "CAESAR 8x8 SP howitzer",
      "Jægerkorpset / Frømandskorpset",
    ],
    bases: [
      "Skrydstrup Air Base (F-35A)",
      "Aalborg Air Base",
      "Frederikshavn Naval Base",
      "Korsør Naval Base",
      "Thule Air Base, Greenland (US, Pituffik)",
    ],
    alliances: [
      "NATO Article 5",
      "EU Article 42.7 (opt-out lifted 2022)",
      "JEF",
      "NORDEFCO",
    ],
    notableCapabilities: [
      "Greenland sovereignty (Arctic positioning)",
      "Strait of Denmark naval choke-point control",
      "F-35A and Iver Huitfeldt frigate force",
    ],
  },
  {
    code: "BE",
    name: "Belgium",
    region: "Europe",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 7,
    activeMilitaryPersonnel: 26000,
    doctrine:
      "NATO collective defence, DCA participant (B61), host of NATO HQ and SHAPE, motorized brigade contribution.",
    aircraft: [
      "F-16AM/BM (retiring)",
      "F-35A Lightning II (incoming)",
      "A400M Atlas",
      "NH90 NFH",
    ],
    missiles: ["AIM-120 AMRAAM", "AIM-9X", "Mistral 3 MANPADS", "ESSM"],
    naval: [
      "Karel Doorman-class M-frigate (Leopold I, Louise-Marie)",
      "City-class MCM (incoming)",
    ],
    groundForces: [
      "Piranha 5 IFV",
      "Pandur APC",
      "CAESAR 6x6 SP howitzer (incoming)",
      "Special Forces Group (SFG)",
    ],
    bases: [
      "Kleine Brogel Air Base (B61 storage)",
      "Florennes Air Base",
      "Beauvechain Air Base",
      "NATO HQ Brussels",
      "SHAPE Mons",
    ],
    alliances: [
      "NATO Article 5 (founding member)",
      "EU Article 42.7",
      "Benelux Defence Cooperation",
    ],
    notableCapabilities: [
      "Hosts NATO HQ Brussels and SHAPE Mons",
      "DCA nuclear sharing role at Kleine Brogel",
      "Joint MCM force with Netherlands",
    ],
  },
  {
    code: "GR",
    name: "Greece",
    region: "Europe",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 8,
    activeMilitaryPersonnel: 142000,
    doctrine:
      "Defence of national territory in Aegean and Eastern Mediterranean, deterrence vs. Türkiye, NATO southern flank.",
    aircraft: [
      "F-16C/D Block 52+ Advanced",
      "F-16V Viper (upgrade in progress)",
      "Rafale F3R",
      "F-4E Phantom II AUP",
      "Mirage 2000-5 Mk2 (retiring)",
      "F-35A Lightning II (procurement)",
    ],
    missiles: [
      "AIM-120C-7 AMRAAM",
      "Meteor BVRAAM",
      "Storm Shadow / SCALP",
      "Exocet AM39 / MM40",
      "Patriot PAC-3 MSE",
      "S-300PMU-1 (legacy)",
    ],
    naval: [
      "Hydra-class FFG (Meko 200HN)",
      "Belharra (FDI HN) frigate (under construction)",
      "Roussen-class FAC(M)",
      "Type 214 / Glafkos-class SSK",
    ],
    groundForces: [
      "Leopard 2A6HEL MBT",
      "Leopard 2A4 / 1A5",
      "M1117 Guardian",
      "M270 MLRS",
      "ETA / OYK special forces",
    ],
    bases: [
      "Souda Bay Naval Air Station, Crete (US/NATO)",
      "Larissa Air Base",
      "Andravida Air Base",
      "Salamis Naval Base",
    ],
    alliances: [
      "NATO Article 5",
      "EU Article 42.7",
      "Greece-France Strategic Partnership (mutual defence clause)",
      "Greece-Israel-Cyprus trilateral",
    ],
    notableCapabilities: [
      "F-35A + Rafale dual fifth/4.5-gen fleet",
      "Hosts US/NATO Souda Bay maritime hub",
      "Belharra frigate program with France",
    ],
  },
  {
    code: "AR",
    name: "Argentina",
    region: "South America",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 4,
    activeMilitaryPersonnel: 75000,
    doctrine:
      "Defence of sovereignty (Falklands/Malvinas claim), counter-drug, civil emergency response, Antarctic operations. Civilian-controlled nuclear program (no weapons).",
    aircraft: [
      "F-16AM/BM (procurement from Denmark)",
      "A-4AR Fightinghawk (retiring)",
      "IA-63 Pampa III trainer",
      "P-3B Orion MPA",
      "C-130H Hercules",
    ],
    missiles: ["AIM-9 / Aspide", "Exocet MM38/MM40"],
    naval: [
      "MEKO 360H2 destroyer",
      "MEKO 140A16 corvette",
      "ARA Bouchard-class OPV",
      "TR-1700-class SSK (limited operational)",
    ],
    groundForces: [
      "TAM 2C MBT",
      "VCTP IFV",
      "M-114 howitzer",
      "Special Operations Group (Halcón / Buzos Tácticos)",
    ],
    bases: [
      "Mar del Plata Naval Base",
      "Puerto Belgrano Naval Base",
      "Tandil Air Brigade",
      "Río Gallegos Air Base (Falklands proximity)",
      "Marambio Antarctic Base",
    ],
    alliances: ["Rio Treaty (TIAR)", "Mercosur"],
    notableCapabilities: [
      "Antarctic operational presence",
      "Latin America's most advanced civilian nuclear program",
      "TAM tank co-developed with Germany",
    ],
  },
  {
    code: "SG",
    name: "Singapore",
    region: "Southeast Asia",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 14,
    activeMilitaryPersonnel: 51000,
    doctrine:
      "Total defence, deterrence-by-denial, swift retaliation, third-generation SAF networked operations, integrated city-state air defence.",
    aircraft: [
      "F-15SG Strike Eagle",
      "F-16C/D Block 52+ Advanced",
      "F-35A / F-35B (procurement)",
      "G550 CAEW",
      "AH-64D Apache",
      "P-8A Poseidon (procurement)",
    ],
    missiles: [
      "AIM-120C-7 AMRAAM",
      "Spike NLOS",
      "RBS 70 / Mistral",
      "ASTER 30",
      "Iron Dome (procurement)",
      "Spyder",
    ],
    naval: [
      "Formidable-class stealth FFG",
      "Independence-class LMV (corvette)",
      "Endurance-class LST",
      "Invincible-class (Type 218SG) SSK",
      "Archer / Challenger-class SSK (legacy)",
    ],
    groundForces: [
      "Leopard 2SG MBT",
      "Bionix II IFV",
      "Hunter AFV",
      "Terrex 2",
      "HIMARS",
      "Singapore Special Operations Force (SOF)",
    ],
    bases: [
      "Tengah Air Base",
      "Paya Lebar Air Base (relocating)",
      "Changi Naval Base (US LCS rotation host)",
      "Sembawang Naval Area",
      "Detachments at RAAF Pearce, Cazaux (FR), Luke AFB (US)",
    ],
    alliances: [
      "Five Power Defence Arrangements",
      "Major Security Cooperation Partner of US",
      "ASEAN",
    ],
    notableCapabilities: [
      "Highest defence-spending per capita in SE Asia",
      "Type 218SG submarines (most advanced in region)",
      "Iron Dome procurement (first export sale)",
      "Hosts forward-deployed US LCS",
    ],
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    region: "Middle East",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 23,
    activeMilitaryPersonnel: 65000,
    doctrine:
      "Counter-Iran posture, expeditionary operations (Yemen, Libya), interoperability with US, Mirage/F-16 fleet, layered air defence.",
    aircraft: [
      "F-16E/F Block 60 Desert Falcon",
      "Mirage 2000-9",
      "A330 MRTT",
      "C-17A Globemaster III",
      "AH-64E Apache",
    ],
    missiles: [
      "AIM-120C AMRAAM",
      "MICA",
      "Storm Shadow / Black Shaheen",
      "Patriot PAC-3 GEM-T",
      "THAAD (first export customer)",
      "Iron Dome (procurement)",
    ],
    naval: [
      "Baynunah-class corvette",
      "Abu Dhabi-class corvette (Falaj 2)",
      "Ghannatha-class missile boat",
    ],
    groundForces: [
      "Leclerc Tropicalisé MBT",
      "BMP-3 IFV",
      "Patria AMV",
      "Caesar 8x8 SP howitzer",
      "UAE Presidential Guard / Special Operations Command",
    ],
    bases: [
      "Al Dhafra Air Base (US AFCENT host)",
      "Jebel Ali Naval Port",
      "Fujairah Naval Base",
      "Berbera, Somaliland (UAE-leased)",
      "Assab, Eritrea (former)",
    ],
    alliances: ["GCC", "Abraham Accords", "Major Defense Partner of US"],
    notableCapabilities: [
      "First THAAD export customer",
      "F-16 Block 60 most advanced export Block",
      "Indigenous EDGE Group defence conglomerate",
      "Hosts Al Dhafra (US AFCENT major hub)",
    ],
  },
  {
    code: "QA",
    name: "Qatar",
    region: "Middle East",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 8,
    activeMilitaryPersonnel: 16500,
    doctrine:
      "Hedging strategy, host of US AFCENT forward HQ, Turkish strategic partnership, mediator role, defence buildup post-blockade.",
    aircraft: [
      "Rafale EQ/DQ",
      "Eurofighter Typhoon",
      "F-15QA Ababil",
      "C-17A Globemaster III",
      "AH-64E Apache",
    ],
    missiles: [
      "Meteor BVRAAM",
      "Storm Shadow",
      "MICA",
      "Patriot PAC-3 MSE",
      "NASAMS",
    ],
    naval: [
      "Al Zubarah-class corvette (Doha)",
      "Musherib-class OPV",
      "Barzan-class FAC(M)",
    ],
    groundForces: ["Leopard 2A7+", "Piranha V", "VBCI", "PzH 2000 SP howitzer"],
    bases: [
      "Al Udeid Air Base (US AFCENT forward HQ)",
      "Tariq bin Ziyad Turkish Base",
      "Doha International (military side)",
      "Hamad Naval Base",
    ],
    alliances: [
      "GCC (rejoined 2021)",
      "Major Non-NATO Ally of US",
      "Qatar-Türkiye Combined Joint Force Command",
    ],
    notableCapabilities: [
      "Al Udeid hosts US CENTCOM forward HQ and CAOC",
      "Three-fleet fighter mix (Rafale, Typhoon, F-15QA)",
      "Diplomatic mediation (Taliban, Hamas, Iran)",
      "World's largest LNG exporter",
    ],
  },
];
