import type { CountryProfile } from "./types";

export const countriesA: CountryProfile[] = [
  {
    code: "US",
    name: "United States",
    region: "North America",
    nuclearStatus: "declared",
    militaryBudgetUsdBillions: 877,
    activeMilitaryPersonnel: 1395000,
    doctrine:
      "Global power projection, nuclear triad deterrence, integrated deterrence across allies, and forward-deployed force posture. Tactical and strategic nuclear options under NC3.",
    aircraft: [
      "F-35A/B/C Lightning II",
      "F-22A Raptor",
      "F/A-18E/F Super Hornet",
      "F-15E/EX Strike Eagle",
      "F-16C/D Fighting Falcon",
      "B-2 Spirit stealth bomber",
      "B-21 Raider (entering service)",
      "B-52H Stratofortress",
      "KC-46 Pegasus tanker",
      "MQ-9 Reaper UAV",
    ],
    missiles: [
      "Tomahawk Block V cruise missile",
      "AGM-158 JASSM-ER stealth cruise missile",
      "LRASM long-range anti-ship missile",
      "SM-3 Block IIA ballistic interceptor",
      "Patriot PAC-3 MSE",
      "THAAD area missile defense",
      "HIMARS / M270 MLRS with PrSM",
      "Minuteman III ICBM",
      "Trident II D5 SLBM",
      "Hypersonic ARRW / Dark Eagle (developmental)",
    ],
    naval: [
      "11 Nimitz/Ford-class supercarriers",
      "Arleigh Burke-class Aegis destroyers",
      "Ticonderoga-class cruisers",
      "Virginia-class SSN attack submarines",
      "Ohio-class SSBN ballistic missile submarines",
      "America/Wasp-class amphibious assault ships",
      "Constellation-class frigates (under construction)",
      "Zumwalt-class stealth destroyers",
    ],
    groundForces: [
      "M1A2 SEPv3 Abrams MBT",
      "M2A4 Bradley IFV",
      "Stryker brigade combat teams",
      "82nd / 101st Airborne Divisions",
      "75th Ranger Regiment",
      "1st Special Forces Operational Detachment-Delta",
      "Marine Expeditionary Units (MEU)",
    ],
    bases: [
      "Naval Station Norfolk, Virginia",
      "Ramstein Air Base, Germany",
      "Yokosuka Naval Base, Japan",
      "Kadena Air Base, Okinawa",
      "Camp Humphreys, South Korea",
      "Diego Garcia (BIOT)",
      "Al Udeid Air Base, Qatar",
      "RAF Lakenheath, UK",
      "Aviano Air Base, Italy",
      "Djibouti Camp Lemonnier",
    ],
    alliances: [
      "NATO Article 5",
      "ANZUS Treaty",
      "US-Japan Mutual Security Treaty",
      "US-ROK Mutual Defense Treaty",
      "AUKUS",
      "Quad (with India, Japan, Australia)",
      "Five Eyes intelligence (USA, UK, CA, AU, NZ)",
      "Rio Treaty (TIAR)",
    ],
    notableCapabilities: [
      "Global blue-water navy with 11 carrier strike groups",
      "Full nuclear triad and B61-12 forward-deployed gravity bombs",
      "Worldwide SIGINT collection (NSA) and overhead reconnaissance (NRO)",
      "Carrier-based fifth-generation airpower (F-35C)",
      "Cyber Command offensive cyber operations",
      "Space Force orbital warfare and missile warning",
    ],
  },
  {
    code: "CN",
    name: "China",
    region: "East Asia",
    nuclearStatus: "declared",
    militaryBudgetUsdBillions: 292,
    activeMilitaryPersonnel: 2035000,
    doctrine:
      "Active defense, anti-access/area denial (A2/AD) within the First and Second Island Chains, gray-zone coercion, and 'intelligentized' warfare. No-first-use nuclear declaratory policy with rapidly expanding arsenal.",
    aircraft: [
      "J-20 Mighty Dragon stealth fighter",
      "J-16 multirole fighter",
      "J-10C lightweight fighter",
      "J-15 Flying Shark carrier-based fighter",
      "H-6K/N strategic bomber (cruise-missile carrier)",
      "Y-20 strategic transport",
      "KJ-500 / KJ-2000 AEW&C",
      "WZ-7 Soaring Dragon HALE UAV",
      "GJ-11 Sharp Sword stealth UCAV",
    ],
    missiles: [
      "DF-21D anti-ship ballistic missile ('carrier killer')",
      "DF-26 IRBM ('Guam killer', anti-ship variant)",
      "DF-17 hypersonic glide vehicle",
      "DF-41 ICBM (MIRV-capable)",
      "DF-31AG road-mobile ICBM",
      "JL-2 / JL-3 SLBM",
      "YJ-18 anti-ship cruise missile",
      "YJ-12 supersonic anti-ship cruise missile",
      "HQ-9 / HQ-19 long-range SAM",
      "CJ-10 / CJ-100 land-attack cruise missile",
    ],
    naval: [
      "CV-16 Liaoning, CV-17 Shandong (STOBAR carriers)",
      "CV-18 Fujian (CATOBAR carrier, sea trials)",
      "Type 055 Renhai-class large destroyer",
      "Type 052D Luyang III destroyer",
      "Type 075 Yushen-class amphibious assault ship",
      "Type 094 Jin-class SSBN",
      "Type 093 Shang-class SSN",
      "Type 039A/B Yuan-class SSK",
    ],
    groundForces: [
      "Type 99A main battle tank",
      "Type 15 light tank (mountain-warfare)",
      "PHL-191 long-range MLRS",
      "PCL-181 self-propelled howitzer",
      "PLA Rocket Force (independent service for missiles)",
      "PLA Strategic Support Force (cyber, space, EW)",
    ],
    bases: [
      "Djibouti PLA Support Base",
      "Woody Island (Yongxing Dao), Paracels",
      "Mischief, Subi, Fiery Cross reef bases (Spratlys)",
      "Yulin Naval Base, Hainan (SSBN bastion)",
      "Qingdao Naval Base",
      "Ream Naval Base presence, Cambodia",
    ],
    alliances: [
      "Shanghai Cooperation Organisation (SCO)",
      "China-Russia Comprehensive Strategic Partnership",
      "China-North Korea Mutual Aid and Cooperation Treaty (1961)",
      "BRICS+",
    ],
    notableCapabilities: [
      "World's largest navy by hull count",
      "Largest standing army by personnel",
      "Rapidly expanding nuclear arsenal (projected 1500 warheads by 2035)",
      "Anti-satellite (ASAT) capability demonstrated 2007",
      "Comprehensive A2/AD architecture in the Western Pacific",
      "Dual-use BeiDou satellite navigation",
    ],
  },
  {
    code: "RU",
    name: "Russia",
    region: "Eurasia",
    nuclearStatus: "declared",
    militaryBudgetUsdBillions: 109,
    activeMilitaryPersonnel: 1320000,
    doctrine:
      "Strategic deterrence including nuclear, non-strategic nuclear weapons for 'escalate to de-escalate', long-range precision strike, and reflexive control / information warfare. Updated 2024 nuclear doctrine lowers thresholds.",
    aircraft: [
      "Su-57 Felon stealth fighter (limited)",
      "Su-35S Flanker-E",
      "Su-34 Fullback strike fighter",
      "Su-30SM multirole fighter",
      "MiG-31BM Foxhound interceptor (Kinzhal carrier)",
      "Tu-160 Blackjack strategic bomber",
      "Tu-95MS Bear-H bomber",
      "Tu-22M3 Backfire bomber",
      "Il-78 Midas tanker",
    ],
    missiles: [
      "Kalibr family (3M14, 3M54) cruise missile",
      "Kh-101 / Kh-102 stealth cruise missile",
      "Kh-47M2 Kinzhal air-launched ballistic missile",
      "3M22 Zircon hypersonic cruise missile",
      "Avangard hypersonic glide vehicle",
      "Iskander-M SRBM",
      "S-400 Triumf SAM",
      "S-500 Prometheus SAM (limited)",
      "RS-28 Sarmat heavy ICBM",
      "Bulava SLBM",
    ],
    naval: [
      "Admiral Kuznetsov aircraft carrier (refit)",
      "Kirov-class nuclear battlecruiser (Pyotr Velikiy)",
      "Slava-class cruisers",
      "Borei / Borei-A SSBN",
      "Yasen / Yasen-M SSGN",
      "Akula-class SSN",
      "Project 22350 Admiral Gorshkov frigate",
    ],
    groundForces: [
      "T-90M Proryv MBT",
      "T-80BVM MBT",
      "T-72B3M MBT",
      "BMP-3 IFV",
      "TOS-1A / TOS-2 thermobaric MLRS",
      "VDV airborne troops",
      "Spetsnaz GRU",
    ],
    bases: [
      "Khmeimim Air Base, Syria",
      "Tartus Naval Facility, Syria",
      "Kaliningrad Oblast (exclave)",
      "Severomorsk (Northern Fleet HQ)",
      "Vladivostok (Pacific Fleet HQ)",
      "Sevastopol (Black Sea Fleet HQ, contested)",
    ],
    alliances: [
      "Collective Security Treaty Organization (CSTO)",
      "Union State of Russia and Belarus",
      "China-Russia Comprehensive Strategic Partnership",
      "BRICS+",
    ],
    notableCapabilities: [
      "Largest nuclear stockpile (~5580 warheads)",
      "Operational hypersonic systems (Kinzhal, Avangard, Zircon)",
      "Cyber and information operations (GRU Unit 26165, FSB)",
      "Deep stocks of legacy Soviet armor and artillery",
      "Submarine-launched cruise missile reach across Atlantic and Pacific",
    ],
  },
  {
    code: "GB",
    name: "United Kingdom",
    region: "Europe",
    nuclearStatus: "declared",
    militaryBudgetUsdBillions: 75,
    activeMilitaryPersonnel: 138000,
    doctrine:
      "Continuous-at-sea deterrence (CASD) via Trident SSBNs, expeditionary maritime power, and integrated NATO frontline force. Tilt to Indo-Pacific via AUKUS and CSG21 deployments.",
    aircraft: [
      "Eurofighter Typhoon FGR4",
      "F-35B Lightning II (carrier-based)",
      "P-8A Poseidon MPA",
      "RC-135W Rivet Joint SIGINT",
      "A330 MRTT Voyager tanker",
      "Wedgetail AEW&C (entering service)",
    ],
    missiles: [
      "Storm Shadow / SCALP cruise missile",
      "Meteor BVRAAM",
      "Brimstone 3 air-to-ground missile",
      "Sea Ceptor (CAMM)",
      "Aster 30 (Sea Viper on Type 45)",
      "Trident II D5 SLBM (shared with US)",
      "Spear 3 networked stand-off missile (entering)",
    ],
    naval: [
      "HMS Queen Elizabeth (R08) carrier",
      "HMS Prince of Wales (R09) carrier",
      "Type 45 Daring-class destroyer",
      "Type 23 Duke-class frigate",
      "Type 26 City-class frigate (under construction)",
      "Astute-class SSN",
      "Vanguard-class SSBN",
    ],
    groundForces: [
      "Challenger 2 / Challenger 3 MBT",
      "Ajax armoured reconnaissance vehicle",
      "Boxer mechanised infantry vehicle",
      "16 Air Assault Brigade",
      "3 Commando Brigade Royal Marines",
      "SAS / SBS special forces",
    ],
    bases: [
      "RAF Lossiemouth (QRA North)",
      "RAF Coningsby (QRA South)",
      "RAF Akrotiri, Cyprus",
      "Naval Base Clyde / Faslane (SSBNs)",
      "RAF Mount Pleasant, Falklands",
      "British Forces Gibraltar",
      "Diego Garcia (joint with US)",
    ],
    alliances: [
      "NATO Article 5",
      "Five Eyes",
      "AUKUS",
      "Joint Expeditionary Force (JEF)",
      "Five Power Defence Arrangements (FPDA)",
      "UK-US Special Relationship",
    ],
    notableCapabilities: [
      "Continuous at-sea nuclear deterrent since 1969",
      "Two STOVL fleet carriers with F-35B air wing",
      "Tier-1 SIGINT via GCHQ (Five Eyes)",
      "Global expeditionary logistics",
    ],
  },
  {
    code: "FR",
    name: "France",
    region: "Europe",
    nuclearStatus: "declared",
    militaryBudgetUsdBillions: 56,
    activeMilitaryPersonnel: 203000,
    doctrine:
      "Independent nuclear deterrent (force de dissuasion) with airborne and SLBM legs, strategic autonomy, and overseas force projection across Africa, Middle East, and Indo-Pacific.",
    aircraft: [
      "Rafale B/C/M",
      "Mirage 2000-5 / 2000D",
      "A400M Atlas transport",
      "A330 MRTT Phénix tanker",
      "E-3F AWACS",
      "ATL-2 Atlantique 2 MPA",
    ],
    missiles: [
      "SCALP cruise missile",
      "MICA air-to-air",
      "Meteor BVRAAM",
      "Exocet MM40 Block 3 anti-ship",
      "ASMP-A nuclear-tipped air-launched cruise missile",
      "M51.3 SLBM (TN-75 / TNO warheads)",
      "Aster 15 / Aster 30 SAM",
    ],
    naval: [
      "Charles de Gaulle (R91) nuclear carrier",
      "FREMM / FREMM-DA frigates",
      "Horizon-class air-defence destroyers",
      "Suffren (Barracuda)-class SSN",
      "Triomphant-class SSBN (4 boats)",
      "Mistral-class amphibious assault ship",
    ],
    groundForces: [
      "Leclerc XLR MBT",
      "VBCI infantry fighting vehicle",
      "Jaguar / Griffon Scorpion-program vehicles",
      "Caesar 155mm self-propelled howitzer",
      "1st Marine Infantry Parachute Regiment (1er RPIMa)",
      "Foreign Legion (13e DBLE, 2e REP)",
    ],
    bases: [
      "Base aérienne 113 Saint-Dizier (Rafale, ASMP-A)",
      "Base aérienne 125 Istres (refuelers, ASMP-A)",
      "Île Longue (SSBN base)",
      "Base navale Toulon",
      "Djibouti French Forces (FFDj)",
      "Niamey, Niger (drawing down)",
      "FANC New Caledonia",
      "FAZSOI Réunion / Mayotte",
    ],
    alliances: [
      "NATO Article 5",
      "EU Article 42.7 mutual assistance",
      "Franco-German Brigade",
      "Lancaster House Treaties (with UK)",
      "Quint (US, UK, FR, DE, IT)",
    ],
    notableCapabilities: [
      "Only EU member with nuclear deterrent and CATOBAR carrier",
      "Strategic airlift via A400M fleet",
      "Permanent UNSC seat with veto",
      "Indo-Pacific overseas territories enabling forward presence",
    ],
  },
  {
    code: "DE",
    name: "Germany",
    region: "Europe",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 66,
    activeMilitaryPersonnel: 181000,
    doctrine:
      "NATO collective defence anchor on the eastern flank, Zeitenwende rearmament, host of US B61 nuclear sharing under DCA mission, and lead framework nation for Lithuania brigade.",
    aircraft: [
      "Eurofighter Typhoon",
      "Tornado IDS / ECR (DCA nuclear role)",
      "F-35A Lightning II (replacing Tornado in DCA)",
      "A400M Atlas",
      "P-8A Poseidon (incoming)",
      "Eurodrone (under development)",
    ],
    missiles: [
      "Taurus KEPD 350 cruise missile",
      "IRIS-T SLM / SLS air defense",
      "Patriot PAC-3 MSE",
      "MEADS / Arrow 3 (Arrow 3 procurement)",
      "RBS 15 Mk3 anti-ship",
    ],
    naval: [
      "Baden-Württemberg-class F125 frigate",
      "Sachsen-class F124 air-defence frigate",
      "Brandenburg-class F123 frigate",
      "Type 212A submarine",
      "Type 212CD (ordered, joint with Norway)",
    ],
    groundForces: [
      "Leopard 2A7V MBT",
      "Puma IFV",
      "Boxer wheeled APC",
      "PzH 2000 self-propelled howitzer",
      "Mars II MLRS",
      "Kommando Spezialkräfte (KSK)",
    ],
    bases: [
      "Büchel Air Base (B61 storage)",
      "Wunstorf (A400M)",
      "Ramstein (host to US Air Forces in Europe)",
      "Spangdahlem (host to US 52nd FW)",
      "Rukla Camp, Lithuania (Bundeswehr brigade)",
    ],
    alliances: [
      "NATO Article 5",
      "EU Article 42.7",
      "Franco-German Brigade",
      "European Sky Shield Initiative (ESSI) lead",
    ],
    notableCapabilities: [
      "Dual-Capable Aircraft (DCA) nuclear sharing role",
      "European Sky Shield air-defence framework lead",
      "Largest EU economy backstopping defence procurement",
      "Permanent Bundeswehr brigade in Lithuania",
    ],
  },
  {
    code: "JP",
    name: "Japan",
    region: "East Asia",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 50,
    activeMilitaryPersonnel: 247000,
    doctrine:
      "Self-defence under Article 9 transitioning toward 'counterstrike capability' (2022 NSS), integrated extended deterrence with the US, and Free and Open Indo-Pacific.",
    aircraft: [
      "F-35A / F-35B Lightning II",
      "F-15J / F-15JSI (Super Interceptor)",
      "F-2A/B Viper Zero",
      "P-1 maritime patrol",
      "E-2D Advanced Hawkeye",
      "C-2 transport",
      "KC-46A tanker",
    ],
    missiles: [
      "Type 12 anti-ship missile (extended-range variant)",
      "Tomahawk Block V (US procurement)",
      "Type 03 Chu-SAM",
      "Patriot PAC-3 MSE",
      "SM-3 Block IIA (co-developed with US)",
      "Hyper Velocity Gliding Projectile (HVGP, developmental)",
    ],
    naval: [
      "JS Izumo / JS Kaga (DDH, F-35B conversion)",
      "Maya / Atago-class Aegis destroyers",
      "Kongō-class Aegis destroyers",
      "Mogami-class FFM frigate",
      "Taigei-class SSK",
      "Sōryū-class SSK",
    ],
    groundForces: [
      "Type 10 MBT",
      "Type 16 mobile combat vehicle",
      "Type 19 wheeled SP howitzer",
      "Amphibious Rapid Deployment Brigade (ARDB)",
      "Special Operations Group (SOG)",
    ],
    bases: [
      "Yokosuka Naval Base (US 7th Fleet host)",
      "Yokota Air Base (USFJ HQ)",
      "Kadena Air Base, Okinawa (US)",
      "Iwakuni MCAS",
      "Misawa Air Base",
      "Camp Hansen / Futenma (US Marines)",
    ],
    alliances: [
      "US-Japan Mutual Security Treaty (Article 5 covers Senkaku)",
      "Quad",
      "Reciprocal Access Agreements with UK and Australia",
    ],
    notableCapabilities: [
      "Largest Aegis BMD fleet outside US",
      "STOVL carrier capability returning via Izumo / F-35B",
      "Intelligence sharing under Five-Eyes-adjacent framework",
      "Standoff counterstrike under FY2027 program",
    ],
  },
  {
    code: "IN",
    name: "India",
    region: "South Asia",
    nuclearStatus: "declared",
    militaryBudgetUsdBillions: 81,
    activeMilitaryPersonnel: 1455000,
    doctrine:
      "Credible minimum deterrence with no-first-use (under review), Cold Start conventional doctrine for rapid-response against Pakistan, and two-front planning vs. China and Pakistan.",
    aircraft: [
      "Su-30MKI Flanker-H",
      "Rafale F3R",
      "Tejas Mk1A LCA",
      "MiG-29UPG",
      "Mirage 2000H",
      "P-8I Neptune MPA",
      "C-17A Globemaster III",
      "Phalcon AEW&C",
    ],
    missiles: [
      "BrahMos supersonic cruise missile (extended range)",
      "Nirbhay subsonic cruise missile",
      "Akash medium-range SAM",
      "S-400 Triumf SAM (Russian procurement)",
      "Prithvi-II SRBM",
      "Agni-III / Agni-V IRBM/ICBM",
      "K-15 / K-4 SLBM",
      "BrahMos-NG (under development)",
    ],
    naval: [
      "INS Vikramaditya (R33) carrier",
      "INS Vikrant (IAC-1) carrier",
      "Kolkata-class destroyer",
      "Visakhapatnam-class destroyer",
      "Shivalik-class frigate",
      "Scorpène-class (Kalvari) SSK",
      "Arihant-class SSBN",
      "Akula-class SSN (leased)",
    ],
    groundForces: [
      "T-90S Bhishma MBT",
      "Arjun Mk1A MBT",
      "BMP-2 Sarath IFV",
      "K9 Vajra-T self-propelled howitzer",
      "Pinaka MBRL",
      "Para Special Forces / MARCOS / Garud",
    ],
    bases: [
      "INS Kadamba, Karwar",
      "INS Varsha (SSBN base, under construction)",
      "Andaman & Nicobar Tri-Service Command",
      "Hindon Air Force Station",
      "Thanjavur AFS (Su-30MKI / BrahMos)",
      "Farkhor Air Base, Tajikistan (limited)",
    ],
    alliances: [
      "Quad (US, JP, IN, AU)",
      "India-Russia Strategic Partnership",
      "India-France Strategic Partnership",
      "Indo-Israeli defence cooperation",
      "BRICS+",
    ],
    notableCapabilities: [
      "Triad nuclear deterrent with INS Arihant SSBN",
      "Largest paramilitary forces globally",
      "BrahMos joint cruise missile capability",
      "Indigenous LCA and AMCA fifth-gen development",
    ],
  },
  {
    code: "IL",
    name: "Israel",
    region: "Middle East",
    nuclearStatus: "undeclared",
    militaryBudgetUsdBillions: 24,
    activeMilitaryPersonnel: 170000,
    doctrine:
      "Qualitative Military Edge (QME), preemption, Begin Doctrine (preventing regional adversaries from acquiring nuclear weapons), and layered air defence (Iron Dome / David's Sling / Arrow).",
    aircraft: [
      "F-35I Adir (modified F-35A)",
      "F-15I Ra'am",
      "F-15C/D Baz",
      "F-16I Sufa",
      "AH-64D Apache Longbow",
      "G550 Eitam / Shavit AEW & SIGINT",
      "Heron TP UAV",
    ],
    missiles: [
      "Iron Dome counter-rocket",
      "David's Sling medium-range",
      "Arrow 2 / Arrow 3 anti-ballistic",
      "Spike NLOS / LR2 anti-tank",
      "Popeye / Rampage stand-off air-to-ground",
      "Jericho III IRBM (presumed)",
      "Delilah cruise missile",
    ],
    naval: [
      "Sa'ar 6-class corvette",
      "Sa'ar 5 Eilat-class corvette",
      "Dolphin / Dolphin II-class SSK (cruise-missile-capable)",
    ],
    groundForces: [
      "Merkava Mk4 / Mk5 Barak MBT",
      "Namer heavy IFV/APC",
      "Eitan wheeled APC",
      "Trophy active protection system",
      "Sayeret Matkal / Shayetet 13 / Shaldag SOF",
    ],
    bases: [
      "Nevatim Airbase (F-35I)",
      "Tel Nof Airbase",
      "Ramat David Airbase",
      "Palmachim (space and missile test)",
      "Haifa Naval Base",
      "Ashdod Naval Base",
    ],
    alliances: [
      "US-Israel Strategic Partnership (Major Non-NATO Ally)",
      "Abraham Accords (UAE, Bahrain, Morocco)",
      "Israel-Jordan Peace Treaty (1994)",
      "Egypt-Israel Peace Treaty (1979)",
    ],
    notableCapabilities: [
      "Only nuclear-armed state in Middle East (undeclared)",
      "Cruise-missile-capable Dolphin SSK fleet",
      "Tier-1 SIGINT via Unit 8200",
      "Layered missile defence integrated with US sensors",
      "Demonstrated long-range strike (Iran 2024)",
    ],
  },
  {
    code: "KR",
    name: "South Korea",
    region: "East Asia",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 47,
    activeMilitaryPersonnel: 555000,
    doctrine:
      "Three-Axis system: Kill Chain preemption, Korea Air and Missile Defense (KAMD), and Korea Massive Punishment and Retaliation (KMPR). US extended deterrence under the Washington Declaration (2023).",
    aircraft: [
      "F-35A Lightning II",
      "F-15K Slam Eagle",
      "KF-16C/D Block 50/52",
      "FA-50 Fighting Eagle",
      "KF-21 Boramae (entering service)",
      "E-737 Peace Eye AEW&C",
      "P-8A Poseidon (incoming)",
    ],
    missiles: [
      "Hyunmoo-2 SRBM",
      "Hyunmoo-4 SRBM (heavy warhead)",
      "Hyunmoo-3 cruise missile",
      "Hyunmoo-5 (developmental, super-heavy)",
      "Cheongung-II (KM-SAM Block 2) SAM",
      "L-SAM (developmental)",
      "Patriot PAC-3 MSE",
    ],
    naval: [
      "ROKS Dokdo / ROKS Marado LPH",
      "Sejong the Great-class Aegis destroyer",
      "Chungmugong Yi Sun-sin-class destroyer",
      "Daegu-class FFG",
      "Dosan Ahn Changho-class SSK (KSS-III)",
      "Chang Bogo-class (KSS-I) SSK",
    ],
    groundForces: [
      "K2 Black Panther MBT",
      "K21 IFV",
      "K9 Thunder self-propelled howitzer",
      "Chunmoo MLRS (K239)",
      "ROK Special Warfare Command (UDT/SEAL, 707th)",
    ],
    bases: [
      "Osan Air Base (USFK 7th AF host)",
      "Kunsan Air Base",
      "Camp Humphreys (USFK HQ)",
      "Busan Naval Base",
      "Jeju Naval Base",
      "Seongju THAAD site",
    ],
    alliances: [
      "US-ROK Mutual Defense Treaty (1953)",
      "Combined Forces Command (CFC) with US",
      "Trilateral Camp David framework (US, JP, KR)",
    ],
    notableCapabilities: [
      "Indigenous SLBM-capable KSS-III submarine",
      "K9 self-propelled artillery is top global export",
      "KF-21 fifth-generation fighter program",
      "Massive Punishment and Retaliation conventional strike option",
    ],
  },
];
