import type { CountryProfile } from "./types";

export const countriesE: CountryProfile[] = [
  {
    code: "NZ",
    name: "New Zealand",
    region: "Oceania",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 3,
    activeMilitaryPersonnel: 9000,
    doctrine:
      "Five Eyes intelligence partner, Pacific Islands maritime security, ANZAC integration, nuclear-free zone (NZNFA 1987).",
    aircraft: [
      "P-8A Poseidon MPA",
      "C-130J-30 Super Hercules",
      "NH90 multi-role",
      "T-6C Texan II",
    ],
    missiles: ["AIM-9X Sidewinder", "Maverick", "Hellfire"],
    naval: [
      "Anzac-class FFG (HMNZS Te Kaha, Te Mana)",
      "HMNZS Aotearoa (replenishment)",
      "Otago-class OPV",
    ],
    groundForces: [
      "LAV III (NZLAV)",
      "Bushmaster PMV",
      "L119 light gun",
      "NZ Special Air Service",
    ],
    bases: [
      "RNZAF Whenuapai",
      "RNZAF Ohakea",
      "Devonport Naval Base",
      "Waiouru Army Camp",
    ],
    alliances: [
      "ANZUS (US relationship limited since 1986)",
      "Five Eyes",
      "Five Power Defence Arrangements",
    ],
    notableCapabilities: [
      "Tier-1 SIGINT via GCSB (Five Eyes)",
      "P-8A maritime patrol over Southern Pacific",
      "Statutory nuclear-free zone",
    ],
  },
  {
    code: "CH",
    name: "Switzerland",
    region: "Europe",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 6,
    activeMilitaryPersonnel: 21000,
    doctrine:
      "Armed neutrality, militia army (~140k mobilizable), homeland defence, Alpine fortifications.",
    aircraft: [
      "F/A-18C/D Hornet (replacement F-35A 2027+)",
      "F-5E/F Tiger II (training)",
      "F-35A Lightning II (procurement)",
    ],
    missiles: [
      "AIM-120 AMRAAM",
      "AIM-9X",
      "Patriot PAC-3 MSE (procurement)",
      "Stinger / RAPIER",
    ],
    naval: [],
    groundForces: [
      "Pz 87 Leopard 2 MBT",
      "CV9030CH IFV",
      "Mowag Piranha",
      "M109 KAWEST",
      "Army Reconnaissance Detachment 10 (AAD 10)",
    ],
    bases: [
      "Payerne Air Base",
      "Meiringen Air Base (cavern)",
      "Emmen Air Base",
      "Various Alpine fortresses",
    ],
    alliances: ["Neutrality (no formal alliance)"],
    notableCapabilities: [
      "Alpine cavern airbases (Meiringen, Buochs)",
      "Universal male conscription, militia structure",
      "Permanent neutrality under 1815 Treaty of Paris",
    ],
  },
  {
    code: "AT",
    name: "Austria",
    region: "Europe",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 4,
    activeMilitaryPersonnel: 22000,
    doctrine:
      "Constitutional neutrality (1955 State Treaty), homeland defence, EU CSDP contributor, peacekeeping (UNDOF, EUFOR Althea).",
    aircraft: [
      "Eurofighter Typhoon Tranche 1",
      "Saab 105 OE (retired)",
      "PC-7 trainer",
      "Black Hawk S-70A-42",
    ],
    missiles: ["IRIS-T (procurement)", "Mistral 3", "RBS 15"],
    naval: [],
    groundForces: [
      "Leopard 2A4 MBT",
      "Ulan IFV",
      "Pandur II 6x6",
      "M109A5 SP howitzer",
      "Jagdkommando special forces",
    ],
    bases: [
      "Hörsching Air Base",
      "Zeltweg Air Base",
      "Wiener Neustadt",
    ],
    alliances: [
      "EU Article 42.7 (neutral participation)",
      "European Sky Shield Initiative",
    ],
    notableCapabilities: [
      "Permanent neutrality under State Treaty 1955",
      "Eurofighter Typhoon force",
      "UNDOF and Althea peacekeeping",
    ],
  },
  {
    code: "CZ",
    name: "Czech Republic",
    region: "Europe",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 5,
    activeMilitaryPersonnel: 27000,
    doctrine:
      "NATO collective defence, V4 cooperation, donor of legacy Soviet equipment to Ukraine, F-35 procurement underway.",
    aircraft: [
      "JAS 39C/D Gripen (leased)",
      "L-159 ALCA",
      "F-35A Lightning II (procurement)",
      "C-295M",
    ],
    missiles: [
      "AIM-120C AMRAAM",
      "AIM-9X",
      "RBS-70",
      "Spyder (procurement)",
    ],
    naval: [],
    groundForces: [
      "Leopard 2A4 (donations from Germany)",
      "T-72M4CZ (legacy)",
      "Pandur II 8x8",
      "CV90 MkIV (procurement)",
      "601st Special Forces Group",
    ],
    bases: [
      "Čáslav Air Base (Gripen)",
      "Náměšť Air Base (helicopters)",
      "Vyškov training area",
    ],
    alliances: [
      "NATO Article 5",
      "EU Article 42.7",
      "Visegrád Group (V4)",
    ],
    notableCapabilities: [
      "Major arms donor to Ukraine (T-72, BMP-1, MiG-21)",
      "NATO CBRN Joint Centre of Excellence (Vyškov)",
      "Indigenous L-39NG / L-159 trainer/light combat aircraft",
    ],
  },
  {
    code: "HU",
    name: "Hungary",
    region: "Europe",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 3,
    activeMilitaryPersonnel: 38000,
    doctrine:
      "Zrínyi 2026 modernisation program, NATO collective defence with reservations on Ukraine support, regional power posture.",
    aircraft: [
      "JAS 39C/D Gripen (leased)",
      "L-39 Albatros (trainer)",
      "H145M / H225M",
      "C-390 Millennium",
    ],
    missiles: ["AIM-120 AMRAAM", "Mistral 2", "NASAMS"],
    naval: [],
    groundForces: [
      "Leopard 2A7HU MBT",
      "Lynx KF41 IFV (Rheinmetall, jointly produced)",
      "PzH 2000 SP howitzer",
      "Hunor 36 special forces",
    ],
    bases: [
      "Kecskemét Air Base (Gripen)",
      "Pápa Air Base (NATO C-17 SAC)",
      "Szolnok",
    ],
    alliances: [
      "NATO Article 5",
      "EU Article 42.7",
      "Visegrád Group",
    ],
    notableCapabilities: [
      "Hosts NATO Strategic Airlift Capability (SAC) at Pápa",
      "Lynx IFV co-production with Rheinmetall (Zalaegerszeg)",
      "Joint NATO/Hungarian C-17 Globemaster wing",
    ],
  },
  {
    code: "RO",
    name: "Romania",
    region: "Europe",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 8,
    activeMilitaryPersonnel: 81000,
    doctrine:
      "NATO Black Sea anchor, hosts Aegis Ashore Deveselu, F-35A and HIMARS procurement, frontline deterrence vs. Russia.",
    aircraft: [
      "F-16AM/BM (ex-Norway/Portugal)",
      "F-35A Lightning II (procurement)",
      "MiG-21 LanceR (retired)",
      "C-27J Spartan",
      "IAR 330 Puma",
    ],
    missiles: [
      "AIM-120 AMRAAM",
      "Patriot PAC-3 MSE",
      "HIMARS / GMLRS",
      "NASAMS",
    ],
    naval: [
      "Mărăşeşti-class FFG",
      "Type 22 Regele Ferdinand-class FFG (ex-RN)",
      "Tarantul-class corvette",
    ],
    groundForces: [
      "TR-85M1 MBT (replacement Abrams M1A2 SEPv3)",
      "M1A2 SEPv3 Abrams (procurement)",
      "Piranha 5",
      "ATMOS 2000 SP howitzer",
      "Brigada 6 OPS",
    ],
    bases: [
      "Mihail Kogălniceanu Air Base (US rotational hub)",
      "Câmpia Turzii Air Base",
      "Deveselu Aegis Ashore site",
      "Constanța Naval Base",
    ],
    alliances: [
      "NATO Article 5",
      "EU Article 42.7",
      "Bucharest Nine (B9)",
    ],
    notableCapabilities: [
      "Hosts Aegis Ashore at Deveselu",
      "M.K. Air Base expanding to NATO largest in Europe",
      "Frontline Black Sea posture",
    ],
  },
  {
    code: "PT",
    name: "Portugal",
    region: "Europe",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 5,
    activeMilitaryPersonnel: 27000,
    doctrine:
      "NATO Atlantic guard (Lajes Field), CSDP contributor, expeditionary peacekeeping, lusophone defence cooperation.",
    aircraft: [
      "F-16AM/BM Fighting Falcon",
      "P-3C CUP+ Orion MPA",
      "C-130H Hercules",
      "C-295M",
      "KC-390 (procurement)",
    ],
    missiles: ["AIM-120 AMRAAM", "AIM-9X", "Mistral"],
    naval: [
      "Vasco da Gama-class FFG (Meko 200)",
      "Bartolomeu Dias-class FFG (ex-Karel Doorman)",
      "Tridente-class (Type 209/PN) SSK",
    ],
    groundForces: [
      "Leopard 2A6 MBT",
      "M113A2 / M577",
      "Pandur II 8x8",
      "M119A2 howitzer",
      "Special Operations Centre (CTOE)",
    ],
    bases: [
      "Lajes Field, Azores (joint US/PT)",
      "Monte Real Air Base (F-16)",
      "Lisbon Naval Base / Alfeite",
      "Madeira",
    ],
    alliances: [
      "NATO Article 5 (founding member)",
      "EU Article 42.7",
    ],
    notableCapabilities: [
      "Lajes Field Atlantic transit hub",
      "Atlantic SAR coverage",
      "Lusophone defence partnerships (Brazil, Angola, Mozambique)",
    ],
  },
  {
    code: "IE",
    name: "Ireland",
    region: "Europe",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 1.5,
    activeMilitaryPersonnel: 8000,
    doctrine:
      "Constitutional neutrality (Triple Lock for deployment), UN peacekeeping, EU CSDP, no NATO membership.",
    aircraft: [
      "PC-9M / PC-12NG",
      "AW139",
      "Defender 4000 maritime patrol (legacy)",
      "C-295 (procurement)",
    ],
    missiles: ["RBS 70 NG"],
    naval: [
      "Samuel Beckett-class OPV",
      "Eithne / Roisin (legacy)",
    ],
    groundForces: [
      "MOWAG Piranha III H 8x8",
      "AML / FV101 Scorpion (legacy)",
      "Army Ranger Wing (ARW)",
    ],
    bases: [
      "Casement Aerodrome, Baldonnel",
      "Cathal Brugha Barracks, Dublin",
      "Naval Base Haulbowline, Cork",
    ],
    alliances: [
      "EU Article 42.7 (with neutrality reservations)",
      "Partnership for Peace (NATO PfP)",
    ],
    notableCapabilities: [
      "Constitutional neutrality (Triple Lock: government, Dáil, UN)",
      "Long UN peacekeeping tradition (Lebanon, Mali, Golan)",
      "Rapid air policing arrangement with UK (informal)",
    ],
  },
  {
    code: "MY",
    name: "Malaysia",
    region: "Southeast Asia",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 4,
    activeMilitaryPersonnel: 113000,
    doctrine:
      "Defence of sovereignty, FPDA partner, balancing China and US, ASEAN centrality, counter-piracy in Strait of Malacca.",
    aircraft: [
      "Su-30MKM Flanker-H",
      "F/A-18D Hornet",
      "MB-339CM",
      "FA-50 Block 20 (procurement)",
      "CN-235 MPA",
    ],
    missiles: [
      "AIM-120 AMRAAM",
      "Kh-31 / R-77",
      "Exocet MM40 Block 2",
      "Jernas (Rapier)",
      "Starstreak",
    ],
    naval: [
      "Lekiu-class FFG",
      "Kasturi-class corvette",
      "Maharajalela-class LCS (delayed)",
      "Scorpène (Tunku Abdul Rahman-class) SSK",
    ],
    groundForces: [
      "PT-91M Pendekar MBT",
      "ACV-15 / AV-8 Gempita 8x8",
      "Astros II MLRS",
      "PASKAL (naval) / Grup Gerak Khas (army) SOF",
    ],
    bases: [
      "Subang Air Base",
      "Butterworth Air Base (FPDA IADS)",
      "Lumut Naval Base",
      "Sandakan, Sabah (eastern flank)",
    ],
    alliances: [
      "Five Power Defence Arrangements",
      "ASEAN",
    ],
    notableCapabilities: [
      "Strait of Malacca chokepoint sovereignty",
      "Mixed Russian/Western/Korean fleet",
      "Hosts FPDA Integrated Air Defence System HQ at Butterworth",
    ],
  },
  {
    code: "PH",
    name: "Philippines",
    region: "Southeast Asia",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 4,
    activeMilitaryPersonnel: 144000,
    doctrine:
      "Self-Reliant Defense Posture, archipelagic defence, US Mutual Defense Treaty (1951), counter-China gray-zone in West Philippine Sea, EDCA expansion (9 sites).",
    aircraft: [
      "FA-50PH",
      "F-16C/D (announced procurement)",
      "C-130T/H Hercules",
      "S-70i Black Hawk",
      "T129 ATAK",
    ],
    missiles: [
      "BrahMos shore-based anti-ship (operational, first export)",
      "Spike NLOS",
      "AIM-9 Sidewinder",
      "JDAM",
    ],
    naval: [
      "Jose Rizal-class FFG",
      "Miguel Malvar-class corvette (incoming)",
      "Tarlac-class SSV (LPD)",
      "Conrado Yap-class corvette (ex-Pohang)",
    ],
    groundForces: [
      "Sabra Mk2 (ex-Israeli M60A3 upgrade)",
      "ACV-300 / Cobra II",
      "ATMOS 2000 SP howitzer",
      "Light Reaction Regiment / Naval Special Operations Command",
    ],
    bases: [
      "EDCA Sites: Antonio Bautista AB (Palawan), Basa AB, Fort Magsaysay, Lumbia AB, Benito Ebuen AB, Camilo Osias Naval Base, Lal-lo Airport, Camp Melchor Dela Cruz, Balabac Island",
      "Subic Bay Freeport (US naval access)",
      "Clark Air Base (rotational US use)",
    ],
    alliances: [
      "US-Philippines Mutual Defense Treaty (1951)",
      "Major Non-NATO Ally",
      "Squad (US, JP, AU, PH)",
      "ASEAN",
    ],
    notableCapabilities: [
      "First foreign export customer of BrahMos",
      "Nine EDCA sites with US rotational forces",
      "Strategic chokepoint at Luzon Strait/Bashi Channel",
    ],
  },
];
