import type { CountryProfile } from "./types";

export const countriesF: CountryProfile[] = [
  {
    code: "BY",
    name: "Belarus",
    region: "Europe",
    nuclearStatus: "former",
    militaryBudgetUsdBillions: 1,
    activeMilitaryPersonnel: 48000,
    doctrine:
      "CSTO collective defence; effectively integrated into Russian Western Strategic Direction since 2020-2022 crackdown and forward-deployed Russian Iskander-M and tactical nuclear assets.",
    aircraft: ["Su-30SM", "MiG-29", "Su-25 Frogfoot", "Mi-24 Hind", "Mi-8/17"],
    missiles: ["Iskander-M (Russian forward deployment)", "Polonez MLRS", "Tor-M2", "S-400 / S-300"],
    naval: [],
    groundForces: ["T-72B3 / T-80U", "BMP-2", "BTR-82A", "Polonez MLRS", "Special Operations Forces"],
    bases: ["Baranavichy Air Base", "Maczulszczyzna Air Base", "Asipovichy (Russian tactical nuclear storage)"],
    alliances: ["CSTO", "Union State of Russia and Belarus", "EAEU"],
    notableCapabilities: [
      "Hosts Russian tactical nuclear weapons (since 2023)",
      "Iskander-M forward deployment threatens Suwałki Gap",
      "Geographic position frontline against NATO eastern flank",
    ],
  },
  {
    code: "KZ",
    name: "Kazakhstan",
    region: "Central Asia",
    nuclearStatus: "former",
    militaryBudgetUsdBillions: 2,
    activeMilitaryPersonnel: 48000,
    doctrine:
      "Multi-vector foreign policy balancing Russia, China, Türkiye, and the West; CSTO member but increasing military diversification post-2022.",
    aircraft: ["Su-30SM", "MiG-31", "Su-27", "Su-25 Frogfoot"],
    missiles: ["S-300", "Buk", "Tor-M2"],
    naval: ["Kazakhstan Naval Forces (Caspian)", "Sayasat-class missile boats"],
    groundForces: ["T-72BA", "BMP-2", "BTR-80A"],
    bases: ["Aktau Naval Base (Caspian)", "Almaty AB", "Baikonur Cosmodrome (leased to Russia)"],
    alliances: ["CSTO", "SCO", "Eurasian Economic Union"],
    notableCapabilities: [
      "Largest Caspian Sea naval force",
      "Voluntarily denuclearized 1993-95 (Lisbon Protocol)",
      "Hosts Russian Baikonur Cosmodrome under long-term lease",
    ],
  },
  {
    code: "UZ",
    name: "Uzbekistan",
    region: "Central Asia",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 1.5,
    activeMilitaryPersonnel: 48000,
    doctrine:
      "Strict non-alignment outside CSTO; balance Russia, China, US presence in Afghanistan footprint.",
    aircraft: ["Su-27", "MiG-29", "Su-25"],
    missiles: ["Scud-B (legacy)", "S-200 / S-125"],
    naval: [],
    groundForces: ["T-72B", "BMP-2", "BTR-80"],
    bases: ["Tashkent AB", "Karshi-Khanabad (US-leased 2001-2005)"],
    alliances: ["SCO", "CIS"],
    notableCapabilities: [
      "Largest military in Central Asia by personnel",
      "Strategically located on Amu Darya / Afghan border",
    ],
  },
  {
    code: "NG",
    name: "Nigeria",
    region: "Africa",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 3,
    activeMilitaryPersonnel: 230000,
    doctrine:
      "Counter-Boko Haram / ISWAP, anti-piracy in Gulf of Guinea, ECOWAS leadership.",
    aircraft: ["JF-17 Block II", "F-7NI", "L-39 Albatros", "A-29 Super Tucano", "Mi-35M"],
    missiles: ["AIM-9 / PL-5"],
    naval: ["NNS Centenary (P18N Chinese-built FFG)", "NNS Aradu", "Hamilton-class (ex-USCG cutters)"],
    groundForces: ["T-72NG", "Vickers Mk3", "Otokar Cobra", "Streit Spartan MRAP"],
    bases: ["Abuja AB", "Kainji AB", "Apapa Naval Base, Lagos"],
    alliances: ["ECOWAS", "African Union"],
    notableCapabilities: [
      "Largest military in West Africa",
      "Multinational Joint Task Force lead vs. Boko Haram (Lake Chad)",
      "JF-17 procurement marks China-Pakistan defense linkage",
    ],
  },
  {
    code: "DZ",
    name: "Algeria",
    region: "North Africa",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 22,
    activeMilitaryPersonnel: 130000,
    doctrine:
      "Defensive against Morocco; large indigenous and Russian-supplied arsenal; non-alignment.",
    aircraft: ["Su-30MKA", "Su-24M2 Fencer", "MiG-29M/M2", "Yak-130"],
    missiles: ["Iskander-E", "S-400 Triumf", "Pantsir-S1", "Kh-31 / Kh-59"],
    naval: ["Project 1159TR Frigate", "MEKO A-200AN frigate", "Kilo-class (Project 636) SSK"],
    groundForces: ["T-90SA", "T-72B", "BMP-2M", "BMPT-72 Terminator"],
    bases: ["Boufarik AB", "Tindouf Airbase", "Mers el-Kébir Naval Base"],
    alliances: ["Arab League (suspended)", "Non-Aligned Movement"],
    notableCapabilities: [
      "Most capable air defence in MENA outside Israel",
      "Largest Russian arms client in Africa",
      "Algerian-French rapprochement on counter-terror in Sahel",
    ],
  },
  {
    code: "MA",
    name: "Morocco",
    region: "North Africa",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 6,
    activeMilitaryPersonnel: 196000,
    doctrine:
      "Defensive against Algeria; Western Sahara security; close US/French/Israeli partnerships.",
    aircraft: ["F-16C/D Block 52", "F-5E Tiger II", "Mirage F1", "AH-64E Apache"],
    missiles: ["AIM-120C AMRAAM", "Patriot PAC-3 (procurement)", "Spike NLOS"],
    naval: ["Mohammed VI-class FFG (FREMM-derived)", "SIGMA-class FFG", "Floréal-class"],
    groundForces: ["M1A1 SA Abrams (procurement)", "VT-1A MBT", "M60A3 TTS", "VAB"],
    bases: ["Sidi Slimane AB", "Kénitra AB", "Casablanca Naval Base"],
    alliances: ["Major Non-NATO Ally of US", "Arab League", "African Union"],
    notableCapabilities: [
      "M1A2 SEPv3 Abrams procurement underway",
      "Israeli intelligence cooperation since 2020 normalization",
      "Largest African F-16 fleet",
    ],
  },
  {
    code: "ET",
    name: "Ethiopia",
    region: "Africa",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 1,
    activeMilitaryPersonnel: 162000,
    doctrine:
      "Post-civil-war reconstitution; African Union peacekeeping leader; counter-terror in Somalia.",
    aircraft: ["Su-27", "MiG-23BN", "Mi-24", "L-39 Albatros"],
    missiles: ["S-125 Pechora-2M"],
    naval: ["Ethiopian Naval Force (re-established 2018)"],
    groundForces: ["T-72UA1", "T-62", "BMP-1", "ZSU-23-4 Shilka"],
    bases: ["Debre Zeit AB", "Bishoftu", "Harar Meda"],
    alliances: ["African Union (HQ in Addis Ababa)"],
    notableCapabilities: [
      "African Union HQ in Addis Ababa",
      "Largest peacekeeping contributor in Africa",
      "Re-establishing naval forces with French support",
    ],
  },
  {
    code: "KE",
    name: "Kenya",
    region: "Africa",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 1.2,
    activeMilitaryPersonnel: 24000,
    doctrine:
      "Counter-Al-Shabaab; East African Community lead; security partnerships with US and UK.",
    aircraft: ["F-5E Tiger II", "Hawk Mk52", "Tucano Mk51", "MD500 Defender"],
    missiles: ["Starstreak MANPADS"],
    naval: ["Jasiri-class corvette"],
    groundForces: ["T-72AV", "Vickers Mk3", "Bastion APC"],
    bases: ["Manda Bay (joint with US)", "Laikipia AB", "Mombasa Naval Base"],
    alliances: ["East African Community", "African Union"],
    notableCapabilities: [
      "Hosts US Camp Simba (Manda Bay) ISR operations",
      "AU mission in Somalia (ATMIS) lead contributor",
    ],
  },
  {
    code: "AO",
    name: "Angola",
    region: "Africa",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 2,
    activeMilitaryPersonnel: 107000,
    doctrine:
      "Post-civil-war modernization; SADC contributor; Russian and Brazilian procurement diversification.",
    aircraft: ["Su-30K", "Su-22 Fitter", "MiG-21bis", "Mi-35"],
    missiles: ["S-300V (limited)", "Pantsir-S1"],
    naval: ["Macuti-class", "Mandume-class"],
    groundForces: ["T-72B", "T-55", "BMP-2"],
    bases: ["Cabinda AB", "Luanda Naval Base"],
    alliances: ["SADC", "African Union"],
    notableCapabilities: [
      "Largest Lusophone African military",
      "Significant Russian and Brazilian arms procurement",
    ],
  },
  {
    code: "NZ",
    name: "Nepal",
    region: "South Asia",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 0.4,
    activeMilitaryPersonnel: 96000,
    doctrine:
      "Strict non-alignment; UN peacekeeping major contributor; Gurkha military tradition.",
    aircraft: ["AS332 Super Puma", "Mi-17", "Bell 206"],
    missiles: [],
    naval: [],
    groundForces: ["T-55", "T-69", "WMA-301 (Chinese)"],
    bases: ["Tribhuvan AB"],
    alliances: ["Non-Aligned Movement"],
    notableCapabilities: [
      "Nepali Gurkha soldiers serve in UK and Indian armies",
      "Top per-capita UN peacekeeping contributor",
    ],
  },
  {
    code: "BD",
    name: "Bangladesh",
    region: "South Asia",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 4,
    activeMilitaryPersonnel: 165000,
    doctrine:
      "Forces Goal 2030 modernization; UN peacekeeping leader; balancing India and China procurement.",
    aircraft: ["F-7BG/BGI", "MiG-29B", "Yak-130 (procurement)", "K-8W trainer"],
    missiles: ["FM-90", "C-704 anti-ship"],
    naval: ["BNS Bangabandhu (FFG)", "Type 053H3 Padma-class FFG", "Ming-class (Type 035) SSK"],
    groundForces: ["MBT-2000 (Al-Khalid)", "Type 69-IIG", "BTR-80"],
    bases: ["Chittagong Naval Base", "Kurmitola AB", "BNS Sheikh Hasina (submarine base under construction)"],
    alliances: ["BIMSTEC", "Non-Aligned Movement"],
    notableCapabilities: [
      "Top UN peacekeeping contributor globally",
      "First Bay of Bengal littoral state with submarines",
      "Mixed Chinese/Russian procurement portfolio",
    ],
  },
  {
    code: "LK",
    name: "Sri Lanka",
    region: "South Asia",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 1.5,
    activeMilitaryPersonnel: 255000,
    doctrine:
      "Post-civil-war (LTTE defeated 2009); Indian Ocean balancing between India and China; Hambantota port concerns.",
    aircraft: ["Kfir C2/C7 (retiring)", "MiG-27 (retired)", "F-7BS"],
    missiles: [],
    naval: ["SLNS Gajabahu (ex-USCGC Sherman)", "Sayura-class OPV"],
    groundForces: ["T-55", "Type 69 MBT", "BMP-1", "Buffel APC"],
    bases: ["SLNS Dakshina, Galle", "SLAF Katunayake"],
    alliances: ["BIMSTEC", "Non-Aligned Movement"],
    notableCapabilities: [
      "Hambantota Port leased to China (99-year)",
      "Strategic Indian Ocean SLOC location",
    ],
  },
  {
    code: "MM",
    name: "Myanmar",
    region: "Southeast Asia",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 2,
    activeMilitaryPersonnel: 350000,
    doctrine:
      "Junta consolidation since 2021 coup; counterinsurgency vs. ethnic armed organizations; Russian and Chinese arms.",
    aircraft: ["Su-30SME", "MiG-29B", "JF-17 Block II", "Yak-130"],
    missiles: ["S-125 Pechora-2M", "Pantsir-S1"],
    naval: ["UMS Kyan Sittha (FFG)", "UMS Aung Zeya"],
    groundForces: ["T-72S", "Type 90-II", "MBT-2000", "BTR-3U"],
    bases: ["Naypyitaw AB", "Sittwe Naval Base"],
    alliances: ["ASEAN (suspended high-level)"],
    notableCapabilities: [
      "Long counterinsurgency experience",
      "Significant Russian and Chinese arms procurement",
      "Subject to extensive Western sanctions since 2021 coup",
    ],
  },
  {
    code: "KH",
    name: "Cambodia",
    region: "Southeast Asia",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 0.6,
    activeMilitaryPersonnel: 124000,
    doctrine:
      "Close alignment with China; possible PLA Navy access at Ream Naval Base.",
    aircraft: ["L-39 Albatros", "Mi-17", "Z-9C"],
    missiles: ["FN-6 MANPADS"],
    naval: ["Stenka-class patrol boat", "Type 062 (Chinese)"],
    groundForces: ["T-55", "Type 59", "BTR-60"],
    bases: ["Ream Naval Base (Chinese expansion)", "Phnom Penh AB"],
    alliances: ["ASEAN"],
    notableCapabilities: [
      "Ream Naval Base hosts PLA Navy presence (per US/IND assessments)",
      "Major Chinese economic and security partner",
    ],
  },
  {
    code: "CL",
    name: "Chile",
    region: "South America",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 6,
    activeMilitaryPersonnel: 77000,
    doctrine:
      "Constitutional defence; Pacific maritime focus; one of South America's most professional militaries.",
    aircraft: ["F-16C/D Block 50", "F-5III Tiger III"],
    missiles: ["AIM-120C", "AGM-65 Maverick", "Crotale", "Spyder"],
    naval: ["Almirante Williams-class (ex-Type 23)", "Adelaide-class FFG (ex-RAN)", "Scorpène-class SSK"],
    groundForces: ["Leopard 2A4", "M-109A5+ SP howitzer", "Marder 1A3"],
    bases: ["Valparaíso Naval Base", "Punta Arenas (Antarctic gateway)", "Pudahuel AB"],
    alliances: ["Rio Treaty"],
    notableCapabilities: [
      "Pacific Alliance member",
      "Antarctic territorial claim and operations",
    ],
  },
  {
    code: "CO",
    name: "Colombia",
    region: "South America",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 11,
    activeMilitaryPersonnel: 295000,
    doctrine:
      "Counter-narcotics, counter-FARC dissidents, ELN, GAOs; longstanding US Plan Colombia partnership.",
    aircraft: ["IAI Kfir COA", "AT-29B Super Tucano", "AC-47T 'Fantasma'", "UH-60 Black Hawk"],
    missiles: ["AIM-120 AMRAAM"],
    naval: ["ARC Almirante Padilla-class FFG", "Type 209/1200 SSK"],
    groundForces: ["EE-9 Cascavel", "RG-31 MRAP", "M113 / M114"],
    bases: ["Tolemaida AB", "Cartagena Naval Base", "Palanquero AB"],
    alliances: ["Major Non-NATO Ally of US (since 2022)", "NATO Global Partner"],
    notableCapabilities: [
      "First Latin American Major Non-NATO Ally",
      "Most US-trained military in Latin America",
      "Counter-narcotic interdiction expertise",
    ],
  },
  {
    code: "PE",
    name: "Peru",
    region: "South America",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 2.5,
    activeMilitaryPersonnel: 100000,
    doctrine:
      "Defence of national territory; counter-Sendero remnants; mixed US-Russian-Korean procurement.",
    aircraft: ["MiG-29SE", "Su-25", "Mirage 2000P (retired)", "FA-50 Fighting Eagle (procurement)"],
    missiles: ["Igla-S MANPADS"],
    naval: ["BAP Almirante Grau (retired)", "Lupo-class FFG", "Type 209/1200 SSK"],
    groundForces: ["T-55", "AMX-13", "BTR-80"],
    bases: ["Las Palmas AB", "Callao Naval Base"],
    alliances: ["Rio Treaty"],
    notableCapabilities: [
      "Largest air force in South America by combat aircraft",
      "Korean K9 howitzer procurement underway",
    ],
  },
  {
    code: "VE",
    name: "Venezuela",
    region: "South America",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 1,
    activeMilitaryPersonnel: 161000,
    doctrine:
      "Bolivarian doctrine; Russian and Chinese procurement; territorial claim on Guyana's Essequibo.",
    aircraft: ["Su-30MK2V", "F-16A/B (1980s)", "K-8W Karakorum"],
    missiles: ["S-300VM", "Buk-M2E", "Pechora-2M"],
    naval: ["Lupo-class FFG (Mariscal Sucre)", "Constitución-class FAC"],
    groundForces: ["T-72B1V", "BMP-3M", "BTR-80A", "Smerch MLRS"],
    bases: ["Caracas AB", "La Carlota AB", "Puerto Cabello Naval Base"],
    alliances: ["ALBA", "Bolivarian Alliance"],
    notableCapabilities: [
      "Most modern Russian-supplied air defence in Latin America",
      "Active Essequibo annexation effort vs. Guyana",
    ],
  },
  {
    code: "EC",
    name: "Ecuador",
    region: "South America",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 2,
    activeMilitaryPersonnel: 39000,
    doctrine:
      "Internal security focus following 2024 'internal armed conflict' declaration vs. drug cartels; territorial defence in Amazon and Pacific approaches.",
    aircraft: ["Cheetah C/D", "A-29 Super Tucano", "Mirage 2000P (Peruvian sale, declined)"],
    missiles: [],
    naval: ["Eloy Alfaro-class FFG (ex-Leander)", "Esmeraldas-class corvette"],
    groundForces: ["T-55", "AMX-13", "EE-9 Cascavel"],
    bases: ["Salinas AB", "Manta AB (former US FOL)"],
    alliances: ["Rio Treaty"],
    notableCapabilities: [
      "Hosts new US Maritime Security Cooperation",
      "Internal armed conflict status against organized crime",
    ],
  },
  {
    code: "FJ",
    name: "Fiji",
    region: "Oceania",
    nuclearStatus: "none",
    militaryBudgetUsdBillions: 0.1,
    activeMilitaryPersonnel: 4000,
    doctrine:
      "UN peacekeeping focus; balancing US, Australia, and PRC influence in the Pacific.",
    aircraft: [],
    missiles: [],
    naval: ["RFNS Savenaca (Guardian-class patrol boat, AU-donated)"],
    groundForces: ["RFMF Land Force"],
    bases: ["RFMF Nabua Camp"],
    alliances: ["Pacific Islands Forum", "Commonwealth"],
    notableCapabilities: [
      "Highest UN peacekeeping deployment per capita globally",
      "Strategic location in central Pacific",
    ],
  },
];
