import type { SofUnit } from "./types";

export const SOF_UNITS: SofUnit[] = [
  // ============ United States ============
  {
    slug: "us-delta-force",
    name: "1st Special Forces Operational Detachment-Delta",
    countryCode: "US",
    parentService: "US Army",
    type: "tier_1",
    foundedYear: 1977,
    estimatedStrength: 1200,
    homeBase: "Fort Liberty (Bragg), North Carolina",
    role: "Tier-1 hostage rescue, direct action, counterterrorism, special reconnaissance.",
    notableOperations: [
      "Operation Acid Gambit (Panama 1989)",
      "Operation Gothic Serpent (Mogadishu 1993)",
      "Operation Neptune Spear support (2011)",
      "ISIS leadership raids (Syria/Iraq 2014-2019)",
    ],
  },
  {
    slug: "us-devgru",
    name: "Naval Special Warfare Development Group (DEVGRU / SEAL Team Six)",
    countryCode: "US",
    parentService: "US Navy",
    type: "tier_1",
    foundedYear: 1980,
    estimatedStrength: 1500,
    homeBase: "Dam Neck Annex, Virginia Beach",
    role: "Tier-1 maritime counterterrorism, hostage rescue, direct action, special reconnaissance.",
    notableOperations: [
      "Operation Neptune Spear (Abbottabad 2011)",
      "Maersk Alabama rescue 2009",
    ],
  },
  {
    slug: "us-rangers",
    name: "75th Ranger Regiment",
    countryCode: "US",
    parentService: "US Army",
    type: "ranger",
    foundedYear: 1974,
    estimatedStrength: 3500,
    homeBase: "Fort Moore, Georgia",
    role: "Direct action, airfield seizure, raids, special reconnaissance; large-unit special operations.",
    notableOperations: [
      "Battle of Mogadishu 1993",
      "Bagram airfield seizure 2001",
      "Continuous raid operations 2001-2021",
    ],
  },
  {
    slug: "us-green-berets",
    name: "United States Army Special Forces (Green Berets)",
    countryCode: "US",
    parentService: "US Army",
    type: "tier_2",
    foundedYear: 1952,
    estimatedStrength: 7000,
    homeBase: "Fort Liberty, North Carolina",
    role: "Unconventional warfare, foreign internal defense, special reconnaissance, direct action, counterterrorism.",
    notableOperations: [
      "Vietnam War unconventional warfare",
      "Northern Alliance liaison Afghanistan 2001",
      "Syrian Democratic Forces enabling 2014-present",
      "Ukrainian SOF training 2015-present",
    ],
  },
  {
    slug: "us-marsoc",
    name: "Marine Forces Special Operations Command (MARSOC / Raiders)",
    countryCode: "US",
    parentService: "US Marine Corps",
    type: "tier_2",
    foundedYear: 2006,
    estimatedStrength: 3000,
    homeBase: "Camp Lejeune, North Carolina",
    role: "Direct action, special reconnaissance, foreign internal defense.",
  },
  {
    slug: "us-160-soar",
    name: "160th Special Operations Aviation Regiment (Night Stalkers)",
    countryCode: "US",
    parentService: "US Army",
    type: "tier_1",
    foundedYear: 1981,
    estimatedStrength: 2500,
    homeBase: "Fort Campbell, Kentucky",
    role: "Special operations aviation; rotary-wing insertion/extraction for Tier-1 missions.",
    notableOperations: [
      "Operation Eagle Claw recovery and reorganization",
      "Operation Neptune Spear insertion (2011)",
    ],
  },
  {
    slug: "us-afsoc-24sts",
    name: "24th Special Tactics Squadron",
    countryCode: "US",
    parentService: "US Air Force",
    type: "tier_1",
    homeBase: "Pope Field, North Carolina",
    role: "Tier-1 air-ground integration: combat control, pararescue, special reconnaissance.",
  },
  {
    slug: "us-afsoc",
    name: "Air Force Special Operations Command (AFSOC)",
    countryCode: "US",
    parentService: "US Air Force",
    type: "tier_2",
    foundedYear: 1990,
    homeBase: "Hurlburt Field, Florida",
    role: "Special operations aviation: AC-130J Ghostrider, MC-130J Commando II, CV-22 Osprey, U-28A Draco.",
  },
  // ============ United Kingdom ============
  {
    slug: "uk-sas",
    name: "22 Special Air Service",
    countryCode: "GB",
    parentService: "British Army",
    type: "tier_1",
    foundedYear: 1941,
    estimatedStrength: 600,
    homeBase: "Hereford",
    role: "Tier-1 counterterrorism, direct action, special reconnaissance, hostage rescue.",
    notableOperations: [
      "Iranian Embassy siege 1980 (Operation Nimrod)",
      "Falklands War 1982 (Pebble Island raid)",
      "Persian Gulf War 1991 (Scud hunting)",
    ],
  },
  {
    slug: "uk-sbs",
    name: "Special Boat Service",
    countryCode: "GB",
    parentService: "Royal Navy",
    type: "naval_sof",
    foundedYear: 1940,
    estimatedStrength: 400,
    homeBase: "Poole, Dorset",
    role: "UK maritime SOF; direct action, special reconnaissance, counter-piracy.",
  },
  {
    slug: "uk-srr",
    name: "Special Reconnaissance Regiment",
    countryCode: "GB",
    parentService: "British Army",
    type: "intelligence_sof",
    foundedYear: 2005,
    homeBase: "Hereford",
    role: "Covert close target reconnaissance and surveillance for UKSF.",
  },
  // ============ France ============
  {
    slug: "fr-1er-rpima",
    name: "1er Régiment de parachutistes d'infanterie de marine (1er RPIMa)",
    countryCode: "FR",
    parentService: "Armée de Terre",
    type: "tier_1",
    foundedYear: 1947,
    estimatedStrength: 1100,
    homeBase: "Bayonne",
    role: "Premier French Army SOF; direct action, special reconnaissance, hostage rescue.",
  },
  {
    slug: "fr-commandos-marine",
    name: "Commandos Marine (FORFUSCO)",
    countryCode: "FR",
    parentService: "Marine nationale",
    type: "naval_sof",
    foundedYear: 1947,
    estimatedStrength: 600,
    homeBase: "Lorient",
    role: "French naval SOF; direct action, hostage rescue, maritime counterterrorism. Includes Commando Hubert (combat divers).",
  },
  {
    slug: "fr-cpa10",
    name: "Commando Parachutiste de l'Air n° 10",
    countryCode: "FR",
    parentService: "Armée de l'air et de l'espace",
    type: "tier_1",
    foundedYear: 1956,
    homeBase: "Orléans-Bricy",
    role: "French Air Force SOF; air-ground integration, JTAC operations.",
  },
  {
    slug: "fr-gign",
    name: "Groupe d'intervention de la Gendarmerie nationale (GIGN)",
    countryCode: "FR",
    parentService: "Gendarmerie nationale",
    type: "law_enforcement_sof",
    foundedYear: 1974,
    estimatedStrength: 380,
    homeBase: "Versailles-Satory",
    role: "Domestic counterterrorism, hostage rescue, VIP protection.",
    notableOperations: [
      "Air France 8969 hijacking 1994",
      "Bataclan 2015 response",
    ],
  },
  // ============ Germany ============
  {
    slug: "de-ksk",
    name: "Kommando Spezialkräfte (KSK)",
    countryCode: "DE",
    parentService: "Bundeswehr",
    type: "tier_1",
    foundedYear: 1996,
    estimatedStrength: 1000,
    homeBase: "Calw",
    role: "German Army SOF; direct action, special reconnaissance, counterterrorism.",
    notableOperations: [
      "Afghanistan 2002-2021",
      "ISAF special operations",
    ],
  },
  {
    slug: "de-ksm",
    name: "Kommando Spezialkräfte Marine (KSM)",
    countryCode: "DE",
    parentService: "Deutsche Marine",
    type: "naval_sof",
    foundedYear: 2014,
    estimatedStrength: 400,
    homeBase: "Eckernförde",
    role: "German naval SOF (formerly Kampfschwimmer); direct action, maritime counterterrorism.",
  },
  // ============ Italy ============
  {
    slug: "it-comsubin",
    name: "Comando Raggruppamento Subacquei e Incursori 'Teseo Tesei' (COMSUBIN)",
    countryCode: "IT",
    parentService: "Marina Militare",
    type: "naval_sof",
    foundedYear: 1952,
    homeBase: "Varignano, La Spezia",
    role: "Italian naval SOF; direct action, special reconnaissance, EOD, maritime counterterrorism.",
  },
  {
    slug: "it-9-col-moschin",
    name: "9° Reggimento d'Assalto Paracadutisti 'Col Moschin'",
    countryCode: "IT",
    parentService: "Esercito Italiano",
    type: "tier_1",
    foundedYear: 1975,
    homeBase: "Livorno",
    role: "Italian Army SOF; direct action, special reconnaissance, counterterrorism.",
  },
  // ============ Spain ============
  {
    slug: "es-uoe",
    name: "Unidad de Operaciones Especiales (UOE)",
    countryCode: "ES",
    parentService: "Spanish Marine Infantry",
    type: "naval_sof",
    homeBase: "San Fernando, Cádiz",
    role: "Spanish marine SOF; direct action, special reconnaissance.",
  },
  {
    slug: "es-mceg",
    name: "Mando de Operaciones Especiales (MOE)",
    countryCode: "ES",
    parentService: "Ejército de Tierra",
    type: "tier_2",
    homeBase: "Alicante",
    role: "Spanish Army SOF command.",
  },
  // ============ Poland ============
  {
    slug: "pl-grom",
    name: "GROM (Jednostka Wojskowa GROM)",
    countryCode: "PL",
    parentService: "Polish Armed Forces",
    type: "tier_1",
    foundedYear: 1990,
    estimatedStrength: 350,
    homeBase: "Warsaw",
    role: "Premier Polish SOF; direct action, special reconnaissance, counterterrorism.",
    notableOperations: [
      "Operation Iraqi Freedom (Umm Qasr port seizure 2003)",
      "Afghanistan operations",
    ],
  },
  {
    slug: "pl-formoza",
    name: "Formoza (JW Formoza)",
    countryCode: "PL",
    parentService: "Polish Navy",
    type: "naval_sof",
    foundedYear: 1975,
    homeBase: "Gdynia",
    role: "Polish naval SOF; combat divers, direct action.",
  },
  // ============ Russia ============
  {
    slug: "ru-spetsnaz-gru-2",
    name: "2nd Spetsnaz Brigade",
    countryCode: "RU",
    parentService: "GRU / Russian Ground Forces",
    type: "tier_2",
    homeBase: "Pskov",
    role: "GRU special-purpose brigade; reconnaissance, raiding, sabotage. Heavily engaged in Ukraine since 2022.",
  },
  {
    slug: "ru-spetsnaz-gru-3",
    name: "3rd Spetsnaz Brigade (Guards)",
    countryCode: "RU",
    parentService: "GRU / Russian Ground Forces",
    type: "tier_2",
    homeBase: "Tolyatti",
    role: "GRU special-purpose brigade.",
  },
  {
    slug: "ru-alpha-group",
    name: "Spetsgruppa A 'Alpha'",
    countryCode: "RU",
    parentService: "FSB Special Operations Center",
    type: "tier_1",
    foundedYear: 1974,
    homeBase: "Moscow",
    role: "FSB elite counterterrorism unit; protects regime stability.",
    notableOperations: [
      "Beslan school siege 2004",
      "Moscow theater hostage crisis 2002",
    ],
  },
  {
    slug: "ru-vympel",
    name: "Spetsgruppa V 'Vympel'",
    countryCode: "RU",
    parentService: "FSB Special Operations Center",
    type: "tier_1",
    foundedYear: 1981,
    homeBase: "Balashikha",
    role: "Originally KGB foreign sabotage unit; now FSB CT and nuclear-facility security.",
  },
  {
    slug: "ru-kso",
    name: "Special Operations Forces Command (KSO)",
    countryCode: "RU",
    parentService: "Russian Armed Forces",
    type: "tier_1",
    foundedYear: 2009,
    homeBase: "Senezh, Solnechnogorsk",
    role: "Russia's tier-1 SOF; modeled on Western SOF.",
    notableOperations: [
      "Crimea annexation 2014 ('little green men')",
      "Syria operations",
    ],
  },
  // ============ China ============
  {
    slug: "cn-sword-southern-service",
    name: "Sword of Southern Service",
    countryCode: "CN",
    parentService: "Southern Theater Command",
    type: "tier_2",
    homeBase: "Guangzhou",
    role: "PLA Southern Theater SOF brigade; South China Sea / Indo-Pacific operations.",
  },
  {
    slug: "cn-falcon",
    name: "Falcon Commando Unit",
    countryCode: "CN",
    parentService: "PAP / People's Armed Police",
    type: "law_enforcement_sof",
    foundedYear: 1982,
    homeBase: "Beijing",
    role: "Counterterrorism and hostage rescue.",
  },
  {
    slug: "cn-sea-dragon",
    name: "Jiaolong Commando Unit (Sea Dragon)",
    countryCode: "CN",
    parentService: "PLA Navy",
    type: "naval_sof",
    homeBase: "Hainan",
    role: "PLA Navy SOF; counter-piracy, maritime direct action.",
  },
  // ============ Israel ============
  {
    slug: "il-sayeret-matkal",
    name: "Sayeret Matkal",
    countryCode: "IL",
    parentService: "IDF General Staff Reconnaissance Unit",
    type: "tier_1",
    foundedYear: 1957,
    estimatedStrength: 200,
    homeBase: "Tel Nof Airbase",
    role: "Tier-1 strategic reconnaissance, hostage rescue, direct action.",
    notableOperations: [
      "Entebbe rescue 1976",
      "Sabena Flight 571 hostage rescue 1972",
    ],
  },
  {
    slug: "il-shayetet-13",
    name: "Shayetet 13",
    countryCode: "IL",
    parentService: "Israeli Navy",
    type: "naval_sof",
    foundedYear: 1948,
    homeBase: "Atlit",
    role: "Israeli naval SOF; maritime counterterrorism, direct action.",
  },
  {
    slug: "il-shaldag",
    name: "Shaldag Unit",
    countryCode: "IL",
    parentService: "Israeli Air Force",
    type: "tier_1",
    foundedYear: 1976,
    homeBase: "Palmachim",
    role: "Tier-1 IAF SOF for air-ground integration, target designation, JTAC.",
  },
  {
    slug: "il-duvdevan",
    name: "Duvdevan Unit (217)",
    countryCode: "IL",
    parentService: "IDF Paratroopers Brigade",
    type: "intelligence_sof",
    foundedYear: 1986,
    homeBase: "Mitkan Adam",
    role: "Undercover counter-terror unit; primarily West Bank operations.",
  },
  // ============ South Korea ============
  {
    slug: "kr-707",
    name: "707th Special Mission Group",
    countryCode: "KR",
    parentService: "ROK Army Special Warfare Command",
    type: "tier_1",
    foundedYear: 1981,
    homeBase: "Seongnam",
    role: "ROK tier-1 counterterrorism and direct action.",
  },
  {
    slug: "kr-udt-seal",
    name: "ROK Naval Special Warfare Flotilla (UDT/SEAL)",
    countryCode: "KR",
    parentService: "ROK Navy",
    type: "naval_sof",
    homeBase: "Jinhae",
    role: "Korean naval SOF; maritime CT, direct action, counter-DPRK infiltration.",
    notableOperations: [
      "Daewon hostage rescue 2011 (Somali pirates)",
    ],
  },
  // ============ Japan ============
  {
    slug: "jp-sog",
    name: "Special Operations Group (Tokushu Sakusen Gun)",
    countryCode: "JP",
    parentService: "Japan Ground Self-Defense Force",
    type: "tier_1",
    foundedYear: 2004,
    estimatedStrength: 400,
    homeBase: "Camp Narashino",
    role: "JGSDF tier-1 SOF; CT, direct action.",
  },
  {
    slug: "jp-special-boarding-unit",
    name: "Special Boarding Unit",
    countryCode: "JP",
    parentService: "JMSDF",
    type: "naval_sof",
    foundedYear: 2001,
    homeBase: "Etajima",
    role: "JMSDF SOF; vessel boarding and counter-terror.",
  },
  // ============ India ============
  {
    slug: "in-para-sf",
    name: "Para SF (Parachute Regiment Special Forces battalions)",
    countryCode: "IN",
    parentService: "Indian Army",
    type: "tier_1",
    estimatedStrength: 4000,
    homeBase: "Various",
    role: "Indian Army tier-1 SOF; direct action, special reconnaissance.",
    notableOperations: [
      "2016 surgical strikes (Pakistan-administered Kashmir)",
      "Myanmar cross-border operation 2015",
    ],
  },
  {
    slug: "in-marcos",
    name: "MARCOS (Marine Commandos)",
    countryCode: "IN",
    parentService: "Indian Navy",
    type: "naval_sof",
    foundedYear: 1987,
    homeBase: "Mumbai",
    role: "Indian Navy SOF; CT, direct action, anti-piracy.",
  },
  {
    slug: "in-garud",
    name: "Garud Commando Force",
    countryCode: "IN",
    parentService: "Indian Air Force",
    type: "tier_2",
    foundedYear: 2004,
    homeBase: "Hindon",
    role: "IAF SOF; airfield seizure, JTAC, search and rescue.",
  },
  // ============ Pakistan ============
  {
    slug: "pk-ssg",
    name: "Special Service Group",
    countryCode: "PK",
    parentService: "Pakistan Army",
    type: "tier_1",
    foundedYear: 1956,
    homeBase: "Tarbela",
    role: "Pakistan Army SOF; CT, direct action, unconventional warfare.",
  },
  {
    slug: "pk-ssg-n",
    name: "SSG (Navy)",
    countryCode: "PK",
    parentService: "Pakistan Navy",
    type: "naval_sof",
    foundedYear: 1966,
    homeBase: "Karachi",
    role: "Pakistan Navy SOF.",
  },
  // ============ Iran ============
  {
    slug: "ir-irgc-quds",
    name: "IRGC Quds Force",
    countryCode: "IR",
    parentService: "IRGC",
    type: "tier_1",
    foundedYear: 1990,
    estimatedStrength: 15000,
    homeBase: "Tehran",
    role: "Iranian extraterritorial special operations and proxy liaison; backbone of the 'Axis of Resistance'.",
    notableOperations: [
      "Iraqi Shiite militia liaison",
      "Hezbollah operational support",
      "Houthi liaison and weapons transfer",
    ],
  },
  {
    slug: "ir-irgc-saberin",
    name: "IRGC Saberin Special Forces",
    countryCode: "IR",
    parentService: "IRGC Ground Forces",
    type: "tier_2",
    homeBase: "Tehran",
    role: "IRGC Ground Forces SOF.",
  },
  // ============ DPRK ============
  {
    slug: "kp-viii-soc",
    name: "VIII Special Operations Corps",
    countryCode: "KP",
    parentService: "Korean People's Army",
    type: "airborne_sof",
    estimatedStrength: 200000,
    homeBase: "Various",
    role: "Largest SOF force in the world by personnel; light infantry, airborne, and reconnaissance brigades.",
  },
  // ============ Australia ============
  {
    slug: "au-sasr",
    name: "Special Air Service Regiment (SASR)",
    countryCode: "AU",
    parentService: "Australian Army",
    type: "tier_1",
    foundedYear: 1957,
    estimatedStrength: 600,
    homeBase: "Campbell Barracks, Perth",
    role: "Australian tier-1 SOF; direct action, special reconnaissance, CT.",
  },
  {
    slug: "au-2cdo",
    name: "2nd Commando Regiment",
    countryCode: "AU",
    parentService: "Australian Army",
    type: "tier_2",
    homeBase: "Holsworthy, Sydney",
    role: "Australian commando regiment; direct action, large-team SOF.",
  },
  // ============ Canada ============
  {
    slug: "ca-jtf2",
    name: "Joint Task Force 2",
    countryCode: "CA",
    parentService: "Canadian Special Operations Forces Command",
    type: "tier_1",
    foundedYear: 1993,
    homeBase: "Dwyer Hill, Ottawa",
    role: "Canadian tier-1 SOF; CT, direct action, hostage rescue.",
  },
  {
    slug: "ca-csor",
    name: "Canadian Special Operations Regiment",
    countryCode: "CA",
    parentService: "CANSOFCOM",
    type: "tier_2",
    foundedYear: 2006,
    homeBase: "Petawawa",
    role: "Direct action, special reconnaissance, foreign internal defense.",
  },
];
