import type { SubStateActor } from "./types";

export const subStateActorsB: SubStateActor[] = [
  // ============ Asia ============
  {
    slug: "isis-k",
    name: "Islamic State Khorasan Province",
    aliases: ["ISIS-K", "ISKP", "Wilayat Khorasan"],
    type: "militant_group",
    region: "Asia",
    areaOfOperations: [
      "Afghanistan",
      "Pakistan",
      "Iran (cross-border)",
      "Central Asia",
    ],
    foundedYear: 2015,
    estimatedStrength: 2000,
    ideology: "Sunni Islamist (Islamic State affiliate)",
    arsenal: [
      "Small arms",
      "VBIEDs",
      "Suicide vests",
      "Captured Afghan security force equipment",
    ],
    notableOperations: [
      "Kabul airport attack August 2021 (~170 killed including 13 US service members)",
      "Crocus City Hall attack (Moscow, March 2024)",
      "Kerman bombings January 2024 (Iran)",
    ],
    description:
      "Islamic State branch active in South-Central Asia; principal global ISIS branch since 2022. Has conducted external operations beyond its core AOR including in Russia and Iran.",
  },
  {
    slug: "ttp",
    name: "Tehrik-i-Taliban Pakistan",
    aliases: ["TTP", "Pakistani Taliban"],
    type: "militant_group",
    region: "Asia",
    areaOfOperations: ["Khyber Pakhtunkhwa, Pakistan", "Afghan border regions"],
    foundedYear: 2007,
    estimatedStrength: 6000,
    ideology: "Sunni Islamist; aligned with Afghan Taliban",
    arsenal: ["Captured Pakistani military small arms", "IEDs", "VBIEDs"],
    description:
      "Pakistani Taliban; active across Pakistan-Afghanistan border. Resurgent since 2021 Afghan Taliban takeover. Subject of Pakistani military operations and TTP-Afghan-Taliban tensions.",
  },
  {
    slug: "lashkar-e-taiba",
    name: "Lashkar-e-Taiba",
    aliases: ["LeT", "Jamaat-ud-Dawa (charitable front)"],
    type: "militant_group",
    region: "Asia",
    areaOfOperations: [
      "Pakistan-administered Kashmir",
      "Indian-administered J&K",
      "International",
    ],
    foundedYear: 1990,
    estimatedStrength: 50000,
    primarySponsorCountryCode: "PK",
    ideology: "Sunni Islamist; anti-India",
    arsenal: [
      "Pakistani-supplied small arms",
      "IEDs",
      "Maritime infiltration capability",
    ],
    notableOperations: [
      "Mumbai 2008 attacks (172 killed)",
      "Cross-LoC infiltration operations (ongoing)",
    ],
    description:
      "Pakistan-based militant group historically linked to ISI; principal anti-India organization. UN-designated terrorist organization 2005.",
  },
  {
    slug: "jaish-e-mohammed",
    name: "Jaish-e-Mohammed",
    aliases: ["JeM"],
    type: "militant_group",
    region: "Asia",
    areaOfOperations: ["Pakistan", "Indian-administered Kashmir"],
    foundedYear: 2000,
    estimatedStrength: 5000,
    ideology: "Sunni Islamist; anti-India; anti-Western",
    arsenal: ["Small arms", "IEDs", "VBIEDs", "Suicide vests"],
    notableOperations: [
      "2001 Indian Parliament attack",
      "2019 Pulwama attack (40 CRPF killed)",
    ],
    description:
      "Pakistan-based Deobandi militant group; UN-designated terrorist organization. 2019 Pulwama attack triggered the India-Pakistan Balakot crisis.",
  },
  {
    slug: "hizbul-mujahideen",
    name: "Hizbul Mujahideen",
    aliases: ["HM"],
    type: "militant_group",
    region: "Asia",
    areaOfOperations: ["Indian-administered Kashmir"],
    foundedYear: 1989,
    estimatedStrength: 1500,
    ideology: "Sunni Islamist; pro-Pakistan accession",
    description:
      "Kashmir-focused militant group; smaller than LeT or JeM but historically the largest Kashmiri-origin organization.",
    arsenal: ["Small arms", "IEDs"],
  },
  {
    slug: "bla",
    name: "Baloch Liberation Army",
    aliases: ["BLA"],
    type: "separatist",
    region: "Asia",
    areaOfOperations: ["Balochistan, Pakistan"],
    foundedYear: 2000,
    estimatedStrength: 3000,
    ideology: "Baloch nationalism; secularist",
    arsenal: ["Small arms", "ATGMs (limited)", "IEDs", "VBIEDs"],
    notableOperations: [
      "Attacks on Chinese personnel and CPEC infrastructure (multiple)",
      "Bolan Pass attack 2024",
      "Quetta train hijacking 2025",
    ],
    description:
      "Baloch separatist insurgent group; principal armed challenger to Pakistani control of Balochistan. Specifically targets Chinese personnel and CPEC infrastructure.",
  },
  {
    slug: "afghan-taliban",
    name: "Islamic Emirate of Afghanistan (Taliban)",
    aliases: ["Afghan Taliban", "Quetta Shura (historic)"],
    type: "militant_group",
    region: "Asia",
    areaOfOperations: ["Afghanistan (de facto government)"],
    foundedYear: 1994,
    estimatedStrength: 80000,
    ideology: "Sunni Islamist; Deobandi-influenced; Pashtun-led",
    keyLeaders: ["Hibatullah Akhundzada (Supreme Leader)"],
    arsenal: [
      "Captured Afghan National Army equipment (US-supplied)",
      "M16/M4",
      "HMMWVs",
      "UH-60 Black Hawks (limited operability)",
    ],
    description:
      "De facto government of Afghanistan since August 2021. Inherited substantial US-supplied Afghan National Army equipment. UN-sanctioned individual leadership; not a UN-designated terrorist organization.",
  },
  {
    slug: "haqqani-network",
    name: "Haqqani Network",
    aliases: ["Khalifa Sirajuddin Haqqani-led network"],
    type: "militant_group",
    region: "Asia",
    areaOfOperations: ["Eastern Afghanistan", "Pakistan tribal areas"],
    foundedYear: 1980,
    estimatedStrength: 10000,
    ideology: "Sunni Islamist (allied with Taliban)",
    keyLeaders: ["Sirajuddin Haqqani (Acting Interior Minister, IEA)"],
    arsenal: ["Captured Afghan equipment", "VBIEDs"],
    description:
      "Originally a Mujahideen faction; integrated into Taliban government. Formerly closely linked to Pakistani ISI. UN-sanctioned as a terrorist group; principal element of Taliban Interior Ministry.",
  },
  {
    slug: "arakan-army",
    name: "Arakan Army",
    aliases: ["AA"],
    type: "insurgent",
    region: "Asia",
    areaOfOperations: ["Rakhine State, Myanmar"],
    foundedYear: 2009,
    estimatedStrength: 30000,
    ideology: "Rakhine ethnic nationalism",
    arsenal: [
      "Captured Tatmadaw equipment",
      "ATGMs (Chinese-derived)",
      "Mortars",
    ],
    description:
      "Major ethnic armed organization in western Myanmar. Captured most of Rakhine State from the Tatmadaw in 2024.",
  },
  {
    slug: "kia",
    name: "Kachin Independence Army",
    aliases: ["KIA"],
    type: "insurgent",
    region: "Asia",
    areaOfOperations: ["Kachin State, Myanmar", "Northern Shan State"],
    foundedYear: 1961,
    estimatedStrength: 12000,
    ideology: "Kachin nationalism",
    arsenal: ["Captured Tatmadaw equipment", "Chinese-supplied small arms"],
    description:
      "Kachin Independence Organization's armed wing; one of the longest-running Myanmar ethnic armed organizations.",
  },
  {
    slug: "pdf-myanmar",
    name: "People's Defence Force (Myanmar)",
    aliases: ["PDF", "NUG armed wing"],
    type: "insurgent",
    region: "Asia",
    areaOfOperations: ["Bamar heartland Myanmar"],
    foundedYear: 2021,
    estimatedStrength: 100000,
    ideology:
      "Pro-democracy; multi-ethnic National Unity Government affiliation",
    arsenal: [
      "3D-printed firearms",
      "FGM-148 Javelin (limited)",
      "Captured Tatmadaw equipment",
      "Improvised UAVs",
    ],
    description:
      "Armed wing of the National Unity Government of Myanmar; multiple regional commands fighting the post-coup military junta.",
  },
  {
    slug: "uwsa",
    name: "United Wa State Army",
    aliases: ["UWSA"],
    type: "insurgent",
    region: "Asia",
    areaOfOperations: ["Wa Self-Administered Division, Myanmar"],
    foundedYear: 1989,
    estimatedStrength: 30000,
    primarySponsorCountryCode: "CN",
    ideology: "Wa autonomy; ceasefire with Tatmadaw",
    arsenal: [
      "Chinese-supplied HQ-12 SAM",
      "MANPADS",
      "Type 81 / Type 56 small arms",
      "ATGMs",
      "Type 99 MBT (small numbers)",
    ],
    description:
      "Best-equipped non-state armed group in Asia. Operates Wa State as a quasi-autonomous PRC-aligned territory. Has not actively fought the Tatmadaw since 1989 ceasefire.",
  },
  {
    slug: "naxalites-cpi-maoist",
    name: "Communist Party of India (Maoist)",
    aliases: ["Naxalites", "CPI-Maoist"],
    type: "insurgent",
    region: "Asia",
    areaOfOperations: [
      "Chhattisgarh",
      "Jharkhand",
      "Odisha",
      "tribal belt of central India",
    ],
    foundedYear: 2004,
    estimatedStrength: 5000,
    ideology: "Maoist communism",
    arsenal: [
      "Locally-produced firearms",
      "Captured Indian small arms",
      "IEDs",
    ],
    description:
      "Maoist insurgent group active in India's 'Red Corridor.' Subject to long-running CRPF and state-police counter-insurgency.",
  },

  // ============ Eurasia / Russia-Ukraine ============
  {
    slug: "wagner-group",
    name: "Wagner Group (legacy)",
    aliases: ["PMC Wagner", "ChVK Vagner"],
    type: "private_military_company",
    region: "Eurasia",
    areaOfOperations: [
      "Africa (succeeded by Africa Corps)",
      "Syria (legacy)",
      "Ukraine 2022-2023",
    ],
    foundedYear: 2014,
    estimatedStrength: 25000,
    primarySponsorCountryCode: "RU",
    ideology: "Russian state interests; nationalist branding",
    keyLeaders: [
      "Yevgeny Prigozhin (killed Aug 2023)",
      "Dmitry Utkin (killed Aug 2023)",
    ],
    arsenal: [
      "Russian small arms",
      "T-72 / T-90 MBT",
      "BMP-2/3 IFV",
      "Su-25 (limited)",
    ],
    notableOperations: [
      "Ukraine 2022-2023 (Bakhmut, Soledar)",
      "March 2023 Wagner mutiny / 'march on Moscow'",
      "African operations (CAR, Mali, Libya, Sudan, Mozambique)",
    ],
    description:
      "Russian private military company, effectively absorbed into Russian state structures (Africa Corps successor) following Prigozhin's death. Substantial role in Ukraine and African theaters 2014-2023.",
  },
  {
    slug: "kadyrovtsy",
    name: "Akhmat Special Forces (Kadyrovtsy)",
    aliases: ["Akhmat", "Chechen units"],
    type: "paramilitary",
    region: "Eurasia",
    areaOfOperations: ["Chechnya (HQ)", "Ukraine"],
    estimatedStrength: 70000,
    primarySponsorCountryCode: "RU",
    ideology: "Russian nationalist; loyal to Ramzan Kadyrov",
    keyLeaders: ["Ramzan Kadyrov"],
    arsenal: ["Russian Federation-supplied weapons", "T-72B3", "BMP-3"],
    description:
      "Chechen Republic security forces effectively under personal command of Ramzan Kadyrov; deployed to Ukraine in significant numbers since 2022.",
  },
  {
    slug: "azov-brigade",
    name: "12th Special Forces Brigade Azov",
    aliases: ["Azov Brigade", "12th Brigade Azov"],
    type: "paramilitary",
    region: "Eurasia",
    areaOfOperations: ["Eastern Ukraine"],
    foundedYear: 2014,
    estimatedStrength: 8000,
    ideology: "Ukrainian nationalism",
    arsenal: [
      "Western-supplied small arms (post-2023)",
      "Ukrainian armored equipment",
      "ATGMs (Javelin, NLAW, Stugna-P)",
    ],
    notableOperations: [
      "Defense of Mariupol 2022 (siege of Azovstal)",
      "Kursk Oblast incursion 2024",
    ],
    description:
      "Ukrainian National Guard / Armed Forces formation grown from the 2014 Azov Battalion. US arms restrictions on the unit lifted in 2024.",
  },
  {
    slug: "kraken-gur",
    name: "Kraken Special Operations Detachment (HUR / GUR-DI)",
    aliases: ["Kraken Regiment"],
    type: "paramilitary",
    region: "Eurasia",
    areaOfOperations: [
      "Northeastern Ukraine",
      "Russian rear (cross-border raids)",
    ],
    foundedYear: 2022,
    estimatedStrength: 2000,
    ideology: "Ukrainian nationalist; HUR-aligned",
    arsenal: [
      "Western-supplied small arms",
      "Captured Russian equipment",
      "Loitering munitions",
    ],
    description:
      "Ukrainian special operations unit subordinate to military intelligence (HUR). Conducts long-range reconnaissance and raids.",
  },
  {
    slug: "free-russia-legion",
    name: "Free Russia Legion / Russian Volunteer Corps",
    aliases: ["LSR", "RDK", "Russian Liberation Movement units"],
    type: "paramilitary",
    region: "Eurasia",
    areaOfOperations: [
      "Northeastern Ukraine",
      "Russian border regions (cross-border)",
    ],
    foundedYear: 2022,
    estimatedStrength: 2000,
    ideology:
      "Anti-Putin Russian opposition; heterogeneous nationalist and liberal cohorts",
    arsenal: ["Western and captured Russian equipment"],
    description:
      "Anti-Kremlin Russian volunteers fighting on the Ukrainian side; conducted cross-border raids into Belgorod and Kursk Oblasts since 2023.",
  },

  // ============ Americas ============
  {
    slug: "farc-dissidents-emc",
    name: "Estado Mayor Central (FARC dissidents)",
    aliases: ["EMC", "Bloque del Sur"],
    type: "insurgent",
    region: "Americas",
    areaOfOperations: ["Southern Colombia", "Venezuela border"],
    foundedYear: 2017,
    estimatedStrength: 3500,
    ideology: "Marxist; FARC ideological successor",
    keyLeaders: ["Iván Mordisco"],
    arsenal: [
      "Captured small arms",
      "IEDs",
      "RPG-7",
      "Venezuelan-supplied equipment (alleged)",
    ],
    description:
      "Largest faction of FARC dissidents who rejected the 2016 peace agreement. Subject of 'Total Peace' negotiations under the Petro government.",
  },
  {
    slug: "farc-dissidents-segunda-marquetalia",
    name: "Segunda Marquetalia",
    aliases: ["Second Marquetalia"],
    type: "insurgent",
    region: "Americas",
    areaOfOperations: ["Colombia-Venezuela border"],
    foundedYear: 2019,
    estimatedStrength: 1500,
    ideology: "Marxist; FARC ideological successor",
    keyLeaders: ["Iván Márquez"],
    arsenal: ["Small arms", "IEDs"],
    description:
      "Faction of senior former FARC commanders who returned to armed struggle in 2019 alleging non-implementation of the peace accord. Operates from Venezuelan territory.",
  },
  {
    slug: "eln",
    name: "Ejército de Liberación Nacional",
    aliases: ["ELN", "National Liberation Army (Colombia)"],
    type: "insurgent",
    region: "Americas",
    areaOfOperations: ["Colombia (Catatumbo, Chocó)", "Venezuela border"],
    foundedYear: 1964,
    estimatedStrength: 5000,
    ideology: "Marxist-Leninist; liberation theology-influenced",
    arsenal: ["Small arms", "ATGMs (limited)", "IEDs", "Drone-dropped IEDs"],
    description:
      "Last major Colombian Marxist insurgent group. Subject to multi-track 'Total Peace' negotiations and active hostilities in early 2025.",
  },
  {
    slug: "clan-del-golfo",
    name: "Clan del Golfo",
    aliases: ["Autodefensas Gaitanistas de Colombia", "AGC"],
    type: "organized_crime",
    region: "Americas",
    areaOfOperations: ["Northern Colombia", "Caribbean coast"],
    foundedYear: 2008,
    estimatedStrength: 10000,
    ideology: "Successor of paramilitary AUC; commercial-criminal motives",
    arsenal: ["Small arms"],
    description:
      "Largest Colombian neo-paramilitary criminal organization. Engaged in cocaine trafficking and territorial control.",
  },
  {
    slug: "sinaloa-cartel",
    name: "Sinaloa Cartel",
    aliases: ["Cártel de Sinaloa", "CDS"],
    type: "organized_crime",
    region: "Americas",
    areaOfOperations: [
      "Mexico (Sinaloa, northern states)",
      "United States (distribution)",
    ],
    foundedYear: 1989,
    estimatedStrength: 25000,
    ideology: "Commercial-criminal",
    keyLeaders: [
      "Los Chapitos faction",
      "El Mayo Zambada (arrested July 2024)",
    ],
    arsenal: [
      "Belt-fed machine guns",
      "Barrett .50 cal",
      "RPGs (limited)",
      "Improvised armored vehicles ('narco-tanks')",
      "Modified UAVs (drone-dropped IEDs)",
    ],
    description:
      "Mexican drug trafficking organization; principal supplier of fentanyl to North American markets. Internal feud between Los Chapitos and Mayo Zambada factions intensified after Zambada's arrest.",
  },
  {
    slug: "cjng",
    name: "Cártel Jalisco Nueva Generación",
    aliases: ["CJNG", "Jalisco New Generation Cartel"],
    type: "organized_crime",
    region: "Americas",
    areaOfOperations: ["Mexico (Jalisco, multiple states)"],
    foundedYear: 2010,
    estimatedStrength: 20000,
    ideology: "Commercial-criminal",
    keyLeaders: ["El Mencho (Nemesio Oseguera Cervantes)"],
    arsenal: [
      "Heavy machine guns",
      "Sniper rifles",
      "RPGs",
      "Anti-personnel UAVs",
      "Improvised armored vehicles",
    ],
    description:
      "Mexican drug trafficking organization rivaling Sinaloa. Notably aggressive paramilitary-style tactics including UAV drops and ambushes of state security forces.",
  },
  {
    slug: "tren-de-aragua",
    name: "Tren de Aragua",
    aliases: ["TdA"],
    type: "organized_crime",
    region: "Americas",
    areaOfOperations: [
      "Venezuela (Aragua origin)",
      "Colombia",
      "Peru",
      "Chile",
      "United States (recent expansion)",
    ],
    foundedYear: 2014,
    estimatedStrength: 5000,
    ideology: "Commercial-criminal; transnational gang structure",
    arsenal: ["Small arms"],
    description:
      "Venezuelan-origin transnational criminal organization; rapid expansion across Latin America in recent years. US-designated as a foreign terrorist organization in February 2025.",
  },
  {
    slug: "ms-13",
    name: "MS-13 (Mara Salvatrucha)",
    aliases: ["MS-13"],
    type: "organized_crime",
    region: "Americas",
    areaOfOperations: [
      "El Salvador",
      "Honduras",
      "Guatemala",
      "Mexico",
      "United States",
    ],
    foundedYear: 1979,
    estimatedStrength: 30000,
    ideology: "Transnational gang structure",
    arsenal: ["Small arms"],
    description:
      "Transnational gang originating in Los Angeles among Salvadoran refugees; long established across Central America and the United States. Subject of mass incarceration under El Salvador's state of exception (2022-present).",
  },

  // ============ Cyber actors ============
  {
    slug: "lazarus-group",
    name: "Lazarus Group",
    aliases: ["APT38", "Hidden Cobra", "Bureau 121-affiliated"],
    type: "cyber_actor",
    region: "Asia",
    areaOfOperations: ["Worldwide cyber operations"],
    foundedYear: 2009,
    primarySponsorCountryCode: "KP",
    ideology: "Sanctions-evasion and intelligence collection on behalf of DPRK",
    arsenal: [
      "Custom malware (BLINDINGCAN, AppleJeus, MagicRAT)",
      "Cryptocurrency-laundering pipelines",
      "Supply-chain compromise tradecraft",
    ],
    notableOperations: [
      "Sony Pictures hack 2014",
      "Bangladesh Bank heist 2016 (~$81M)",
      "WannaCry 2017",
      "Cryptocurrency exchange thefts ($3B+ cumulative)",
    ],
    description:
      "DPRK state-affiliated cyber actor (Reconnaissance General Bureau, Bureau 121). Principal financial-cyber threat actor globally; major contributor to DPRK sanctions evasion and weapons program funding.",
  },
  {
    slug: "apt29-cozy-bear",
    name: "APT29 (Cozy Bear)",
    aliases: ["The Dukes", "Nobelium", "Midnight Blizzard"],
    type: "cyber_actor",
    region: "Eurasia",
    areaOfOperations: ["Worldwide intelligence collection"],
    primarySponsorCountryCode: "RU",
    ideology: "Russian foreign intelligence collection (SVR)",
    arsenal: [
      "Sophisticated custom backdoors (HAMMERTOSS, MINIDUKE, FOGGYWEB)",
      "Supply-chain compromise (SolarWinds)",
      "OAuth abuse",
    ],
    notableOperations: [
      "DNC compromise 2015 (with APT28)",
      "SolarWinds Orion supply-chain attack 2020",
      "Microsoft and HPE corporate compromises 2023-2024",
    ],
    description:
      "Russian SVR-attributed cyber threat actor specializing in long-dwell-time intelligence collection. Notable for sophisticated supply-chain operations.",
  },
  {
    slug: "apt28-fancy-bear",
    name: "APT28 (Fancy Bear)",
    aliases: ["Sofacy", "Strontium", "Forest Blizzard", "GRU Unit 26165"],
    type: "cyber_actor",
    region: "Eurasia",
    areaOfOperations: ["Worldwide military and political collection"],
    primarySponsorCountryCode: "RU",
    ideology: "Russian military intelligence (GRU) operations",
    arsenal: [
      "X-Agent / Sofacy malware",
      "Sednit toolkit",
      "VPNFilter (with APT-affiliates)",
    ],
    notableOperations: [
      "DNC hack 2016",
      "Bundestag breach 2015",
      "WADA / IAAF hacks 2016",
      "Olympic Destroyer 2018",
      "Persistent operations against Ukraine and NATO since 2022",
    ],
    description:
      "Russian GRU Unit 26165-attributed cyber threat actor. Distinguished from APT29 by faster, more aggressive tradecraft and military-influence operations.",
  },
  {
    slug: "sandworm-apt44",
    name: "Sandworm Team (APT44)",
    aliases: ["Voodoo Bear", "TeleBots", "GRU Unit 74455"],
    type: "cyber_actor",
    region: "Eurasia",
    areaOfOperations: [
      "Ukraine (primary)",
      "Worldwide critical infrastructure",
    ],
    primarySponsorCountryCode: "RU",
    ideology: "Russian destructive military-cyber operations",
    arsenal: [
      "Industroyer / CrashOverride ICS malware",
      "NotPetya wiper",
      "Olympic Destroyer",
      "Wiper families (HermeticWiper, IsaacWiper, CaddyWiper)",
    ],
    notableOperations: [
      "Ukraine power grid attacks 2015 and 2016",
      "NotPetya 2017 (~$10B global damage)",
      "Olympic Destroyer 2018 (Pyeongchang)",
      "Multiple Ukraine wiper waves 2022-present",
    ],
    description:
      "Russian GRU Unit 74455-attributed cyber threat actor specialized in destructive operations against critical infrastructure. Most prolific destructive APT globally.",
  },
  {
    slug: "volt-typhoon",
    name: "Volt Typhoon",
    aliases: ["Vanguard Panda", "BRONZE SILHOUETTE"],
    type: "cyber_actor",
    region: "Asia",
    areaOfOperations: ["US critical infrastructure (especially Indo-Pacific)"],
    primarySponsorCountryCode: "CN",
    ideology: "Chinese pre-positioning for crisis-time disruption",
    arsenal: [
      "Living-off-the-land techniques (no custom malware)",
      "SOHO router botnets (KV-botnet)",
      "VPN appliance compromise",
    ],
    notableOperations: [
      "US critical infrastructure pre-positioning (water, electric, transportation) — disclosed 2023-2024",
    ],
    description:
      "Chinese state-affiliated cyber threat actor publicly named by US/Five Eyes 2023; focus on pre-positioning in US critical infrastructure for disruption in event of Indo-Pacific crisis.",
  },
  {
    slug: "salt-typhoon",
    name: "Salt Typhoon",
    aliases: ["GhostEmperor"],
    type: "cyber_actor",
    region: "Asia",
    areaOfOperations: ["US telecommunications infrastructure"],
    primarySponsorCountryCode: "CN",
    ideology: "Chinese intelligence collection",
    arsenal: [
      "Telecom infrastructure exploitation",
      "CALEA / lawful-intercept abuse",
    ],
    notableOperations: [
      "Compromise of major US telecom providers disclosed 2024 (lawful-intercept systems and senior US officials' communications)",
    ],
    description:
      "Chinese state-affiliated cyber threat actor responsible for the late-2024 compromise of US telecommunications carriers' lawful-intercept systems.",
  },
];
