import type { SubStateActor } from "./types";

export const subStateActorsA: SubStateActor[] = [
  // ============ Middle East ============
  {
    slug: "hezbollah",
    name: "Hezbollah",
    aliases: ["Lebanese Hezbollah", "Party of God", "Islamic Resistance"],
    type: "proxy_force",
    region: "Middle East",
    areaOfOperations: ["Lebanon", "Syria", "Iraq", "Yemen (advisory)"],
    foundedYear: 1985,
    estimatedStrength: 50000,
    primarySponsorCountryCode: "IR",
    ideology: "Shia Islamist; Iranian wilayat al-faqih affiliation",
    keyLeaders: ["Naim Qassem (Secretary-General since Oct 2024)"],
    arsenal: [
      "Fateh-110 / M-600 SRBM (Iranian)",
      "Fajr-3 / Fajr-5 rocket",
      "Burkan-2/3 large-warhead rocket",
      "Almas anti-tank guided missile",
      "Falaq-1/2 short-range rocket",
      "Yakhont anti-ship cruise missile (limited)",
      "Shahed-136 / Mersad-1 UAV",
    ],
    notableOperations: [
      "2006 Lebanon War (cross-border with Israel)",
      "Syrian civil war intervention (2012-present)",
      "October 2023-November 2024 cross-border exchange with IDF (Operation Northern Arrows)",
    ],
    description:
      "Lebanese political party and armed organization; the most heavily-armed non-state actor globally. Designated a foreign terrorist organization by the US, UK, EU, and Gulf states.",
  },
  {
    slug: "hamas",
    name: "Hamas (Islamic Resistance Movement)",
    aliases: ["Harakat al-Muqawama al-Islamiyya"],
    type: "militant_group",
    region: "Middle East",
    areaOfOperations: ["Gaza Strip", "West Bank (limited)"],
    foundedYear: 1987,
    estimatedStrength: 30000,
    primarySponsorCountryCode: "IR",
    ideology:
      "Sunni Islamist; Muslim Brotherhood-derived; rejection of Israeli statehood",
    keyLeaders: [
      "Yahya Sinwar (killed Oct 2024)",
      "Khaled Mashal (political bureau)",
    ],
    arsenal: [
      "Qassam rocket family",
      "M-75 / M-90 / Fajr-5 derivatives",
      "Yasin-105 anti-tank rocket",
      "Tunnel infrastructure (industrial scale)",
      "Improvised UAVs",
      "Small arms and ATGMs (locally produced)",
    ],
    notableOperations: [
      "October 7, 2023 attack on Israel",
      "2014 Operation Protective Edge (Gaza)",
    ],
    description:
      "Palestinian Sunni Islamist organization governing Gaza since 2007. Designated a terrorist organization by the US, EU, UK, Israel, and others.",
  },
  {
    slug: "palestinian-islamic-jihad",
    name: "Palestinian Islamic Jihad",
    aliases: ["PIJ", "Harakat al-Jihad al-Islami fi Filastin"],
    type: "militant_group",
    region: "Middle East",
    areaOfOperations: ["Gaza Strip", "West Bank"],
    foundedYear: 1981,
    estimatedStrength: 8000,
    primarySponsorCountryCode: "IR",
    ideology: "Sunni Islamist; rejectionist",
    arsenal: ["Buraq rocket", "Quds rocket family", "ATGMs"],
    description:
      "Palestinian militant group operating alongside but independently of Hamas. Designated a terrorist organization by the US, EU, and others.",
  },
  {
    slug: "houthis-ansar-allah",
    name: "Ansar Allah (Houthi movement)",
    aliases: ["Houthis", "Houthi militants", "Yemen Armed Forces (claimed)"],
    type: "proxy_force",
    region: "Middle East",
    areaOfOperations: ["Northern Yemen", "Red Sea / Bab-el-Mandeb"],
    foundedYear: 1990,
    estimatedStrength: 200000,
    primarySponsorCountryCode: "IR",
    ideology: "Zaydi Shia revivalism; anti-Western, anti-Israel",
    keyLeaders: ["Abdul-Malik al-Houthi"],
    arsenal: [
      "Toophan / Quds-1/2/3 anti-ship cruise missile",
      "Asef / Falaq-1 anti-ship ballistic missile",
      "Burkan-3 ballistic missile",
      "Shahed-136 / Samad-3 UAV",
      "Sea drones (USVs)",
      "Naval mines",
    ],
    notableOperations: [
      "Saudi-led coalition war 2015-present",
      "2019 Abqaiq-Khurais oil-facility attack (claimed)",
      "Red Sea anti-shipping campaign Nov 2023-present",
    ],
    description:
      "Yemen-based Zaydi Shia armed political movement; controls Sana'a and northern Yemen. Designated a Specially Designated Global Terrorist by the US (re-designated January 2024).",
  },
  {
    slug: "kataib-hezbollah",
    name: "Kata'ib Hezbollah",
    aliases: ["KH", "Hezbollah Brigades"],
    type: "proxy_force",
    region: "Middle East",
    areaOfOperations: ["Iraq", "Syria"],
    foundedYear: 2003,
    estimatedStrength: 10000,
    primarySponsorCountryCode: "IR",
    ideology: "Shia Islamist; Iranian wilayat al-faqih affiliation",
    keyLeaders: ["Abu Hussein al-Hamidawi (post-Soleimani-era leadership)"],
    arsenal: [
      "Iranian-made rockets and short-range missiles",
      "ATGMs (Toophan, Dehlavieh)",
      "UAVs (Shahed-style and locally-produced)",
    ],
    notableOperations: [
      "Attacks on US forces in Iraq and Syria (multiple)",
      "Tower 22 attack (Jordan, January 28, 2024) — three US service members killed",
    ],
    description:
      "Iraqi Shia militia within the Popular Mobilization Forces; closely aligned with IRGC Quds Force. US-designated FTO since 2009.",
  },
  {
    slug: "asaib-ahl-al-haq",
    name: "Asa'ib Ahl al-Haq",
    aliases: ["AAH", "League of the Righteous"],
    type: "proxy_force",
    region: "Middle East",
    areaOfOperations: ["Iraq", "Syria"],
    foundedYear: 2006,
    estimatedStrength: 10000,
    primarySponsorCountryCode: "IR",
    ideology: "Shia Islamist",
    keyLeaders: ["Qais al-Khazali"],
    arsenal: ["Iranian-supplied rockets", "ATGMs", "small arms", "UAVs"],
    description:
      "Iraqi Shia militia within the PMF; political wing has parliamentary seats. US-designated FTO 2020.",
  },
  {
    slug: "harakat-hezbollah-al-nujaba",
    name: "Harakat Hezbollah al-Nujaba",
    aliases: ["HHN", "Nujaba Movement"],
    type: "proxy_force",
    region: "Middle East",
    areaOfOperations: ["Iraq", "Syria"],
    foundedYear: 2013,
    estimatedStrength: 10000,
    primarySponsorCountryCode: "IR",
    ideology: "Shia Islamist",
    arsenal: ["Iranian-supplied rockets", "ATGMs", "UAVs"],
    description:
      "Iraqi Shia militia within the PMF, IRGC-aligned; openly states its mission includes confrontation with Israel and the US.",
  },
  {
    slug: "popular-mobilization-forces",
    name: "Popular Mobilization Forces (Hashd al-Shaabi)",
    aliases: ["PMF", "Hashd al-Sha'abi", "PMU"],
    type: "paramilitary",
    region: "Middle East",
    areaOfOperations: ["Iraq"],
    foundedYear: 2014,
    estimatedStrength: 230000,
    primarySponsorCountryCode: "IQ",
    ideology:
      "Heterogeneous; predominantly Shia with Sunni and Christian units",
    arsenal: [
      "Iraqi state-issued small arms and armor",
      "Iranian-supplied rockets and ATGMs (varied by faction)",
    ],
    description:
      "Iraqi state paramilitary umbrella formed during the anti-ISIS campaign; integrates ~67 brigades, including Iran-aligned, Sistani-aligned, and tribal forces. Legally part of the Iraqi armed forces since 2016.",
  },
  {
    slug: "liwa-fatemiyoun",
    name: "Liwa Fatemiyoun",
    aliases: ["Fatemiyoun Brigade", "Fatemiyoun Division"],
    type: "proxy_force",
    region: "Middle East",
    areaOfOperations: ["Syria", "Afghanistan (origin)"],
    foundedYear: 2014,
    estimatedStrength: 12000,
    primarySponsorCountryCode: "IR",
    ideology: "Shia Islamist",
    arsenal: ["Iranian small arms and rockets"],
    description:
      "IRGC Quds Force-organized brigade composed primarily of Afghan Hazara Shia recruits; deployed to support the Syrian government.",
  },
  {
    slug: "liwa-zainebiyoun",
    name: "Liwa Zainebiyoun",
    aliases: ["Zainebiyoun Brigade"],
    type: "proxy_force",
    region: "Middle East",
    areaOfOperations: ["Syria"],
    foundedYear: 2013,
    estimatedStrength: 2000,
    primarySponsorCountryCode: "IR",
    ideology: "Shia Islamist",
    arsenal: ["Iranian small arms"],
    description:
      "IRGC Quds Force brigade composed primarily of Pakistani Shia recruits; deployed in Syria. US-sanctioned 2019.",
  },
  {
    slug: "hayat-tahrir-al-sham",
    name: "Hayat Tahrir al-Sham",
    aliases: ["HTS", "Tahrir al-Sham"],
    type: "militant_group",
    region: "Middle East",
    areaOfOperations: ["Northwest Syria (Idlib province)"],
    foundedYear: 2017,
    estimatedStrength: 30000,
    ideology: "Sunni Islamist (formerly al-Qaeda affiliated)",
    keyLeaders: ["Abu Mohammad al-Jolani"],
    arsenal: [
      "Captured Syrian Army equipment",
      "Locally-produced rockets and IEDs",
      "UAVs",
    ],
    description:
      "Dominant armed group in northwest Syria's Idlib pocket. Originated as Jabhat al-Nusra (al-Qaeda Syria affiliate); broke from al-Qaeda 2016. US-designated FTO since 2018.",
  },
  {
    slug: "syrian-democratic-forces",
    name: "Syrian Democratic Forces",
    aliases: ["SDF", "QSD"],
    type: "paramilitary",
    region: "Middle East",
    areaOfOperations: [
      "Northeast Syria (Autonomous Administration of NES / Rojava)",
    ],
    foundedYear: 2015,
    estimatedStrength: 100000,
    primarySponsorCountryCode: "US",
    ideology:
      "Heterogeneous; YPG-led with Arab and Christian components; democratic confederalism",
    arsenal: [
      "Coalition-supplied small arms",
      "Captured ISIS equipment",
      "ATGMs",
    ],
    notableOperations: [
      "Anti-ISIS campaign 2015-2019 (Battle of Raqqa, Battle of Baghuz)",
      "Defense vs. Turkish incursions",
    ],
    description:
      "Kurdish-led multi-ethnic alliance of armed groups in northeast Syria; principal US partner force in the anti-ISIS campaign. Türkiye considers the YPG component a terrorist organization.",
  },

  // ============ Africa ============
  {
    slug: "al-shabaab",
    name: "Harakat al-Shabaab al-Mujahideen",
    aliases: ["al-Shabaab", "HSM"],
    type: "militant_group",
    region: "Africa",
    areaOfOperations: [
      "Somalia (rural south-central)",
      "Kenya border",
      "Ethiopia border",
    ],
    foundedYear: 2006,
    estimatedStrength: 7000,
    ideology: "Sunni Islamist (al-Qaeda affiliate since 2012)",
    arsenal: [
      "Captured small arms",
      "VBIEDs",
      "IEDs",
      "Mortars",
      "ZU-23-2 anti-aircraft",
    ],
    notableOperations: [
      "Westgate Mall attack 2013 (Nairobi)",
      "Garissa University attack 2015",
      "Manda Bay attack 2020 (US/Kenyan base)",
    ],
    description:
      "Somali Sunni Islamist armed group; largest and wealthiest al-Qaeda affiliate. Subject of African Union ATMIS (formerly AMISOM) counter-insurgency.",
  },
  {
    slug: "boko-haram",
    name: "Boko Haram",
    aliases: ["Jama'atu Ahlis Sunna Lidda'awati wal-Jihad", "JAS"],
    type: "militant_group",
    region: "Africa",
    areaOfOperations: [
      "Northeastern Nigeria",
      "Lake Chad Basin (Cameroon, Chad, Niger)",
    ],
    foundedYear: 2002,
    estimatedStrength: 4000,
    ideology: "Sunni Islamist",
    arsenal: ["Captured Nigerian small arms", "VBIEDs", "Suicide vests"],
    notableOperations: [
      "Chibok schoolgirls abduction 2014",
      "Maiduguri attacks (multiple)",
    ],
    description:
      "Nigerian Sunni Islamist organization. Suicide-bomb tactics targeting civilians. Subject of Multinational Joint Task Force operations.",
  },
  {
    slug: "iswap",
    name: "Islamic State West Africa Province",
    aliases: ["ISWAP", "ISIS West Africa"],
    type: "militant_group",
    region: "Africa",
    areaOfOperations: ["Lake Chad Basin", "Northeastern Nigeria"],
    foundedYear: 2015,
    estimatedStrength: 5000,
    ideology: "Sunni Islamist (Islamic State affiliate)",
    arsenal: [
      "Captured small arms",
      "VBIEDs",
      "Heavy weapons captured from NA",
    ],
    description:
      "Splinter from Boko Haram; Islamic State affiliate. Has overtaken Boko Haram as the dominant Sunni Islamist threat in Lake Chad Basin since 2019.",
  },
  {
    slug: "jnim",
    name: "Jama'at Nasr al-Islam wal Muslimin",
    aliases: ["JNIM", "Group for the Support of Islam and Muslims"],
    type: "militant_group",
    region: "Africa",
    areaOfOperations: [
      "Mali",
      "Burkina Faso",
      "Niger",
      "Côte d'Ivoire / Benin border",
    ],
    foundedYear: 2017,
    estimatedStrength: 6000,
    ideology: "Sunni Islamist (al-Qaeda affiliate)",
    arsenal: [
      "Captured small arms",
      "Toyota technical pickups",
      "IEDs",
      "Captured Russian/Chinese arms",
    ],
    description:
      "Al-Qaeda's Sahel umbrella formed by merger of Ansar Dine, AQIM-Sahara, MUJAO, and Macina Liberation Front. Dominant insurgent force in central Sahel.",
  },
  {
    slug: "isgs",
    name: "Islamic State Sahel Province",
    aliases: ["ISGS", "ISSP", "Islamic State in the Greater Sahara"],
    type: "militant_group",
    region: "Africa",
    areaOfOperations: [
      "Mali",
      "Burkina Faso",
      "Niger (Liptako-Gourma tri-border)",
    ],
    foundedYear: 2015,
    estimatedStrength: 2000,
    ideology: "Sunni Islamist (Islamic State affiliate)",
    arsenal: ["Captured small arms and pickups"],
    description:
      "Islamic State's Sahel affiliate; rival to JNIM. Notorious for the 2017 Tongo Tongo ambush that killed four US Green Berets.",
  },
  {
    slug: "aqim",
    name: "Al-Qaeda in the Islamic Maghreb",
    aliases: ["AQIM"],
    type: "militant_group",
    region: "Africa",
    areaOfOperations: ["Maghreb", "Sahel", "Libya"],
    foundedYear: 2007,
    estimatedStrength: 1000,
    ideology: "Sunni Islamist (al-Qaeda affiliate)",
    arsenal: ["Captured small arms", "Toyota technicals", "IEDs"],
    description:
      "North African al-Qaeda branch (originated from Algerian GSPC). Operationally subsumed under JNIM in the Sahel since 2017.",
  },
  {
    slug: "isis-mozambique",
    name: "Islamic State Mozambique",
    aliases: ["ISIS-M", "Ansar al-Sunna (regional)"],
    type: "militant_group",
    region: "Africa",
    areaOfOperations: ["Cabo Delgado, Mozambique", "Mtwara, Tanzania (border)"],
    foundedYear: 2017,
    estimatedStrength: 2500,
    ideology: "Sunni Islamist (Islamic State affiliate)",
    arsenal: ["Captured Mozambican military small arms", "ATGMs"],
    description:
      "Cabo Delgado insurgency targeting LNG developments. Subject of SADC SAMIM and Rwandan deployment since 2021.",
  },
  {
    slug: "lord-resistance-army",
    name: "Lord's Resistance Army",
    aliases: ["LRA"],
    type: "militant_group",
    region: "Africa",
    areaOfOperations: ["DRC", "Central African Republic", "South Sudan"],
    foundedYear: 1987,
    estimatedStrength: 200,
    ideology: "Acholi nationalism / messianic Christian extremism",
    keyLeaders: ["Joseph Kony"],
    arsenal: ["Captured small arms"],
    description:
      "Once-major Ugandan insurgent group; reduced to small armed bands operating across Central Africa. Subject of African Union Regional Task Force.",
  },
  {
    slug: "adf",
    name: "Allied Democratic Forces",
    aliases: ["ADF", "Madina at Tauheed Wau Mujahedeen", "ISIS-DRC", "ISCAP"],
    type: "militant_group",
    region: "Africa",
    areaOfOperations: ["Eastern DRC (North Kivu, Ituri)", "Western Uganda"],
    foundedYear: 1995,
    estimatedStrength: 1500,
    ideology: "Sunni Islamist (Islamic State affiliate since 2019)",
    arsenal: ["Captured small arms", "IEDs"],
    description:
      "Ugandan-origin armed group based in eastern DRC; pledged allegiance to ISIS as Islamic State Central Africa Province (ISCAP). Subject of joint Ugandan-DRC counter-insurgency.",
  },
  {
    slug: "m23",
    name: "Mouvement du 23 mars",
    aliases: ["M23"],
    type: "militant_group",
    region: "Africa",
    areaOfOperations: ["Eastern DRC (North Kivu)"],
    foundedYear: 2012,
    estimatedStrength: 8000,
    primarySponsorCountryCode: "RW",
    ideology: "Tutsi nationalism; protection of Congolese Tutsis (claimed)",
    arsenal: [
      "Captured FARDC equipment",
      "Reportedly Rwandan-supplied advanced systems",
    ],
    description:
      "Tutsi-led rebel group active in eastern DRC; UN Group of Experts reports document Rwandan support. Subject of EAC and SADC deployments.",
  },
  {
    slug: "raia-mutomboki",
    name: "Raia Mutomboki",
    aliases: ["Outraged Citizens"],
    type: "militant_group",
    region: "Africa",
    areaOfOperations: ["Eastern DRC (South Kivu, Maniema)"],
    foundedYear: 2005,
    estimatedStrength: 5000,
    ideology: "Local self-defense (heterogeneous Mai-Mai movement)",
    arsenal: ["Locally-made firearms", "Captured small arms"],
    description:
      "Decentralized network of Mai-Mai local-defense militias in eastern DRC; numerous factions with shifting allegiances.",
  },
  {
    slug: "fdlr",
    name: "Forces démocratiques de libération du Rwanda",
    aliases: ["FDLR"],
    type: "militant_group",
    region: "Africa",
    areaOfOperations: ["Eastern DRC"],
    foundedYear: 2000,
    estimatedStrength: 600,
    ideology:
      "Hutu nationalism; descended from former Rwandan Armed Forces (FAR) and Interahamwe",
    arsenal: ["Captured small arms"],
    description:
      "Hutu-extremist armed group in eastern DRC composed partly of veterans of the 1994 Rwandan genocide. Cited by Rwanda as justification for its eastern DRC posture.",
  },
  {
    slug: "rsf-sudan",
    name: "Rapid Support Forces (Sudan)",
    aliases: ["RSF", "Janjaweed-derived"],
    type: "paramilitary",
    region: "Africa",
    areaOfOperations: ["Sudan (especially Darfur, Khartoum, Gezira)"],
    foundedYear: 2013,
    estimatedStrength: 100000,
    ideology: "Tribal-based; political-economic interests of leadership",
    keyLeaders: ["Mohamed Hamdan 'Hemedti' Dagalo"],
    arsenal: [
      "Toyota technicals (~10,000)",
      "Captured Sudanese army equipment",
      "UAE-supplied weapons (alleged)",
    ],
    notableOperations: ["Sudanese civil war 2023-present (vs. SAF)"],
    description:
      "Sudanese paramilitary force grown from the Janjaweed; principal combatant against the Sudanese Armed Forces in the 2023-present civil war.",
  },
  {
    slug: "rsf-congo",
    name: "M23 / AFC alliance (DRC eastern conflict 2024-2025)",
    aliases: ["AFC", "Alliance Fleuve Congo"],
    type: "militant_group",
    region: "Africa",
    areaOfOperations: ["Eastern DRC (Goma, Bukavu)"],
    foundedYear: 2023,
    estimatedStrength: 10000,
    primarySponsorCountryCode: "RW",
    ideology: "Tutsi nationalism + heterogeneous opposition coalition",
    keyLeaders: ["Corneille Nangaa (political leadership)"],
    arsenal: [
      "Captured FARDC equipment",
      "Rwandan-supplied advanced weapons (alleged)",
    ],
    description:
      "Political-military alliance encompassing M23 and other anti-Kinshasa armed factions; captured Goma and Bukavu in early 2025.",
  },
  {
    slug: "wagner-africa-corps",
    name: "Africa Corps (Russian Ministry of Defense)",
    aliases: ["Russia Africa Corps", "Wagner successor structure"],
    type: "private_military_company",
    region: "Africa",
    areaOfOperations: [
      "Mali",
      "Burkina Faso",
      "Central African Republic",
      "Libya",
      "Sudan",
    ],
    foundedYear: 2024,
    estimatedStrength: 15000,
    primarySponsorCountryCode: "RU",
    ideology: "Russian state interests",
    arsenal: [
      "Russian small arms",
      "BMP-1/2 IFV",
      "T-72 (limited)",
      "Mi-8/17 helicopters",
    ],
    description:
      "Russian Ministry of Defense-controlled successor to Wagner Group operations in Africa. Provides regime security, counter-insurgency, and resource-extraction security to client states.",
  },
  {
    slug: "tplf",
    name: "Tigray People's Liberation Front",
    aliases: ["TPLF"],
    type: "paramilitary",
    region: "Africa",
    areaOfOperations: ["Tigray Region, Ethiopia"],
    foundedYear: 1975,
    estimatedStrength: 250000,
    ideology: "Tigrayan nationalism (originally Marxist-Leninist)",
    arsenal: ["Captured ENDF equipment", "ATGMs", "Heavy mortars"],
    description:
      "Ethiopian Tigrayan political party and former dominant force in the EPRDF coalition. Combatant in the 2020-2022 Tigray War against the Ethiopian federal government.",
  },
  {
    slug: "polisario",
    name: "Polisario Front",
    aliases: ["Frente Polisario", "Sahrawi People's Liberation Army"],
    type: "separatist",
    region: "Africa",
    areaOfOperations: ["Western Sahara", "Tindouf, Algeria (HQ in exile)"],
    foundedYear: 1973,
    estimatedStrength: 6000,
    primarySponsorCountryCode: "DZ",
    ideology: "Sahrawi nationalism",
    arsenal: ["Algerian-supplied small arms", "T-55 / T-62 (legacy)", "BM-21"],
    description:
      "Sahrawi independence movement and military force opposing Moroccan control of Western Sahara. Backed by Algeria; ceasefire (1991) collapsed in 2020.",
  },
];
