import type { WeaponSystem } from "./types";

export const weaponsB: WeaponSystem[] = [
  // ICBMs / SLBMs
  {
    slug: "minuteman-iii",
    name: "LGM-30G Minuteman III",
    category: "icbm",
    originCountryCode: "US",
    yearIntroduced: 1970,
    rangeKm: 13000,
    payload: "W78 (335 kt) or W87 (300 kt)",
    operators: ["US"],
    notableFeatures:
      "MIRV-capable (single-warhead per New START); Sentinel replacement program in development",
    description:
      "Sole US land-based ICBM; 400 missiles deployed across Malmstrom, Minot, F.E. Warren.",
  },
  {
    slug: "trident-ii",
    name: "UGM-133A Trident II D5",
    category: "slbm",
    originCountryCode: "US",
    yearIntroduced: 1990,
    rangeKm: 12000,
    payload: "W76-1 (100 kt) / W76-2 (5-7 kt low-yield) / W88 (475 kt)",
    operators: ["US", "GB"],
    notableFeatures:
      "Shared with UK Vanguard SSBNs; W76-2 fielded 2019 for low-yield response",
    description:
      "US/UK sea-based strategic deterrent; deployed on Ohio (US) and Vanguard (UK) classes.",
  },
  {
    slug: "rs-28-sarmat",
    name: "RS-28 Sarmat",
    category: "icbm",
    originCountryCode: "RU",
    yearIntroduced: 2023,
    rangeKm: 18000,
    payload: "10+ MIRV warheads or Avangard HGV",
    operators: ["RU"],
    notableFeatures:
      "Heavy liquid-fuel ICBM; can carry hypersonic glide vehicles",
    description:
      "Russian heavy ICBM successor to R-36M Voevoda; combat duty announced 2023.",
  },
  {
    slug: "yars",
    name: "RS-24 Yars",
    category: "icbm",
    originCountryCode: "RU",
    yearIntroduced: 2010,
    rangeKm: 11000,
    payload: "MIRV (3-4 warheads typical)",
    operators: ["RU"],
    notableFeatures:
      "Road-mobile and silo-based variants; principal modern Russian ICBM",
    description:
      "Russian solid-fuel ICBM; backbone of contemporary Strategic Rocket Forces.",
  },
  {
    slug: "bulava",
    name: "RSM-56 Bulava",
    category: "slbm",
    originCountryCode: "RU",
    yearIntroduced: 2018,
    rangeKm: 8300,
    payload: "MIRV (6-10 warheads)",
    operators: ["RU"],
    notableFeatures: "Sole modern Russian SLBM",
    description: "Russian solid-fuel SLBM deployed on Borei-class SSBN.",
  },
  {
    slug: "m51",
    name: "M51 SLBM",
    category: "slbm",
    originCountryCode: "FR",
    yearIntroduced: 2010,
    rangeKm: 9000,
    payload: "TN-75 / TNO MIRV warheads",
    operators: ["FR"],
    notableFeatures: "Three-stage solid-fuel SLBM; M51.3 entering service",
    description:
      "French sea-based strategic deterrent; deployed on Triomphant-class SSBNs.",
  },
  {
    slug: "df-41",
    name: "DF-41",
    category: "icbm",
    originCountryCode: "CN",
    yearIntroduced: 2017,
    rangeKm: 14000,
    payload: "MIRV (up to 10 warheads claimed)",
    operators: ["CN"],
    notableFeatures:
      "Road-mobile / silo / rail; centerpiece of Chinese arsenal expansion",
    description:
      "PLA Rocket Force's principal modern ICBM; central to projected 1500-warhead arsenal by 2035.",
  },
  {
    slug: "jl-3",
    name: "JL-3",
    category: "slbm",
    originCountryCode: "CN",
    yearIntroduced: 2022,
    rangeKm: 10000,
    payload: "MIRV nuclear",
    operators: ["CN"],
    notableFeatures:
      "Provides PLAN SSBNs intercontinental reach from Chinese bastions",
    description:
      "Chinese third-generation SLBM deployed on Type 094 Jin-class SSBNs.",
  },
  {
    slug: "agni-v",
    name: "Agni-V",
    category: "icbm",
    originCountryCode: "IN",
    yearIntroduced: 2018,
    rangeKm: 5500,
    payload: "MIRV (since 2024)",
    operators: ["IN"],
    notableFeatures:
      "First Indian ICBM-class missile; MIRV capability demonstrated 2024",
    description:
      "Indian three-stage solid-fuel ICBM; central to credible minimum deterrence.",
  },
  {
    slug: "k-4",
    name: "K-4 SLBM",
    category: "slbm",
    originCountryCode: "IN",
    yearIntroduced: 2020,
    rangeKm: 3500,
    payload: "Nuclear",
    operators: ["IN"],
    notableFeatures: "Indigenous SLBM for Arihant-class SSBN",
    description: "Indian sea-based deterrent missile.",
  },
  {
    slug: "hwasong-18",
    name: "Hwasong-18",
    category: "icbm",
    originCountryCode: "KP",
    yearIntroduced: 2023,
    rangeKm: 15000,
    payload: "Nuclear (MIRV claimed)",
    operators: ["KP"],
    notableFeatures: "First DPRK solid-fuel ICBM; rapid launch posture",
    description:
      "DPRK solid-fuel ICBM; provides survivable second-strike option.",
  },
  {
    slug: "shaheen-iii",
    name: "Shaheen-III",
    category: "ballistic_missile",
    originCountryCode: "PK",
    yearIntroduced: 2015,
    rangeKm: 2750,
    payload: "Nuclear or conventional",
    operators: ["PK"],
    notableFeatures: "Pakistan's longest-range MRBM",
    description:
      "Pakistani solid-fuel medium-range ballistic missile reaching across the entire Indian land mass.",
  },
  // Carriers and amphibs
  {
    slug: "ford-class-cvn",
    name: "Ford-class supercarrier (CVN-78)",
    category: "carrier",
    originCountryCode: "US",
    yearIntroduced: 2017,
    payload: "60+ aircraft including F-35C, F/A-18E/F, EA-18G",
    operators: ["US"],
    notableFeatures: "EMALS catapults; AAG arresting gear; reduced crew",
    description:
      "Latest US nuclear supercarrier class; lead ship USS Gerald R. Ford operational.",
  },
  {
    slug: "nimitz-class-cvn",
    name: "Nimitz-class supercarrier",
    category: "carrier",
    originCountryCode: "US",
    yearIntroduced: 1975,
    payload: "60+ aircraft",
    operators: ["US"],
    notableFeatures: "10 hulls in commission",
    description: "Backbone US supercarrier class; transitioning to Ford-class.",
  },
  {
    slug: "queen-elizabeth-cv",
    name: "Queen Elizabeth-class carrier",
    category: "carrier",
    originCountryCode: "GB",
    yearIntroduced: 2017,
    payload: "Up to 36 F-35B + Merlin / Wildcat",
    operators: ["GB"],
    notableFeatures: "STOVL carrier with two islands; ramp-launched F-35B",
    description:
      "UK's flat-deck STOVL strike carriers; HMS Queen Elizabeth and HMS Prince of Wales.",
  },
  {
    slug: "charles-de-gaulle",
    name: "Charles de Gaulle (R91)",
    category: "carrier",
    originCountryCode: "FR",
    yearIntroduced: 2001,
    payload: "30+ Rafale M, E-2C/D Hawkeye, NH90",
    operators: ["FR"],
    notableFeatures: "Only nuclear-powered carrier outside US Navy",
    description: "French CATOBAR carrier; flagship of the Marine nationale.",
  },
  {
    slug: "type-003-fujian",
    name: "Type 003 Fujian (CV-18)",
    category: "carrier",
    originCountryCode: "CN",
    yearIntroduced: 2024,
    payload: "Estimated 40+ J-15T / J-35; KJ-600 AEW",
    operators: ["CN"],
    notableFeatures:
      "First Chinese CATOBAR carrier with electromagnetic catapults",
    description: "Latest PLAN aircraft carrier; sea trials underway.",
  },
  {
    slug: "izumo-class",
    name: "Izumo-class DDH",
    category: "carrier",
    originCountryCode: "JP",
    yearIntroduced: 2015,
    payload: "F-35B (post-conversion); SH-60K helicopters",
    operators: ["JP"],
    notableFeatures: "Conversion to support F-35B operations completed by 2027",
    description:
      "JMSDF helicopter destroyers; converting to STOVL light carriers.",
  },
  {
    slug: "america-class-lha",
    name: "America-class LHA",
    category: "carrier",
    originCountryCode: "US",
    yearIntroduced: 2014,
    payload: "Up to 20 F-35B + MV-22B + AH-1Z + UH-1Y",
    operators: ["US"],
    notableFeatures: "Aviation-centric amphibious assault ship",
    description:
      "US Marine STOVL carrier; central to distributed maritime operations.",
  },
  // Submarines
  {
    slug: "ohio-ssbn",
    name: "Ohio-class SSBN",
    category: "submarine",
    originCountryCode: "US",
    yearIntroduced: 1981,
    payload: "20 Trident II D5 SLBMs",
    operators: ["US"],
    notableFeatures:
      "Backbone of US sea-based deterrent; replaced by Columbia from 2030",
    description:
      "US strategic ballistic-missile submarine class; 14 SSBNs in service.",
  },
  {
    slug: "columbia-ssbn",
    name: "Columbia-class SSBN",
    category: "submarine",
    originCountryCode: "US",
    yearIntroduced: 2031,
    payload: "16 Trident II D5LE missiles",
    operators: ["US"],
    notableFeatures: "Life-of-ship reactor; quieter than Ohio",
    description:
      "Next-generation US SSBN under construction; lead ship USS District of Columbia.",
  },
  {
    slug: "virginia-class",
    name: "Virginia-class SSN",
    category: "submarine",
    originCountryCode: "US",
    yearIntroduced: 2004,
    payload: "Tomahawk Block V; Mk 48 ADCAP; UUVs",
    operators: ["US", "AU (planned)"],
    notableFeatures:
      "Block V adds Virginia Payload Module (28 additional Tomahawks)",
    description:
      "Premier Western SSN; AUKUS Pillar I rotational deployment to Australia.",
  },
  {
    slug: "borei-class",
    name: "Borei / Borei-A class SSBN",
    category: "submarine",
    originCountryCode: "RU",
    yearIntroduced: 2013,
    payload: "16 RSM-56 Bulava SLBMs",
    operators: ["RU"],
    notableFeatures: "Replaces Delta IV; Borei-A quieter and improved sensors",
    description:
      "Russian fourth-generation SSBN; eight planned across Northern and Pacific Fleets.",
  },
  {
    slug: "yasen-class",
    name: "Yasen / Yasen-M class SSGN/SSN",
    category: "submarine",
    originCountryCode: "RU",
    yearIntroduced: 2014,
    payload: "Kalibr / Oniks / Zircon (32 in VLS)",
    operators: ["RU"],
    notableFeatures: "Russia's most modern attack submarine; multi-mission",
    description:
      "Severodvinsk-class with Kalibr/Oniks/Zircon long-range strike capability.",
  },
  {
    slug: "type-094",
    name: "Type 094 Jin-class SSBN",
    category: "submarine",
    originCountryCode: "CN",
    yearIntroduced: 2007,
    payload: "12 JL-2 / JL-3 SLBMs",
    operators: ["CN"],
    notableFeatures: "PLA Navy nuclear deterrent platform; Yulin/Hainan based",
    description:
      "Chinese SSBN class supporting near-continuous deterrent patrols.",
  },
  {
    slug: "type-093",
    name: "Type 093 Shang-class SSN",
    category: "submarine",
    originCountryCode: "CN",
    yearIntroduced: 2006,
    payload: "Torpedoes; YJ-18 cruise missiles (Type 093B)",
    operators: ["CN"],
    notableFeatures: "Type 093B variant adds VLS",
    description: "PLA Navy SSN class; principal Chinese attack submarine.",
  },
  {
    slug: "astute-class",
    name: "Astute-class SSN",
    category: "submarine",
    originCountryCode: "GB",
    yearIntroduced: 2010,
    payload: "Tomahawk Block V; Spearfish",
    operators: ["GB"],
    notableFeatures: "Pump-jet propulsor; PWR2 reactor",
    description:
      "Royal Navy attack submarine class; AUKUS technology basis for SSN-AUKUS.",
  },
  {
    slug: "vanguard-class",
    name: "Vanguard-class SSBN",
    category: "submarine",
    originCountryCode: "GB",
    yearIntroduced: 1993,
    payload: "16 Trident II D5 SLBMs",
    operators: ["GB"],
    notableFeatures:
      "UK CASD platform replaced by Dreadnought-class from 2030s",
    description:
      "UK strategic submarine class providing continuous-at-sea deterrence.",
  },
  {
    slug: "suffren-class",
    name: "Suffren-class (Barracuda) SSN",
    category: "submarine",
    originCountryCode: "FR",
    yearIntroduced: 2022,
    payload: "Naval Cruise Missile (MdCN); F21 torpedoes",
    operators: ["FR"],
    notableFeatures:
      "First French SSN with land-attack cruise missile capability",
    description:
      "French nuclear attack submarine class with stand-off strike role.",
  },
  {
    slug: "soryu-class",
    name: "Sōryū / Taigei class SSK",
    category: "submarine",
    originCountryCode: "JP",
    yearIntroduced: 2009,
    payload: "Type 89 torpedoes; Harpoon",
    operators: ["JP"],
    notableFeatures: "Lithium-ion batteries on Taigei follow-on",
    description:
      "JMSDF AIP/Li-ion submarine class; world's largest non-nuclear SSK.",
  },
  // Tanks and IFVs
  {
    slug: "m1a2-abrams",
    name: "M1A2 SEPv3 Abrams",
    category: "tank",
    originCountryCode: "US",
    yearIntroduced: 2017,
    payload: "120 mm M256 smoothbore",
    operators: ["US", "AU", "PL", "TW", "RO", "EG", "SA", "KW", "MA", "IQ"],
    notableFeatures: "Trophy APS in service",
    description: "Latest US main battle tank variant; widely exported.",
  },
  {
    slug: "leopard-2a7",
    name: "Leopard 2A7 / 2A7+ / 2A8",
    category: "tank",
    originCountryCode: "DE",
    yearIntroduced: 2014,
    payload: "120 mm Rh-120 L/55A1",
    operators: ["DE", "DK", "HU", "QA", "SG", "ES", "GR", "PL"],
    notableFeatures: "Most advanced Leopard 2 variant; Trophy on 2A8",
    description: "Premier European MBT; 2A8 in production for Bundeswehr.",
  },
  {
    slug: "challenger-3",
    name: "Challenger 3",
    category: "tank",
    originCountryCode: "GB",
    yearIntroduced: 2027,
    payload: "120 mm Rh-120 L/55A1",
    operators: ["GB"],
    notableFeatures: "Smoothbore 120 mm; Trophy APS",
    description:
      "British upgrade replacing Challenger 2; entering service late this decade.",
  },
  {
    slug: "k2-black-panther",
    name: "K2 Black Panther",
    category: "tank",
    originCountryCode: "KR",
    yearIntroduced: 2014,
    payload: "120 mm CN08",
    operators: ["KR", "PL (K2GF/PL)", "NO", "TR (Altay tech transfer)"],
    notableFeatures: "Active hydropneumatic suspension; major export wins",
    description: "South Korean MBT; Polish K2PL co-production at Bumar-Łabędy.",
  },
  {
    slug: "t-90m",
    name: "T-90M Proryv",
    category: "tank",
    originCountryCode: "RU",
    yearIntroduced: 2020,
    payload: "125 mm 2A46M-5",
    operators: ["RU", "IN (license)"],
    notableFeatures: "Relikt ERA; Kalina FCS",
    description:
      "Modern Russian MBT; combat losses heavy in Ukraine despite upgrades.",
  },
  {
    slug: "type-99a",
    name: "Type 99A",
    category: "tank",
    originCountryCode: "CN",
    yearIntroduced: 2011,
    payload: "125 mm autoloader",
    operators: ["CN"],
    notableFeatures: "Premier PLAGF MBT",
    description:
      "Chinese third-generation MBT; mainstay of group army armoured brigades.",
  },
  {
    slug: "merkava-mk4",
    name: "Merkava Mk4 / Mk5 Barak",
    category: "tank",
    originCountryCode: "IL",
    yearIntroduced: 2004,
    payload: "120 mm MG253",
    operators: ["IL"],
    notableFeatures: "Trophy APS; rear crew compartment for infantry",
    description:
      "Israeli MBT family; latest Mk5 Barak entering service 2023-2024.",
  },
  // Artillery / MLRS
  {
    slug: "himars",
    name: "M142 HIMARS",
    category: "artillery",
    originCountryCode: "US",
    yearIntroduced: 2010,
    rangeKm: 300,
    payload: "GMLRS; ATACMS Block IA; PrSM",
    operators: [
      "US",
      "PL",
      "RO",
      "EE",
      "LV",
      "LT",
      "AU",
      "SG",
      "AE",
      "TW",
      "MA",
      "JO",
    ],
    notableFeatures: "Highly mobile; PrSM range 500+ km",
    description: "Wheeled MLRS; transformative effect demonstrated in Ukraine.",
  },
  {
    slug: "k9-thunder",
    name: "K9 Thunder",
    category: "artillery",
    originCountryCode: "KR",
    yearIntroduced: 1999,
    rangeKm: 40,
    payload: "155 mm K307 / K310",
    operators: ["KR", "PL", "FI", "NO", "EE", "TR", "IN (Vajra-T)", "AU", "EG"],
    notableFeatures: "Top global self-propelled artillery exporter",
    description: "South Korean self-propelled howitzer; standard NATO 155 mm.",
  },
  {
    slug: "pzh-2000",
    name: "Panzerhaubitze 2000",
    category: "artillery",
    originCountryCode: "DE",
    yearIntroduced: 1998,
    rangeKm: 40,
    operators: ["DE", "IT", "NL", "GR", "HR", "QA", "HU", "LT", "UA"],
    notableFeatures: "MRSI capability (multi-round simultaneous impact)",
    description:
      "German 155 mm self-propelled howitzer; combat-proven in Ukraine.",
  },
  {
    slug: "caesar",
    name: "CAESAR self-propelled howitzer",
    category: "artillery",
    originCountryCode: "FR",
    yearIntroduced: 2008,
    rangeKm: 40,
    operators: ["FR", "DK", "BE", "CZ", "TH", "ID", "SA", "LB", "MA", "UA"],
    notableFeatures: "Truck-mounted 155 mm; rapid relocation",
    description: "French wheeled SP howitzer; major Ukrainian frontline asset.",
  },
];
