import type { WeaponSystem } from "./types";

export const weaponsC: WeaponSystem[] = [
  // ============ UAVs / Loitering Munitions ============
  {
    slug: "mq-9-reaper",
    name: "MQ-9 Reaper",
    category: "uav",
    originCountryCode: "US",
    yearIntroduced: 2007,
    rangeKm: 1850,
    payload: "AGM-114 Hellfire, GBU-12 Paveway II, GBU-38 JDAM",
    operators: ["US", "GB", "FR", "ES", "IT", "NL", "AU", "JP", "TW"],
    notableFeatures:
      "Persistent ISR + strike; SeaGuardian variant for maritime",
    description:
      "Premier Western armed MALE UAV; backbone of US counterterrorism strike operations.",
  },
  {
    slug: "rq-4-global-hawk",
    name: "RQ-4 Global Hawk",
    category: "uav",
    originCountryCode: "US",
    yearIntroduced: 2001,
    rangeKm: 22780,
    payload: "Multi-INT sensor suite (no weapons)",
    operators: ["US", "KR", "JP", "DE (legacy Euro Hawk)"],
    notableFeatures: "HALE platform with 30+ hour endurance",
    description:
      "High-altitude long-endurance ISR UAV; critical for theater-wide reconnaissance.",
  },
  {
    slug: "mq-4-triton",
    name: "MQ-4C Triton",
    category: "uav",
    originCountryCode: "US",
    yearIntroduced: 2018,
    rangeKm: 15000,
    payload: "MFAS radar, EO/IR, ESM (no weapons)",
    operators: ["US", "AU"],
    notableFeatures:
      "Maritime variant of Global Hawk for broad-area maritime surveillance",
    description:
      "US Navy/Australian wide-area maritime ISR UAV; replacing P-3 Orion roles.",
  },
  {
    slug: "switchblade-300",
    name: "AeroVironment Switchblade 300",
    category: "uav",
    originCountryCode: "US",
    yearIntroduced: 2013,
    rangeKm: 10,
    payload: "Anti-personnel warhead (~600g)",
    operators: ["US", "UA", "GB", "NL", "TW (procurement)"],
    notableFeatures: "Tube-launched man-portable loitering munition",
    description:
      "Backpack-portable kamikaze drone; widely supplied to Ukraine.",
  },
  {
    slug: "switchblade-600",
    name: "AeroVironment Switchblade 600",
    category: "uav",
    originCountryCode: "US",
    yearIntroduced: 2020,
    rangeKm: 80,
    payload: "Anti-armor shaped-charge warhead",
    operators: ["US", "UA"],
    notableFeatures: "Larger kin of Switchblade 300; anti-armor capability",
    description:
      "Tube-launched anti-tank loitering munition deployed in Ukraine.",
  },
  {
    slug: "bayraktar-tb2",
    name: "Bayraktar TB2",
    category: "uav",
    originCountryCode: "TR",
    yearIntroduced: 2014,
    rangeKm: 150,
    payload: "MAM-L / MAM-C laser-guided munitions",
    operators: [
      "TR",
      "AZ",
      "UA",
      "QA",
      "PL",
      "MA",
      "ET",
      "Various African states",
    ],
    notableFeatures: "Combat-proven in Nagorno-Karabakh, Libya, Syria, Ukraine",
    description:
      "Turkish armed MALE UAV; transformed UCAV warfare and exports.",
  },
  {
    slug: "bayraktar-akinci",
    name: "Bayraktar Akıncı",
    category: "uav",
    originCountryCode: "TR",
    yearIntroduced: 2021,
    rangeKm: 7500,
    payload: "SOM-A cruise missile, MAM family, Mk.81/82/83 bombs",
    operators: ["TR", "PK", "AZ", "LY"],
    notableFeatures: "HALE-class twin-engine UCAV with cruise-missile carriage",
    description:
      "Turkish heavy UCAV; carries SOM-A air-launched cruise missile.",
  },
  {
    slug: "kizilelma",
    name: "Bayraktar Kızılelma",
    category: "uav",
    originCountryCode: "TR",
    yearIntroduced: 2024,
    rangeKm: 925,
    operators: ["TR"],
    notableFeatures:
      "Subsonic stealth UCAV with internal weapons bay; will operate from TCG Anadolu",
    description: "Turkish carrier-capable stealth combat UAV.",
  },
  {
    slug: "shahed-136",
    name: "Shahed-136 / Geran-2",
    category: "uav",
    originCountryCode: "IR",
    yearIntroduced: 2021,
    rangeKm: 2500,
    payload: "~50 kg warhead",
    operators: ["IR", "RU (Geran-2 variant)", "Houthis"],
    notableFeatures:
      "Cheap mass-production loitering munition; Russian production at Alabuga",
    description:
      "Iranian-designed long-range loitering munition; widely used by Russia against Ukraine and by Houthis in Red Sea.",
  },
  {
    slug: "lancet",
    name: "ZALA Lancet",
    category: "uav",
    originCountryCode: "RU",
    yearIntroduced: 2020,
    rangeKm: 70,
    payload: "3 kg warhead",
    operators: ["RU"],
    notableFeatures: "Recon-strike loitering munition; used heavily in Ukraine",
    description:
      "Russian short-range loitering munition; primary anti-armor and anti-artillery threat.",
  },
  {
    slug: "wingloong-2",
    name: "Wing Loong II",
    category: "uav",
    originCountryCode: "CN",
    yearIntroduced: 2017,
    rangeKm: 1500,
    payload: "AKD-10, BA-7, AR-1, AR-2",
    operators: ["CN", "AE", "EG", "KZ", "PK", "RS", "ID"],
    notableFeatures:
      "Chinese Reaper-equivalent; dominant export armed UAV in MENA",
    description: "Chinese MALE UCAV; major Chinese arms-export success.",
  },
  {
    slug: "ch-5",
    name: "CASC CH-5 'Rainbow'",
    category: "uav",
    originCountryCode: "CN",
    yearIntroduced: 2018,
    rangeKm: 6500,
    payload: "AR-1/2 missile, FT-9/10 bombs",
    operators: ["CN", "PK", "AE", "DZ", "EG"],
    notableFeatures: "Chinese armed MALE UCAV class-equivalent to MQ-9",
    description:
      "Major export competitor to Wing Loong II; AR-1 anti-armor missile carriage.",
  },
  {
    slug: "heron-tp",
    name: "IAI Heron TP",
    category: "uav",
    originCountryCode: "IL",
    yearIntroduced: 2010,
    rangeKm: 7400,
    payload: "Various Israeli air-to-ground munitions",
    operators: ["IL", "DE (lease)", "IN", "AZ"],
    notableFeatures: "MALE UAV with 30+ hour endurance",
    description:
      "Israeli HALE/MALE UAV; widely operated in non-export form by various countries.",
  },
  {
    slug: "anka-s",
    name: "TUSAS Anka-S",
    category: "uav",
    originCountryCode: "TR",
    yearIntroduced: 2017,
    rangeKm: 250,
    payload: "MAM-L / MAM-C / Roketsan Mizrak-U",
    operators: ["TR", "TN"],
    notableFeatures: "Turkish state-owned alternative to Baykar TB2",
    description: "Turkish Aerospace Industries armed MALE UAV.",
  },

  // ============ Additional fighters ============
  {
    slug: "su-34",
    name: "Su-34 Fullback",
    category: "fighter_aircraft",
    originCountryCode: "RU",
    yearIntroduced: 2014,
    rangeKm: 4000,
    speedMach: 1.8,
    payload: "Up to 8 t including KAB-500/1500, Kh-29, FAB-500",
    operators: ["RU", "DZ"],
    notableFeatures: "Side-by-side cockpit; long-range strike role",
    description:
      "Russian frontline strike fighter; carrier of UMPK glide bombs in Ukraine.",
  },
  {
    slug: "su-35s",
    name: "Su-35S Flanker-E",
    category: "fighter_aircraft",
    originCountryCode: "RU",
    yearIntroduced: 2014,
    rangeKm: 3600,
    speedMach: 2.25,
    payload: "R-77, R-73, Kh-31, Kh-35",
    operators: ["RU", "EG (procurement)", "IR (procurement)"],
    notableFeatures: "Thrust-vectoring; Irbis-E PESA radar",
    description:
      "Russia's most capable 4.5-gen fighter; export to Iran reported.",
  },
  {
    slug: "j-16",
    name: "Shenyang J-16",
    category: "fighter_aircraft",
    originCountryCode: "CN",
    yearIntroduced: 2015,
    rangeKm: 4000,
    payload: "PL-15, PL-10, YJ-83K, KD-88",
    operators: ["CN"],
    notableFeatures: "Chinese Su-30 derivative; specialized J-16D EW variant",
    description:
      "PLA Air Force Flanker-derivative; backbone Chinese strike fighter.",
  },
  {
    slug: "tejas-mk1a",
    name: "HAL Tejas Mk1A",
    category: "fighter_aircraft",
    originCountryCode: "IN",
    yearIntroduced: 2024,
    rangeKm: 3000,
    speedMach: 1.6,
    payload: "Astra, Derby, R-73, MICA, Brimstone",
    operators: ["IN"],
    notableFeatures: "Indigenous Indian LCA; Mk2 in development",
    description:
      "Indian indigenous light combat aircraft; 83 ordered for IAF replacing MiG-21.",
  },
  {
    slug: "kf-21",
    name: "KAI KF-21 Boramae",
    category: "fighter_aircraft",
    originCountryCode: "KR",
    yearIntroduced: 2025,
    rangeKm: 2900,
    speedMach: 1.8,
    payload: "Meteor, IRIS-T, AIM-120",
    operators: ["KR", "ID (joint dev partner)"],
    notableFeatures: "South Korean 4.5-gen indigenous fighter; AESA radar",
    description:
      "Korean Boramae fighter; replaces F-4/F-5 fleet starting late 2025.",
  },
  {
    slug: "f-cK-1",
    name: "AIDC F-CK-1 Ching-Kuo (IDF)",
    category: "fighter_aircraft",
    originCountryCode: "TW",
    yearIntroduced: 1994,
    rangeKm: 1100,
    speedMach: 1.8,
    payload: "Tien Chien I/II AAM",
    operators: ["TW"],
    notableFeatures: "Indigenous Taiwanese fighter",
    description:
      "Taiwan's indigenous defense fighter; complement to F-16V fleet.",
  },
  {
    slug: "saab-jas-39e",
    name: "Saab JAS 39E Gripen E",
    category: "fighter_aircraft",
    originCountryCode: "SE",
    yearIntroduced: 2019,
    rangeKm: 4000,
    speedMach: 2.0,
    payload: "Meteor, IRIS-T, RBS 15F, KEPD 350",
    operators: ["SE", "BR"],
    notableFeatures: "Most modern Gripen variant with PS-05/A Mk4 AESA radar",
    description:
      "Latest-gen Gripen; Brazilian local production at Embraer's São Paulo facility.",
  },

  // ============ Additional missiles ============
  {
    slug: "atacms",
    name: "MGM-140 ATACMS",
    category: "ballistic_missile",
    originCountryCode: "US",
    yearIntroduced: 1991,
    rangeKm: 300,
    payload: "Unitary or DPICM submunition",
    operators: [
      "US",
      "KR",
      "PL",
      "RO",
      "GR",
      "TR",
      "AE",
      "BH",
      "QA",
      "TW",
      "EE",
      "AU (procurement)",
      "UA (donated)",
    ],
    notableFeatures: "HIMARS / M270 launched; replaced by PrSM",
    description:
      "US tactical ballistic missile; Block IA at 300 km range used by Ukraine since 2024.",
  },
  {
    slug: "prsm",
    name: "PrSM (Precision Strike Missile)",
    category: "ballistic_missile",
    originCountryCode: "US",
    yearIntroduced: 2023,
    rangeKm: 500,
    payload: "Unitary",
    operators: ["US", "AU", "UK (procurement)", "PL"],
    notableFeatures: "ATACMS replacement; Increment 2 with maritime seeker",
    description:
      "Next-gen US Army surface-to-surface missile; 2/launcher (vs. 1 ATACMS).",
  },
  {
    slug: "iskander-m",
    name: "9K720 Iskander-M",
    category: "ballistic_missile",
    originCountryCode: "RU",
    yearIntroduced: 2006,
    rangeKm: 500,
    payload: "Conventional or low-yield nuclear",
    operators: ["RU", "BY (forward-deployed)", "AM"],
    notableFeatures: "Quasi-ballistic trajectory; nuclear-capable",
    description:
      "Russian short-range tactical ballistic missile; primary battlefield strike asset.",
  },
  {
    slug: "iskander-k",
    name: "9K720 Iskander-K (R-500)",
    category: "cruise_missile",
    originCountryCode: "RU",
    yearIntroduced: 2014,
    rangeKm: 500,
    payload: "Conventional",
    operators: ["RU"],
    notableFeatures:
      "GLCM variant of Iskander system; INF Treaty violation US position pre-2019",
    description:
      "Russian ground-launched cruise missile; cited by US as INF Treaty violation that led to US INF withdrawal.",
  },
  {
    slug: "kalibr-3m54",
    name: "3M-54 Kalibr (anti-ship variant)",
    category: "anti_ship",
    originCountryCode: "RU",
    yearIntroduced: 2012,
    rangeKm: 660,
    speedMach: 2.9,
    payload: "200 kg conventional",
    operators: ["RU", "IN"],
    notableFeatures: "Subsonic cruise + supersonic terminal sprint",
    description: "Russian sea-launched supersonic anti-ship missile.",
  },
  {
    slug: "yj-18",
    name: "YJ-18 (Eagle Strike 18)",
    category: "anti_ship",
    originCountryCode: "CN",
    yearIntroduced: 2015,
    rangeKm: 540,
    speedMach: 3.0,
    payload: "300 kg",
    operators: ["CN"],
    notableFeatures: "Subsonic cruise with supersonic terminal sprint",
    description:
      "Chinese version of Kalibr-style anti-ship missile; PLAN VLS standard.",
  },
  {
    slug: "yj-21",
    name: "YJ-21 anti-ship hypersonic",
    category: "hypersonic",
    originCountryCode: "CN",
    yearIntroduced: 2022,
    rangeKm: 1500,
    speedMach: 6,
    payload: "Conventional anti-ship",
    operators: ["CN"],
    notableFeatures: "Air-launched / VLS-launched hypersonic anti-ship",
    description:
      "Type 055 destroyer launches of YJ-21 demonstrated 2023; threat to US carrier strike groups.",
  },
  {
    slug: "naval-strike-missile",
    name: "Naval Strike Missile (NSM)",
    category: "anti_ship",
    originCountryCode: "NO",
    yearIntroduced: 2012,
    rangeKm: 250,
    payload: "125 kg HE",
    operators: ["NO", "PL", "US (Marines/Navy)", "MY", "DE", "RO", "AU", "CA"],
    notableFeatures: "Sea-skimming with 5th-gen IIR seeker",
    description:
      "Norwegian/US anti-ship missile; US Marines deploy as NMESIS shore-defense.",
  },
  {
    slug: "exocet-mm40-block3",
    name: "MM40 Block 3 Exocet",
    category: "anti_ship",
    originCountryCode: "FR",
    yearIntroduced: 2008,
    rangeKm: 200,
    payload: "165 kg",
    operators: ["FR", "GR", "QA", "EG", "MA", "MY", "OM", "AE", "ID"],
    notableFeatures: "Improved range and littoral capability",
    description: "Block 3 upgrade of classic Exocet anti-ship missile.",
  },
  {
    slug: "harpoon-block-ii",
    name: "AGM/RGM-84 Harpoon Block II",
    category: "anti_ship",
    originCountryCode: "US",
    yearIntroduced: 2002,
    rangeKm: 124,
    payload: "221 kg",
    operators: [
      "US",
      "AU",
      "BR",
      "CA",
      "DK",
      "DE",
      "GR",
      "IN",
      "ID",
      "JP",
      "KR",
      "NL",
      "PK",
      "PL",
      "PT",
      "SA",
      "SG",
      "ES",
      "TW",
      "TR",
      "AE",
      "GB",
    ],
    notableFeatures: "Block II SAR/INS plus GPS for littoral strike",
    description:
      "US standard sub/sea/air-launched anti-ship missile; widely exported.",
  },
  {
    slug: "type-12-ssm",
    name: "Type 12 anti-ship missile",
    category: "anti_ship",
    originCountryCode: "JP",
    yearIntroduced: 2015,
    rangeKm: 200,
    payload: "Conventional",
    operators: ["JP"],
    notableFeatures: "Extended-range upgrade in development to 1000+ km",
    description:
      "Japanese standard truck-launched anti-ship missile; Japan's stand-off counterstrike spine.",
  },
  {
    slug: "hyunmoo-3",
    name: "Hyunmoo-3",
    category: "cruise_missile",
    originCountryCode: "KR",
    yearIntroduced: 2006,
    rangeKm: 1500,
    payload: "500 kg conventional",
    operators: ["KR"],
    notableFeatures: "Subsonic LACM; cornerstone of ROK Kill Chain",
    description: "South Korean Tomahawk-class land-attack cruise missile.",
  },
  {
    slug: "babur-3",
    name: "Babur-3 cruise missile",
    category: "cruise_missile",
    originCountryCode: "PK",
    yearIntroduced: 2017,
    rangeKm: 450,
    payload: "Nuclear-capable",
    operators: ["PK"],
    notableFeatures: "Submarine-launched cruise missile",
    description:
      "Pakistani SLCM giving Pakistan a sea-based deterrent leg via Agosta-90B.",
  },
  {
    slug: "raad",
    name: "Ra'ad / Ra'ad-II ALCM",
    category: "cruise_missile",
    originCountryCode: "PK",
    yearIntroduced: 2013,
    rangeKm: 600,
    payload: "Nuclear-capable",
    operators: ["PK"],
    notableFeatures:
      "Air-launched cruise missile; Mirage III/V launch platform",
    description: "Pakistani ALCM; provides air-component nuclear deterrent.",
  },

  // ============ Additional air defense ============
  {
    slug: "irist-slm",
    name: "IRIS-T SLM",
    category: "air_defense",
    originCountryCode: "DE",
    yearIntroduced: 2022,
    rangeKm: 40,
    payload: "Hit-to-kill",
    operators: ["DE", "EG", "UA", "EE", "SE", "AT", "NO"],
    notableFeatures:
      "Highly effective in Ukraine vs. ballistic, cruise, and drone threats",
    description:
      "German short/medium-range air defense system; Ukraine deployment validated effectiveness.",
  },
  {
    slug: "samp-t",
    name: "SAMP/T (Aster 30 ground-based)",
    category: "air_defense",
    originCountryCode: "FR",
    yearIntroduced: 2011,
    rangeKm: 150,
    payload: "Aster 30 with hit-to-kill",
    operators: ["FR", "IT", "SG", "UA"],
    notableFeatures: "European Patriot-class system; SAMP/T NG in development",
    description:
      "Italo-French Aster 30 ground-based air defense; supplied to Ukraine.",
  },
  {
    slug: "pantsir-s1",
    name: "Pantsir-S1",
    category: "air_defense",
    originCountryCode: "RU",
    yearIntroduced: 2007,
    rangeKm: 20,
    payload: "57E6 missile + 30mm cannon",
    operators: ["RU", "DZ", "IR", "SY", "AE", "RS"],
    notableFeatures: "Combined missile-gun point-defense system",
    description:
      "Russian short-range air defense; widely fielded against UAV threats.",
  },
  {
    slug: "buk-m3",
    name: "9K317M Buk-M3",
    category: "air_defense",
    originCountryCode: "RU",
    yearIntroduced: 2016,
    rangeKm: 70,
    payload: "9M317M missile",
    operators: ["RU"],
    notableFeatures: "Latest Buk variant with improved 9M317M missile",
    description:
      "Russian medium-range mobile air defense; 6 missiles per launcher.",
  },

  // ============ Additional naval ============
  {
    slug: "type-055-renhai",
    name: "Type 055 Renhai-class destroyer",
    category: "destroyer",
    originCountryCode: "CN",
    yearIntroduced: 2020,
    payload: "112 VLS cells (YJ-18, HHQ-9, HHQ-26, CY-5)",
    operators: ["CN"],
    notableFeatures: "Largest non-US surface combatant; cruiser-sized",
    description:
      "Premier PLA Navy surface combatant; equivalent to US Ticonderoga in firepower.",
  },
  {
    slug: "zumwalt-class",
    name: "Zumwalt-class destroyer",
    category: "destroyer",
    originCountryCode: "US",
    yearIntroduced: 2016,
    payload:
      "80 Mk57 VLS cells; Conventional Prompt Strike (CPS) hypersonic from 2025",
    operators: ["US"],
    notableFeatures:
      "Stealth tumblehome hull; first US Navy hypersonic strike platform",
    description:
      "Three-ship US guided-missile destroyer class; hosts Conventional Prompt Strike hypersonic.",
  },
  {
    slug: "type-218sg",
    name: "Type 218SG Invincible-class SSK",
    category: "submarine",
    originCountryCode: "DE",
    yearIntroduced: 2022,
    payload: "Heavyweight torpedoes; capable of cruise missile carriage",
    operators: ["SG"],
    notableFeatures: "Lithium-ion AIP optional; tropical operations",
    description:
      "Most advanced non-nuclear submarine in Southeast Asia (Singapore).",
  },
  {
    slug: "u212cd",
    name: "Type 212CD",
    category: "submarine",
    originCountryCode: "DE",
    yearIntroduced: 2030,
    payload: "Torpedoes, Naval Strike Missile (procurement)",
    operators: ["DE", "NO"],
    notableFeatures: "Common design for Norwegian and German programs",
    description:
      "Joint German-Norwegian SSK program replacing Type 212A and Ula-class.",
  },
  {
    slug: "scorpene-class",
    name: "Scorpène-class SSK",
    category: "submarine",
    originCountryCode: "FR",
    yearIntroduced: 2005,
    payload: "F21 torpedo, Exocet SM39 anti-ship",
    operators: ["IN (Kalvari)", "MY", "CL", "BR"],
    notableFeatures: "AIP available; export success",
    description: "French Naval Group SSK; widely exported.",
  },
  {
    slug: "kilo-class-improved",
    name: "Project 636.3 Improved Kilo-class SSK",
    category: "submarine",
    originCountryCode: "RU",
    yearIntroduced: 2014,
    payload: "Type 53 torpedo, Kalibr-PL SLCM",
    operators: ["RU", "VN", "IN (legacy 877EKM)", "DZ"],
    notableFeatures: "Kalibr cruise missile capability; widely exported",
    description:
      "Russian diesel-electric SSK; Vietnam and Algeria operate full squadron strength.",
  },
  {
    slug: "type-039a-yuan",
    name: "Type 039A/B Yuan-class SSK",
    category: "submarine",
    originCountryCode: "CN",
    yearIntroduced: 2006,
    payload: "Yu-6 torpedo, YJ-18 SLCM",
    operators: ["CN", "PK (Hangor-II derivative)", "TH (procurement)"],
    notableFeatures:
      "AIP-equipped; first Chinese diesel SSK with cruise missile carriage",
    description:
      "PLA Navy diesel-electric submarine; export to Pakistan and Thailand.",
  },

  // ============ Additional tanks / IFVs ============
  {
    slug: "kf51-panther",
    name: "Rheinmetall KF51 Panther",
    category: "tank",
    originCountryCode: "DE",
    yearIntroduced: 2024,
    payload: "130mm Rheinmetall Future Gun System",
    operators: ["IT (procurement)"],
    notableFeatures:
      "First production-ready 130mm MBT; designed for European Main Ground Combat System",
    description:
      "Rheinmetall's next-gen MBT competing for European future-tank programs.",
  },
  {
    slug: "altay",
    name: "Altay MBT",
    category: "tank",
    originCountryCode: "TR",
    yearIntroduced: 2025,
    payload: "120mm Rheinmetall L/55",
    operators: ["TR"],
    notableFeatures: "Turkish indigenous MBT; Korean K2 technology basis",
    description: "Turkey's first indigenous MBT entering service.",
  },
  {
    slug: "type-10",
    name: "Type 10 MBT",
    category: "tank",
    originCountryCode: "JP",
    yearIntroduced: 2012,
    payload: "120mm L/44",
    operators: ["JP"],
    notableFeatures: "C4ISR-integrated; mobility tuned for Japanese terrain",
    description: "Japanese MBT optimized for archipelagic and urban terrain.",
  },

  // ============ Additional artillery ============
  {
    slug: "krasnopol",
    name: "2K25 Krasnopol guided artillery shell",
    category: "artillery",
    originCountryCode: "RU",
    rangeKm: 25,
    payload: "Laser-guided 152/155mm",
    operators: ["RU", "IN", "CN (license)"],
    notableFeatures: "Laser-designated guided artillery round",
    description: "Russian laser-guided artillery shell; widely exported.",
  },
  {
    slug: "excalibur",
    name: "M982 Excalibur",
    category: "artillery",
    originCountryCode: "US",
    rangeKm: 70,
    payload: "GPS/INS-guided 155mm",
    operators: ["US", "AU", "CA", "FR", "DE", "IT", "NL", "SE", "UA"],
    notableFeatures: "Increment Ib at 70 km range",
    description:
      "US precision-guided 155mm artillery shell; major Ukraine wartime supply.",
  },
  {
    slug: "smerch",
    name: "9K58 Smerch",
    category: "artillery",
    originCountryCode: "RU",
    rangeKm: 90,
    payload: "300mm rockets, various submunitions",
    operators: ["RU", "IN (Pinaka derivative)", "AE", "DZ", "VE"],
    notableFeatures: "Largest-caliber MLRS in service",
    description: "Russian 300mm 12-tube MLRS.",
  },
  {
    slug: "tornado-s",
    name: "Tornado-S MLRS",
    category: "artillery",
    originCountryCode: "RU",
    rangeKm: 120,
    payload: "300mm rockets with INS guidance",
    operators: ["RU"],
    notableFeatures: "Smerch successor with corrected/guided rockets",
    description:
      "Russian successor to Smerch with extended range and improved accuracy.",
  },

  // ============ Hypersonics expansion ============
  {
    slug: "agm-183-arrw",
    name: "AGM-183A ARRW (Air-launched Rapid Response Weapon)",
    category: "hypersonic",
    originCountryCode: "US",
    yearIntroduced: 2024,
    rangeKm: 1600,
    speedMach: 8,
    operators: ["US"],
    notableFeatures: "Boost-glide hypersonic launched from B-52H",
    description: "US Air Force hypersonic stand-off weapon; final tests 2024.",
  },
  {
    slug: "lrhw-dark-eagle",
    name: "Long-Range Hypersonic Weapon (Dark Eagle)",
    category: "hypersonic",
    originCountryCode: "US",
    yearIntroduced: 2025,
    rangeKm: 2775,
    speedMach: 17,
    operators: ["US"],
    notableFeatures: "Common-Hypersonic-Glide-Body warhead with US Navy IRCPS",
    description: "US Army truck-launched hypersonic; entering service 2025.",
  },
  {
    slug: "fattah-2",
    name: "Fattah-2",
    category: "hypersonic",
    originCountryCode: "IR",
    yearIntroduced: 2023,
    rangeKm: 1500,
    speedMach: 15,
    operators: ["IR"],
    notableFeatures: "Iran's claimed hypersonic glide vehicle",
    description:
      "Iranian hypersonic missile; capabilities and accuracy disputed.",
  },
];
