import type { WeaponSystem } from "./types";

export const weaponsA: WeaponSystem[] = [
  // Fifth-generation fighters
  {
    slug: "f-35a",
    name: "F-35A Lightning II",
    category: "fighter_aircraft",
    originCountryCode: "US",
    yearIntroduced: 2016,
    rangeKm: 2200,
    speedMach: 1.6,
    payload: "Up to 8.1 t internal/external; AIM-120, AIM-9X, JSM, B61-12, Storm Shadow (planned)",
    operators: ["US", "GB", "IT", "NL", "NO", "DK", "BE", "AU", "JP", "KR", "IL", "PL", "FI", "CA", "DE", "GR", "RO", "CZ", "SG"],
    notableFeatures: "All-aspect VLO; sensor fusion; F-35I 'Adir' configured for nuclear delivery in IL",
    description: "Conventional-takeoff variant of the Joint Strike Fighter. Backbone of the Western fifth-generation fleet.",
  },
  {
    slug: "f-35b",
    name: "F-35B Lightning II",
    category: "fighter_aircraft",
    originCountryCode: "US",
    yearIntroduced: 2015,
    rangeKm: 1600,
    speedMach: 1.6,
    payload: "Up to 6.8 t (STOVL constrained)",
    operators: ["US", "GB", "IT", "JP", "SG"],
    notableFeatures: "STOVL capability for amphibious assault ships and short-deck carriers",
    description: "Short-takeoff/vertical-landing F-35 variant. Operates from Queen Elizabeth, Cavour, Izumo/Kaga, Trieste, and Wasp/America-class.",
  },
  {
    slug: "f-35c",
    name: "F-35C Lightning II",
    category: "fighter_aircraft",
    originCountryCode: "US",
    yearIntroduced: 2019,
    rangeKm: 2200,
    speedMach: 1.6,
    payload: "Up to 8.1 t",
    operators: ["US"],
    notableFeatures: "Carrier-based variant with larger wing and reinforced gear",
    description: "CATOBAR-launched fifth-generation fighter for US Navy supercarriers.",
  },
  {
    slug: "f-22",
    name: "F-22A Raptor",
    category: "fighter_aircraft",
    originCountryCode: "US",
    yearIntroduced: 2005,
    rangeKm: 2960,
    speedMach: 2.25,
    payload: "AIM-120D, AIM-9X, JDAM",
    operators: ["US"],
    notableFeatures: "Supercruise; thrust-vectoring; air-superiority focus",
    description: "Premier Western air-superiority fighter; production curtailed at 187 airframes.",
  },
  {
    slug: "su-57",
    name: "Su-57 Felon",
    category: "fighter_aircraft",
    originCountryCode: "RU",
    yearIntroduced: 2020,
    rangeKm: 3500,
    speedMach: 2.0,
    payload: "Internal R-77M, Kh-59MK2, Kh-69; external pylons available",
    operators: ["RU"],
    notableFeatures: "Russia's first fifth-gen fighter; limited series production",
    description: "Russian fifth-generation multirole fighter. Combat-debuted in Ukraine in 2024 in stand-off strike role.",
  },
  {
    slug: "j-20",
    name: "Chengdu J-20 Mighty Dragon",
    category: "fighter_aircraft",
    originCountryCode: "CN",
    yearIntroduced: 2017,
    rangeKm: 5500,
    speedMach: 2.0,
    payload: "PL-15 BVR, PL-10 SRAAM, internal weapons bays",
    operators: ["CN"],
    notableFeatures: "Largest fifth-gen fighter; long-range air superiority over Pacific",
    description: "PLA Air Force's premier stealth fighter; operational fleet over 200 airframes.",
  },
  // 4.5-gen and key 4-gen fighters
  {
    slug: "rafale",
    name: "Dassault Rafale",
    category: "fighter_aircraft",
    originCountryCode: "FR",
    yearIntroduced: 2001,
    rangeKm: 3700,
    speedMach: 1.8,
    payload: "Meteor, MICA, SCALP, Exocet AM39, ASMP-A nuclear ALCM",
    operators: ["FR", "EG", "QA", "IN", "GR", "HR", "AE", "ID", "RS"],
    notableFeatures: "Sole French nuclear-delivery fighter; combat-experienced",
    description: "French omnirole fighter; performs nuclear-deterrent role with ASMP-A on French air component.",
  },
  {
    slug: "eurofighter-typhoon",
    name: "Eurofighter Typhoon",
    category: "fighter_aircraft",
    originCountryCode: "GB",
    yearIntroduced: 2003,
    rangeKm: 2900,
    speedMach: 2.0,
    payload: "Meteor, ASRAAM, Storm Shadow, Brimstone, Paveway",
    operators: ["GB", "DE", "IT", "ES", "AT", "SA", "OM", "KW", "QA"],
    notableFeatures: "Twin-engine BVR-optimized 4.5-gen fighter",
    description: "Quadrinational European air-superiority fighter; backbone of NATO QRA in central and southern Europe.",
  },
  {
    slug: "f-15ex",
    name: "F-15EX Eagle II",
    category: "fighter_aircraft",
    originCountryCode: "US",
    yearIntroduced: 2024,
    rangeKm: 4400,
    speedMach: 2.5,
    payload: "Up to 13.4 t including hypersonic AGM-183A ARRW",
    operators: ["US"],
    notableFeatures: "Largest payload of any US fighter; AESA radar; designed for stand-off carriers and missile truck role",
    description: "Latest Eagle variant replacing F-15C; carries AGM-183A ARRW hypersonic in air-launch role.",
  },
  {
    slug: "f-18ef-superhornet",
    name: "F/A-18E/F Super Hornet",
    category: "fighter_aircraft",
    originCountryCode: "US",
    yearIntroduced: 2001,
    rangeKm: 2300,
    speedMach: 1.8,
    payload: "AIM-120, AIM-9X, JASSM, LRASM, Harpoon, JDAM",
    operators: ["US", "AU", "KW"],
    notableFeatures: "Carrier-based multirole strike fighter with growing LRASM long-range anti-ship reach",
    description: "Backbone of US carrier air wings; will fly alongside F-35C through 2030s.",
  },
  // Bombers
  {
    slug: "b-2",
    name: "B-2 Spirit",
    category: "bomber",
    originCountryCode: "US",
    yearIntroduced: 1997,
    rangeKm: 11000,
    payload: "B61-12 / B83-1 nuclear; JASSM-ER, GBU-57 MOP",
    operators: ["US"],
    notableFeatures: "Sole flying-wing all-aspect VLO bomber",
    description: "Strategic stealth bomber; only platform certified for the GBU-57 Massive Ordnance Penetrator.",
  },
  {
    slug: "b-21",
    name: "B-21 Raider",
    category: "bomber",
    originCountryCode: "US",
    yearIntroduced: 2024,
    payload: "Conventional and nuclear (when certified)",
    operators: ["US"],
    notableFeatures: "Sixth-gen stealth flying-wing; networked with NGAD",
    description: "Next-generation strategic stealth bomber replacing B-2 and complementing B-52.",
  },
  {
    slug: "b-52h",
    name: "B-52H Stratofortress",
    category: "bomber",
    originCountryCode: "US",
    yearIntroduced: 1961,
    rangeKm: 14000,
    payload: "Up to 31.5 t conventional / nuclear ALCM-A / W80 warheads",
    operators: ["US"],
    notableFeatures: "Long-life airframe through 2050s; AGM-183 ARRW host",
    description: "Standoff long-range bomber and BTF rotational platform across Europe, Indo-Pacific, and Diego Garcia.",
  },
  {
    slug: "tu-160",
    name: "Tu-160 Blackjack",
    category: "bomber",
    originCountryCode: "RU",
    yearIntroduced: 1987,
    rangeKm: 12300,
    speedMach: 2.05,
    payload: "Kh-101 / Kh-102 ALCMs; Kh-555",
    operators: ["RU"],
    notableFeatures: "Variable-geometry wings; largest combat aircraft in service",
    description: "Russian strategic bomber; primary platform for Kh-101 strikes in Ukraine.",
  },
  {
    slug: "tu-95ms",
    name: "Tu-95MS Bear-H",
    category: "bomber",
    originCountryCode: "RU",
    yearIntroduced: 1981,
    rangeKm: 15000,
    payload: "Kh-101 / Kh-102 ALCMs",
    operators: ["RU"],
    notableFeatures: "Turboprop strategic platform; long-loiter cruise-missile carrier",
    description: "Russian long-range turboprop bomber; primary cruise missile carrier alongside Tu-160.",
  },
  {
    slug: "h-6k",
    name: "Xi'an H-6K/N",
    category: "bomber",
    originCountryCode: "CN",
    yearIntroduced: 2009,
    rangeKm: 6000,
    payload: "CJ-10 / CJ-100 / KD-20 ALCMs; air-launched ballistic (H-6N)",
    operators: ["CN"],
    notableFeatures: "H-6N variant carries air-launched ballistic missile (CH-AS-X-13)",
    description: "PLA Air Force long-range cruise-missile carrier; backbone of stand-off strike against Western Pacific targets.",
  },
  // Cruise missiles
  {
    slug: "tomahawk-block-v",
    name: "Tomahawk Block V",
    category: "cruise_missile",
    originCountryCode: "US",
    yearIntroduced: 2021,
    rangeKm: 1600,
    speedMach: 0.74,
    payload: "450 kg conventional unitary or submunition (now retired)",
    operators: ["US", "GB", "AU", "JP", "NL"],
    notableFeatures: "Block Va Maritime Strike Tomahawk; Block Vb upgraded warhead",
    description: "US standard sub-/ship-launched land-attack cruise missile; Block V adds anti-ship capability.",
  },
  {
    slug: "jassm-er",
    name: "AGM-158B JASSM-ER / -XR",
    category: "cruise_missile",
    originCountryCode: "US",
    yearIntroduced: 2014,
    rangeKm: 1000,
    payload: "450 kg unitary penetrator",
    operators: ["US", "AU", "FI", "NL", "PL", "JP"],
    notableFeatures: "Stealth, terrain-matching, GPS/INS guidance",
    description: "Air-launched stealthy stand-off land-attack cruise missile family.",
  },
  {
    slug: "lrasm",
    name: "AGM-158C LRASM",
    category: "anti_ship",
    originCountryCode: "US",
    yearIntroduced: 2018,
    rangeKm: 930,
    payload: "450 kg",
    operators: ["US", "AU"],
    notableFeatures: "Sensor-fused anti-ship; passive RF/IR seeker",
    description: "Long-Range Anti-Ship Missile derived from JASSM-ER; deployed on B-1B and F/A-18E/F.",
  },
  {
    slug: "storm-shadow",
    name: "Storm Shadow / SCALP-EG",
    category: "cruise_missile",
    originCountryCode: "GB",
    yearIntroduced: 2003,
    rangeKm: 560,
    payload: "BROACH penetrator warhead",
    operators: ["GB", "FR", "IT", "GR", "EG", "SA", "QA", "UA"],
    notableFeatures: "Combat-proven in Iraq, Libya, Ukraine",
    description: "Anglo-French air-launched stealthy stand-off cruise missile.",
  },
  {
    slug: "kalibr",
    name: "Kalibr (3M14 / 3M54)",
    category: "cruise_missile",
    originCountryCode: "RU",
    yearIntroduced: 2012,
    rangeKm: 2500,
    payload: "Conventional or low-yield nuclear",
    operators: ["RU", "IN (BrahMos co-development)"],
    notableFeatures: "Family includes anti-ship and land-attack variants",
    description: "Russian sea-launched land-attack and anti-ship cruise missile family. Used heavily against Ukraine since 2022.",
  },
  {
    slug: "kh-101",
    name: "Kh-101 / Kh-102",
    category: "cruise_missile",
    originCountryCode: "RU",
    yearIntroduced: 2013,
    rangeKm: 4500,
    payload: "Kh-102 carries nuclear warhead",
    operators: ["RU"],
    notableFeatures: "Air-launched stealth profile; reduced RCS",
    description: "Russian air-launched long-range cruise missile family launched from Tu-95MS and Tu-160.",
  },
  {
    slug: "kinzhal",
    name: "Kh-47M2 Kinzhal",
    category: "hypersonic",
    originCountryCode: "RU",
    yearIntroduced: 2017,
    rangeKm: 2000,
    speedMach: 10,
    payload: "500 kg conventional or nuclear",
    operators: ["RU"],
    notableFeatures: "Air-launched aero-ballistic; carried by MiG-31K and Tu-22M3",
    description: "Russian air-launched hypersonic ballistic missile; intercepted by Ukrainian Patriot in 2023.",
  },
  {
    slug: "avangard",
    name: "Avangard HGV",
    category: "hypersonic",
    originCountryCode: "RU",
    yearIntroduced: 2019,
    speedMach: 27,
    payload: "Nuclear (~2 MT yield reported)",
    operators: ["RU"],
    notableFeatures: "Hypersonic glide vehicle on UR-100UTTKh / Sarmat ICBM",
    description: "Russian boost-glide vehicle; classified as a strategic asset under New START.",
  },
  {
    slug: "zircon",
    name: "3M22 Zircon",
    category: "hypersonic",
    originCountryCode: "RU",
    yearIntroduced: 2022,
    rangeKm: 1000,
    speedMach: 9,
    payload: "Conventional",
    operators: ["RU"],
    notableFeatures: "Sea-launched scramjet hypersonic cruise missile",
    description: "Russian hypersonic anti-ship and land-attack cruise missile fielded on Yasen-M and Admiral Gorshkov.",
  },
  {
    slug: "df-21d",
    name: "DF-21D Anti-Ship Ballistic Missile",
    category: "ballistic_missile",
    originCountryCode: "CN",
    yearIntroduced: 2010,
    rangeKm: 1500,
    payload: "Maneuvering re-entry vehicle (MaRV), conventional",
    operators: ["CN"],
    notableFeatures: "First operational anti-ship ballistic missile ('carrier killer')",
    description: "PLA Rocket Force road-mobile MRBM with anti-ship variant aimed at US carrier strike groups.",
  },
  {
    slug: "df-26",
    name: "DF-26 IRBM",
    category: "ballistic_missile",
    originCountryCode: "CN",
    yearIntroduced: 2016,
    rangeKm: 4000,
    payload: "Conventional or nuclear; anti-ship variant",
    operators: ["CN"],
    notableFeatures: "'Guam killer'; range to threaten US Pacific bases",
    description: "Dual-capable PLARF intermediate-range ballistic missile threatening US Pacific bases and naval assets.",
  },
  {
    slug: "df-17",
    name: "DF-17",
    category: "hypersonic",
    originCountryCode: "CN",
    yearIntroduced: 2019,
    rangeKm: 2500,
    speedMach: 10,
    payload: "DF-ZF hypersonic glide vehicle",
    operators: ["CN"],
    notableFeatures: "First operational HGV-equipped MRBM",
    description: "Chinese MRBM topped with the DF-ZF hypersonic glide vehicle.",
  },
  {
    slug: "brahmos",
    name: "BrahMos",
    category: "cruise_missile",
    originCountryCode: "IN",
    yearIntroduced: 2005,
    rangeKm: 800,
    speedMach: 3.0,
    payload: "300 kg conventional",
    operators: ["IN", "PH"],
    notableFeatures: "Indo-Russian supersonic cruise missile; air, ship, sub, and land variants; first export sale to Philippines",
    description: "Versatile supersonic cruise missile family; recently exported to the Philippines for shore-based anti-ship role.",
  },
  // Air defense systems
  {
    slug: "patriot-pac3",
    name: "Patriot PAC-3 MSE",
    category: "air_defense",
    originCountryCode: "US",
    yearIntroduced: 2015,
    rangeKm: 35,
    payload: "Hit-to-kill interceptor",
    operators: ["US", "DE", "NL", "JP", "KR", "SA", "AE", "TW", "PL", "RO", "SE", "ES", "GR", "QA", "BH"],
    notableFeatures: "Hit-to-kill against TBMs, cruise missiles, and aircraft",
    description: "US-led Patriot upgrade; backbone of Western lower-tier ballistic-missile defense.",
  },
  {
    slug: "thaad",
    name: "Terminal High Altitude Area Defense (THAAD)",
    category: "air_defense",
    originCountryCode: "US",
    yearIntroduced: 2008,
    rangeKm: 200,
    payload: "Hit-to-kill (kinetic kill vehicle)",
    operators: ["US", "AE", "SA", "KR (Seongju)"],
    notableFeatures: "Endo/exoatmospheric hit-to-kill against MRBMs/IRBMs",
    description: "US area BMD against medium- and intermediate-range ballistic missiles.",
  },
  {
    slug: "aegis-bmd-sm3",
    name: "Aegis BMD with SM-3 Block IIA",
    category: "air_defense",
    originCountryCode: "US",
    rangeKm: 2500,
    operators: ["US", "JP", "KR", "ES (host Aegis BMD ships)"],
    notableFeatures: "Sea- and land-based; SM-3 Block IIA tested against ICBM in 2020",
    description: "Naval and Aegis Ashore BMD using SPY-1/-6 radar and SM-3 family interceptors.",
  },
  {
    slug: "iron-dome",
    name: "Iron Dome",
    category: "air_defense",
    originCountryCode: "IL",
    yearIntroduced: 2011,
    rangeKm: 70,
    payload: "Tamir interceptor",
    operators: ["IL", "US (procurement)", "AZ", "RO (procurement)", "SG (procurement)"],
    notableFeatures: "Counter-rocket / artillery / mortar; high engagement rates demonstrated",
    description: "Israeli short-range air defense system; high-volume defense against rockets and artillery.",
  },
  {
    slug: "davids-sling",
    name: "David's Sling",
    category: "air_defense",
    originCountryCode: "IL",
    yearIntroduced: 2017,
    rangeKm: 300,
    operators: ["IL", "FI"],
    notableFeatures: "Mid-tier missile defense bridging Iron Dome and Arrow",
    description: "Israeli medium-range air and missile defense system.",
  },
  {
    slug: "arrow-3",
    name: "Arrow 3",
    category: "air_defense",
    originCountryCode: "IL",
    yearIntroduced: 2017,
    rangeKm: 2400,
    operators: ["IL", "DE (procurement)"],
    notableFeatures: "Exoatmospheric hit-to-kill against IRBMs",
    description: "Israeli upper-tier ballistic-missile interceptor; selected by Germany for European Sky Shield.",
  },
  {
    slug: "s-400",
    name: "S-400 Triumf",
    category: "air_defense",
    originCountryCode: "RU",
    yearIntroduced: 2007,
    rangeKm: 400,
    operators: ["RU", "CN", "TR", "IN", "BY"],
    notableFeatures: "40N6E missile claimed 400 km; layered with shorter-range 48N6 and 9M96",
    description: "Russian long-range SAM family; sale to Türkiye triggered US F-35 expulsion.",
  },
  {
    slug: "s-500",
    name: "S-500 Prometheus",
    category: "air_defense",
    originCountryCode: "RU",
    yearIntroduced: 2021,
    rangeKm: 600,
    operators: ["RU"],
    notableFeatures: "Anti-IRBM and anti-LEO satellite engagement claimed",
    description: "Russian next-generation air and space defense system; small numbers fielded.",
  },
  {
    slug: "hq-9",
    name: "HQ-9 / HQ-9B",
    category: "air_defense",
    originCountryCode: "CN",
    yearIntroduced: 2003,
    rangeKm: 250,
    operators: ["CN", "PK", "TM", "RS"],
    notableFeatures: "Chinese long-range SAM; deployed on Spratly outposts",
    description: "PLAN/PLAGF long-range SAM; fielded on Type 052D destroyers and South China Sea reefs.",
  },
  {
    slug: "nasams",
    name: "NASAMS",
    category: "air_defense",
    originCountryCode: "NO",
    yearIntroduced: 1998,
    rangeKm: 50,
    payload: "AIM-120 AMRAAM, AIM-9X, AIM-120-ER",
    operators: ["NO", "US", "FI", "ES", "NL", "LT", "OM", "AU", "QA", "ID", "UA", "HU"],
    notableFeatures: "Distributed networked launcher concept; co-developed by Kongsberg and Raytheon",
    description: "Norwegian/US medium-range air defense system providing layered defense for the National Capital Region (US) and frontline NATO/Ukraine deployments.",
  },
];
